import React, { useEffect, useRef, useState, useMemo, memo } from 'react';
import * as THREE from 'three';
import {
  RotateCcw,
  Maximize2,
  ZoomIn,
  ZoomOut,
  Eye,
  EyeOff,
  Layers,
  Sparkles,
  Info,
  ShieldCheck,
  Zap,
  Box,
  Compass,
  Flame,
  CheckCircle2,
  Camera,
  Download,
  Image as ImageIcon,
  Check,
  Loader2,
  Copy,
  AlertTriangle,
  Radio,
  Power,
  Sliders,
  Move
} from 'lucide-react';
import { InteractiveComponent, Wire } from './PhysicalBoardSimulationTab';
import { AutoGeneratedCircuit } from '../types';

export interface BoardSimulator3DProps {
  components: InteractiveComponent[];
  wires?: Wire[];
  circuits?: AutoGeneratedCircuit[];
  isThreePhase?: boolean;
  isEnergized?: boolean;
  onToggleEnergized?: () => void;
  onToggleBreaker?: (compId: string) => void;
  onCaptureScreenshot?: (dataUrl: string) => void;
}

/**
 * Creates ultra-high-resolution procedural canvas textures for real electrical component faceplates (PBR)
 */
function createComponentFaceplateTexture(
  type: 'MCB' | 'IGA' | 'RCD' | 'DPS' | 'PILOT_LIGHTS' | 'LOAD' | 'GRID' | string,
  tag: string,
  name: string,
  ampacity?: number,
  curve?: string,
  isThreePhase?: boolean,
  isOverflow?: boolean,
  isEnergized?: boolean,
  isOff?: boolean,
  liveVolts: number = 222.4
): THREE.CanvasTexture {
  const canvas = document.createElement('canvas');
  canvas.width = 1024;
  canvas.height = 2048;
  const ctx = canvas.getContext('2d');
  if (!ctx) return new THREE.CanvasTexture(canvas);

  // Background body tone with subtle industrial texture
  let bgGradient = ctx.createLinearGradient(0, 0, 1024, 2048);
  if (type === 'DPS') {
    bgGradient.addColorStop(0, '#0c2340');
    bgGradient.addColorStop(0.3, '#081a30');
    bgGradient.addColorStop(0.7, '#051324');
    bgGradient.addColorStop(1, '#020b17');
  } else if (type === 'PILOT_LIGHTS') {
    bgGradient.addColorStop(0, '#1e2638');
    bgGradient.addColorStop(0.5, '#131926');
    bgGradient.addColorStop(1, '#0c101a');
  } else {
    // High-grade RAL 7035 light grey electrical engineering thermoplastic
    bgGradient.addColorStop(0, '#fafcff');
    bgGradient.addColorStop(0.2, '#f1f5f9');
    bgGradient.addColorStop(0.6, '#e2e8f0');
    bgGradient.addColorStop(0.9, '#cbd5e1');
    bgGradient.addColorStop(1, '#94a3b8');
  }

  ctx.fillStyle = bgGradient;
  ctx.fillRect(0, 0, 1024, 2048);

  // Molded plastic chamfers and hairline seam lines
  ctx.strokeStyle = type === 'DPS' ? '#1e3a8a' : '#94a3b8';
  ctx.lineWidth = 8;
  ctx.strokeRect(16, 16, 992, 2016);

  // Terminal cage recesses on top and bottom
  ctx.fillStyle = type === 'DPS' ? '#030a14' : '#475569';
  ctx.fillRect(32, 32, 960, 240);
  ctx.fillRect(32, 1776, 960, 240);

  // Ventilation / arc-chute side relief vents
  ctx.fillStyle = type === 'DPS' ? '#020810' : '#64748b';
  for (let y = 320; y < 500; y += 40) {
    ctx.fillRect(60, y, 120, 18);
    ctx.fillRect(844, y, 120, 18);
  }

  // Laser Etched Brand Header & SEC Approval
  ctx.fillStyle = type === 'DPS' ? '#38bdf8' : '#0f172a';
  ctx.font = 'bold 72px sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('NEOVOLT SEC', 512, 380);

  ctx.font = 'bold 40px monospace';
  ctx.fillStyle = type === 'DPS' ? '#94a3b8' : '#64748b';
  ctx.fillText('IEC/EN 60898-1 • 50Hz', 512, 440);

  // Circuit Tag Badge Plate (e.g., [ C1 ], [ RCD-1 ], [ DPS-1 ], [ IGA-1 ])
  const displayTag = tag || (type === 'MCB' ? name.split(' ')[0] : type);
  ctx.fillStyle = isOverflow ? '#dc2626' : (type === 'DPS' ? '#0284c7' : '#0284c7');
  ctx.beginPath();
  ctx.roundRect(192, 500, 640, 140, 32);
  ctx.fill();

  ctx.fillStyle = '#ffffff';
  ctx.font = '900 80px monospace';
  ctx.fillText(displayTag, 512, 600);

  // Ratings, breaking capacities and technical markings
  if (type === 'MCB' || type === 'IGA') {
    const mainCurve = curve || 'C';
    const mainAmps = ampacity || (type === 'IGA' ? 25 : 16);

    ctx.fillStyle = '#0f172a';
    ctx.font = '900 156px sans-serif';
    ctx.fillText(`${mainCurve}${mainAmps}`, 512, 860);

    // Voltage rating
    ctx.font = 'bold 48px monospace';
    ctx.fillStyle = '#475569';
    ctx.fillText(isThreePhase ? '400V~ / 230V~' : '230V~', 512, 960);

    // Breaking capacity box: 6000 [3] (IEC standard)
    ctx.strokeStyle = '#0f172a';
    ctx.lineWidth = 8;
    ctx.strokeRect(352, 1040, 320, 112);
    ctx.fillStyle = '#0f172a';
    ctx.font = 'bold 64px monospace';
    ctx.fillText('6000', 460, 1120);
    ctx.strokeRect(600, 1048, 60, 96);
    ctx.font = 'bold 52px monospace';
    ctx.fillText('3', 630, 1120);

    // Schematic symbol etched
    ctx.strokeStyle = '#475569';
    ctx.lineWidth = 8;
    ctx.beginPath();
    ctx.moveTo(420, 1280);
    ctx.lineTo(420, 1340);
    ctx.lineTo(520, 1300);
    ctx.lineTo(520, 1400);
    ctx.stroke();

    // SEC Certification holographic / QR seal placeholder
    ctx.fillStyle = '#cbd5e1';
    ctx.fillRect(436, 1480, 152, 152);
    ctx.strokeStyle = '#0f172a';
    ctx.lineWidth = 4;
    ctx.strokeRect(436, 1480, 152, 152);
    ctx.fillStyle = '#0f172a';
    ctx.font = '900 28px monospace';
    ctx.fillText('SEC-CL', 512, 1570);
  } else if (type === 'RCD') {
    const mainAmps = ampacity || 25;
    ctx.fillStyle = '#0f172a';
    ctx.font = '900 136px sans-serif';
    ctx.fillText(`In ${mainAmps}A`, 512, 820);

    ctx.fillStyle = '#dc2626';
    ctx.font = '900 96px sans-serif';
    ctx.fillText('IΔn 30mA', 512, 960);

    ctx.font = 'bold 48px monospace';
    ctx.fillStyle = '#475569';
    ctx.fillText('Tipo AC • [ T ] Test', 512, 1060);

    // RCD Test button icon
    ctx.fillStyle = '#f59e0b';
    ctx.beginPath();
    ctx.arc(512, 1240, 72, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = '#000000';
    ctx.font = '900 88px sans-serif';
    ctx.fillText('T', 512, 1270);

    ctx.font = 'bold 36px sans-serif';
    ctx.fillStyle = '#64748b';
    ctx.fillText('Pulsar Mensualmente', 512, 1360);
  } else if (type === 'DPS') {
    ctx.fillStyle = '#38bdf8';
    ctx.font = '900 104px sans-serif';
    ctx.fillText('SURGE PROTECT', 512, 820);

    ctx.fillStyle = '#facc15';
    ctx.font = 'bold 68px monospace';
    ctx.fillText('SPD T2 • 20/40kA', 512, 940);

    ctx.fillStyle = '#ffffff';
    ctx.font = '48px monospace';
    ctx.fillText('Uc: 275V~ | Up ≤ 1.5kV', 512, 1060);

    // Live Digital LED Voltmeter Display Screen
    ctx.fillStyle = isEnergized ? '#02182b' : '#030a14';
    ctx.fillRect(256, 1140, 512, 150);
    ctx.strokeStyle = isEnergized ? '#0284c7' : '#1e293b';
    ctx.lineWidth = 8;
    ctx.strokeRect(256, 1140, 512, 150);

    if (isEnergized) {
      ctx.fillStyle = '#38bdf8';
      ctx.shadowColor = '#0284c7';
      ctx.shadowBlur = 20;
      ctx.font = '900 96px monospace';
      ctx.fillText(`${liveVolts.toFixed(1)} V~`, 512, 1250);
      ctx.shadowBlur = 0;
    } else {
      ctx.fillStyle = '#334155';
      ctx.font = '900 80px monospace';
      ctx.fillText('---.- V', 512, 1245);
    }

    // Optical cartridge status window
    ctx.fillStyle = '#052e16';
    ctx.strokeStyle = '#22c55e';
    ctx.lineWidth = 8;
    ctx.strokeRect(312, 1360, 400, 100);
    ctx.fillRect(312, 1360, 400, 100);
    ctx.fillStyle = '#4ade80';
    ctx.font = '900 56px monospace';
    ctx.fillText('STATUS: OK', 512, 1430);
  } else if (type === 'PILOT_LIGHTS') {
    ctx.fillStyle = '#f59e0b';
    ctx.font = 'bold 72px sans-serif';
    ctx.fillText('SEÑALIZACIÓN SEC', 512, 840);
    ctx.fillStyle = '#94a3b8';
    ctx.font = '48px monospace';
    ctx.fillText('LED 230V~ 50Hz', 512, 940);

    ctx.fillStyle = isEnergized ? '#22c55e' : '#64748b';
    ctx.font = '900 52px monospace';
    ctx.fillText(isEnergized ? '⚡ RED ENERGIZADA' : '⭕ RED DESCONECTADA', 512, 1100);
  }

  // Capacity overflow visual warning label
  if (isOverflow) {
    ctx.fillStyle = '#7f1d1d';
    ctx.fillRect(40, 1580, 944, 160);
    ctx.strokeStyle = '#ef4444';
    ctx.lineWidth = 12;
    ctx.strokeRect(40, 1580, 944, 160);
    ctx.fillStyle = '#ffffff';
    ctx.font = '900 64px sans-serif';
    ctx.fillText('⚠️ SOBRECUPO DIN', 512, 1680);
  }

  const texture = new THREE.CanvasTexture(canvas);
  texture.needsUpdate = true;
  return texture;
}

export const BoardSimulator3DComponent: React.FC<BoardSimulator3DProps> = ({
  components,
  wires = [],
  circuits = [],
  isThreePhase = false,
  isEnergized: externalIsEnergized,
  onToggleEnergized,
  onToggleBreaker,
  onCaptureScreenshot,
}) => {
  const mountRef = useRef<HTMLDivElement | null>(null);
  const [selectedComp, setSelectedComp] = useState<InteractiveComponent | null>(null);
  const [doorOpen, setDoorOpen] = useState(true);
  const [showWireDucts, setShowWireDucts] = useState(true);
  const [show3DWires, setShow3DWires] = useState(true);
  const [internalEnergized, setInternalEnergized] = useState(false);
  const [viewPreset, setViewPreset] = useState<'iso' | 'front' | 'top' | 'side' | 'bornes_top' | 'bornes_bot'>('iso');

  // Sync energized state between props and internal
  const isEnergized = externalIsEnergized !== undefined ? externalIsEnergized : internalEnergized;

  // Screenshot capture states
  const [showCaptureMenu, setShowCaptureMenu] = useState(false);
  const [isCapturing, setIsCapturing] = useState(false);
  const [captureFeedback, setCaptureFeedback] = useState<string | null>(null);
  const [shutterFlash, setShutterFlash] = useState(false);

  // Dynamic live voltage fluctuation
  const [liveVolts, setLiveVolts] = useState(222.4);
  useEffect(() => {
    if (!isEnergized) {
      setLiveVolts(0);
      return;
    }
    const interval = setInterval(() => {
      const base = isThreePhase ? 380.5 : 222.4;
      const jitter = (Math.sin(Date.now() / 1000) * 1.5 + (Math.random() * 0.6 - 0.3));
      setLiveVolts(+(base + jitter).toFixed(1));
    }, 800);
    return () => clearInterval(interval);
  }, [isEnergized, isThreePhase]);

  // Three.js Scene, Renderer & Animation References
  const sceneRef = useRef<THREE.Scene | null>(null);
  const rendererRef = useRef<THREE.WebGLRenderer | null>(null);
  const cameraRef = useRef<THREE.PerspectiveCamera | null>(null);
  const doorMeshRef = useRef<THREE.Group | null>(null);
  const clickableMeshesRef = useRef<Array<{ mesh: THREE.Object3D; comp: InteractiveComponent; leverMesh?: THREE.Mesh }>>([]);
  const pilotLightSourcesRef = useRef<THREE.PointLight[]>([]);
  const particleSystemRef = useRef<THREE.Points | null>(null);

  // Camera Orbit & Pan State
  const isOrbitingRef = useRef(false);
  const isPanningRef = useRef(false);
  const previousMousePosRef = useRef({ x: 0, y: 0 });
  const cameraTargetRef = useRef<THREE.Vector3>(new THREE.Vector3(0, 0, 0));
  const cameraSphericalRef = useRef({ radius: 48, theta: Math.PI / 4, phi: Math.PI / 3 });

  // Toggle Energized Handler
  const handleToggleEnergized = () => {
    if (onToggleEnergized) {
      onToggleEnergized();
    } else {
      setInternalEnergized(prev => !prev);
    }
  };

  // Initialize Three.js Scene with PBR Materials, Studio Lighting, Real Wires & Particles
  useEffect(() => {
    const container = mountRef.current;
    if (!container) return;

    const width = container.clientWidth || 800;
    const height = container.clientHeight || 550;

    // 1. Scene & Dark Technical Atmosphere
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x070b14);
    scene.fog = new THREE.FogExp2(0x070b14, 0.01);
    sceneRef.current = scene;

    // 2. Camera Setup with Orbit + Pan Target
    const camera = new THREE.PerspectiveCamera(40, width / height, 0.1, 1000);
    cameraRef.current = camera;

    const updateCameraTransform = () => {
      const { radius, theta, phi } = cameraSphericalRef.current;
      const target = cameraTargetRef.current;
      camera.position.x = target.x + radius * Math.sin(phi) * Math.sin(theta);
      camera.position.y = target.y + radius * Math.cos(phi);
      camera.position.z = target.z + radius * Math.sin(phi) * Math.cos(theta);
      camera.lookAt(target);
    };
    updateCameraTransform();

    // 3. High-Fidelity WebGL Renderer with ACES ToneMapping & Soft Shadows
    const renderer = new THREE.WebGLRenderer({
      antialias: true,
      alpha: false,
      powerPreference: 'high-performance',
      preserveDrawingBuffer: true,
    });
    renderer.setSize(width, height);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    renderer.toneMappingExposure = 1.15;
    rendererRef.current = renderer;

    container.replaceChildren(renderer.domElement);

    // 4. STUDIO LIGHTING RIG (Key, Fill, Rim, Top & Bounce Lights)
    // Studio Ambient Light for neutral fill
    const ambientLight = new THREE.AmbientLight(0xffffff, 0.45);
    scene.add(ambientLight);

    // Studio Key Light (High-angle soft shadow caster)
    const keyLight = new THREE.DirectionalLight(0xffffff, 1.6);
    keyLight.position.set(25, 45, 30);
    keyLight.castShadow = true;
    keyLight.shadow.mapSize.width = 2048;
    keyLight.shadow.mapSize.height = 2048;
    keyLight.shadow.bias = -0.0001;
    keyLight.shadow.camera.near = 10;
    keyLight.shadow.camera.far = 120;
    keyLight.shadow.camera.left = -30;
    keyLight.shadow.camera.right = 30;
    keyLight.shadow.camera.top = 30;
    keyLight.shadow.camera.bottom = -30;
    scene.add(keyLight);

    // Studio Fill Light (Cool daylight tone to soften contrast)
    const fillLight = new THREE.DirectionalLight(0x94a3b8, 0.7);
    fillLight.position.set(-25, 20, 25);
    scene.add(fillLight);

    // Left Specular Rim Light (sharp plastic bevel highlights)
    const leftRimLight = new THREE.DirectionalLight(0x38bdf8, 0.9);
    leftRimLight.position.set(-35, 30, -15);
    scene.add(leftRimLight);

    // Top Rim Light (galvanized DIN rail metallic sheen)
    const topRimLight = new THREE.DirectionalLight(0xe2e8f0, 0.65);
    topRimLight.position.set(0, 35, -10);
    scene.add(topRimLight);

    // Ground Bounce Light (simulating reflection from enclosure baseplate)
    const bounceLight = new THREE.DirectionalLight(0x64748b, 0.5);
    bounceLight.position.set(0, -30, 20);
    scene.add(bounceLight);

    // 5. ENCLOSURE & INDUSTRIAL DIN 35mm HARDWARE
    const cabinetGroup = new THREE.Group();
    scene.add(cabinetGroup);

    const cabWidth = 42;
    const cabHeight = 32;
    const cabDepth = 12;

    // Galvanized steel back mounting plate with realistic specular & roughness
    const backPlateMat = new THREE.MeshStandardMaterial({
      color: 0x1e293b,
      metalness: 0.88,
      roughness: 0.25,
    });
    const backPlate = new THREE.Mesh(new THREE.BoxGeometry(cabWidth - 1, cabHeight - 1, 0.6), backPlateMat);
    backPlate.position.set(0, 0, -cabDepth / 2 + 0.3);
    backPlate.receiveShadow = true;
    cabinetGroup.add(backPlate);

    // Heavy-duty IP65 Thermoplastic Enclosure Frame (RAL 7035)
    const frameMat = new THREE.MeshPhysicalMaterial({
      color: 0x334155,
      metalness: 0.2,
      roughness: 0.35,
      clearcoat: 0.2,
    });

    const topWall = new THREE.Mesh(new THREE.BoxGeometry(cabWidth, 1.0, cabDepth), frameMat);
    topWall.position.set(0, cabHeight / 2, 0);
    topWall.castShadow = true;
    cabinetGroup.add(topWall);

    const botWall = new THREE.Mesh(new THREE.BoxGeometry(cabWidth, 1.0, cabDepth), frameMat);
    botWall.position.set(0, -cabHeight / 2, 0);
    cabinetGroup.add(botWall);

    const leftWall = new THREE.Mesh(new THREE.BoxGeometry(1.0, cabHeight, cabDepth), frameMat);
    leftWall.position.set(-cabWidth / 2, 0, 0);
    cabinetGroup.add(leftWall);

    const rightWall = new THREE.Mesh(new THREE.BoxGeometry(1.0, cabHeight, cabDepth), frameMat);
    rightWall.position.set(cabWidth / 2, 0, 0);
    cabinetGroup.add(rightWall);

    // DIN 35mm Top-Hat Rails (Perforated Zinc Galvanized Steel IEC 60715)
    const railMat = new THREE.MeshStandardMaterial({
      color: 0xe2e8f0,
      metalness: 0.95,
      roughness: 0.12,
    });

    const createDinRail = (yPos: number) => {
      const railGroup = new THREE.Group();
      const flat = new THREE.Mesh(new THREE.BoxGeometry(cabWidth - 4, 1.2, 0.25), railMat);
      railGroup.add(flat);

      const topLip = new THREE.Mesh(new THREE.BoxGeometry(cabWidth - 4, 0.25, 0.45), railMat);
      topLip.position.set(0, 0.6, 0.22);
      railGroup.add(topLip);

      const botLip = new THREE.Mesh(new THREE.BoxGeometry(cabWidth - 4, 0.25, 0.45), railMat);
      botLip.position.set(0, -0.6, 0.22);
      railGroup.add(botLip);

      railGroup.position.set(0, yPos, -cabDepth / 2 + 1.2);
      return railGroup;
    };

    const dinRail1 = createDinRail(5.0);
    cabinetGroup.add(dinRail1);

    const dinRail2 = createDinRail(-5.5);
    cabinetGroup.add(dinRail2);

    // Slotted Wire Ducts (Canaletas Ranuradas Industriales)
    if (showWireDucts) {
      const ductMat = new THREE.MeshStandardMaterial({
        color: 0x475569,
        metalness: 0.1,
        roughness: 0.6,
      });

      const topDuct = new THREE.Mesh(new THREE.BoxGeometry(cabWidth - 3, 1.8, 1.8), ductMat);
      topDuct.position.set(0, cabHeight / 2 - 2.2, -cabDepth / 2 + 1.2);
      cabinetGroup.add(topDuct);

      const botDuct = new THREE.Mesh(new THREE.BoxGeometry(cabWidth - 3, 1.8, 1.8), ductMat);
      botDuct.position.set(0, -cabHeight / 2 + 2.2, -cabDepth / 2 + 1.2);
      cabinetGroup.add(botDuct);

      const leftDuct = new THREE.Mesh(new THREE.BoxGeometry(1.8, cabHeight - 6, 1.8), ductMat);
      leftDuct.position.set(-cabWidth / 2 + 2.2, 0, -cabDepth / 2 + 1.2);
      cabinetGroup.add(leftDuct);

      const rightDuct = new THREE.Mesh(new THREE.BoxGeometry(1.8, cabHeight - 6, 1.8), ductMat);
      rightDuct.position.set(cabWidth / 2 - 2.2, 0, -cabDepth / 2 + 1.2);
      cabinetGroup.add(rightDuct);
    }

    // Brass Distribution Bars (PE Earth Bar & N Neutral Bar)
    const brassMat = new THREE.MeshStandardMaterial({
      color: 0xd97706,
      metalness: 0.92,
      roughness: 0.22,
    });
    const screwMat = new THREE.MeshStandardMaterial({
      color: 0x94a3b8,
      metalness: 0.94,
      roughness: 0.14,
    });

    const createTerminalBar = (isEarth: boolean, yPos: number) => {
      const barGroup = new THREE.Group();
      const barMesh = new THREE.Mesh(new THREE.BoxGeometry(18, 0.75, 0.75), brassMat);
      barGroup.add(barMesh);

      for (let i = 0; i < 10; i++) {
        const screw = new THREE.Mesh(new THREE.CylinderGeometry(0.22, 0.22, 0.4, 12), screwMat);
        screw.position.set(-8 + i * 1.75, 0.42, 0);
        barGroup.add(screw);
      }

      const holderMat = new THREE.MeshStandardMaterial({
        color: isEarth ? 0x16a34a : 0x2563eb,
        roughness: 0.35,
      });
      const leftHolder = new THREE.Mesh(new THREE.BoxGeometry(0.85, 1.3, 1.1), holderMat);
      leftHolder.position.set(-9.2, 0, 0);
      barGroup.add(leftHolder);

      const rightHolder = new THREE.Mesh(new THREE.BoxGeometry(0.85, 1.3, 1.1), holderMat);
      rightHolder.position.set(9.2, 0, 0);
      barGroup.add(rightHolder);

      barGroup.position.set(isEarth ? 8.5 : -8.5, yPos, -cabDepth / 2 + 1.5);
      return barGroup;
    };

    const peBar = createTerminalBar(true, cabHeight / 2 - 4.2);
    cabinetGroup.add(peBar);

    const nBar = createTerminalBar(false, -cabHeight / 2 + 4.2);
    cabinetGroup.add(nBar);

    // Front Smoked Acrylic Viewing Door with Hinges
    const doorGroup = new THREE.Group();
    doorGroup.position.set(-cabWidth / 2, 0, cabDepth / 2);
    doorMeshRef.current = doorGroup;

    const acrylicMat = new THREE.MeshPhysicalMaterial({
      color: 0x0369a1,
      transparent: true,
      opacity: 0.35,
      roughness: 0.08,
      metalness: 0.05,
      transmission: 0.8,
      ior: 1.52,
    });

    const doorMesh = new THREE.Mesh(new THREE.BoxGeometry(cabWidth, cabHeight, 0.4), acrylicMat);
    doorMesh.position.set(cabWidth / 2, 0, 0);
    doorGroup.add(doorMesh);

    const handleMat = new THREE.MeshStandardMaterial({ color: 0x0284c7, metalness: 0.9, roughness: 0.1 });
    const handle = new THREE.Mesh(new THREE.BoxGeometry(0.7, 3.8, 1.2), handleMat);
    handle.position.set(cabWidth - 1.8, 0, 0.7);
    doorGroup.add(handle);

    cabinetGroup.add(doorGroup);

    // 6. 3D PHYSICAL PBR HARDWARE COMPONENTS
    clickableMeshesRef.current = [];
    pilotLightSourcesRef.current = [];

    const effectiveComps = components && components.length > 0 ? components : [
      { id: 'iga', type: 'IGA', name: 'IGA General 25A Curva C', tag: 'IGA-1', x: 0, y: 0, w: 58, h: 100, terminals: [], ampacity: 25, poles: 2, curve: 'C' },
      { id: 'dps', type: 'DPS', name: 'DPS Sobretensión 20kA', tag: 'DPS-1', x: 0, y: 0, w: 32, h: 100, terminals: [] },
      { id: 'pilot', type: 'PILOT_LIGHTS', name: 'Pilotos Red', tag: 'PILOT-1', x: 0, y: 0, w: 32, h: 100, terminals: [] },
      { id: 'rcd1', type: 'RCD', name: 'Diferencial RCD 25A 30mA', tag: 'RCD-1', x: 0, y: 0, w: 58, h: 100, terminals: [], ampacity: 25, poles: 2 },
      { id: 'mcb1', type: 'MCB', name: 'C1 Alumbrado 10A Curva B', tag: 'C1', x: 0, y: 0, w: 30, h: 100, terminals: [], ampacity: 10, curve: 'B' },
      { id: 'mcb2', type: 'MCB', name: 'C2 Enchufes 16A Curva C', tag: 'C2', x: 0, y: 0, w: 30, h: 100, terminals: [], ampacity: 16, curve: 'C' },
      { id: 'mcb3', type: 'MCB', name: 'C3 Fuerza 20A Curva C', tag: 'C3', x: 0, y: 0, w: 30, h: 100, terminals: [], ampacity: 20, curve: 'C' },
    ];

    let currentX = -cabWidth / 2 + 4.0;
    const railY = 5.0;
    const zBase = -cabDepth / 2 + 2.5;

    // Component Terminal 3D Position Map for Real Wire Splines
    const terminal3DPosMap = new Map<string, THREE.Vector3>();

    effectiveComps.forEach((comp) => {
      const poles = comp.poles || (comp.type === 'IGA' ? (isThreePhase ? 4 : 2) : comp.type === 'RCD' ? 2 : comp.type === 'DPS' ? (isThreePhase ? 4 : 2) : 1);
      const modWidth = poles * 1.85;
      const totalHeight = 8.4;
      const rearDepth = 4.8;
      const noseDepth = 1.4;

      const compGroup = new THREE.Group();

      // Advanced PBR Material for Breaker Body (Thermoplastic / Technical Polymer)
      let bodyColor = 0xf1f5f9;
      if (comp.type === 'DPS') bodyColor = 0x0f172a;
      if (comp.type === 'PILOT_LIGHTS') bodyColor = 0x111827;

      const bodyMat = new THREE.MeshPhysicalMaterial({
        color: bodyColor,
        metalness: 0.08,
        roughness: 0.28,
        clearcoat: 0.3,
        clearcoatRoughness: 0.15,
      });

      // 1. Rear Chassis (Clips to DIN rail)
      const rearChassis = new THREE.Mesh(new THREE.BoxGeometry(modWidth, totalHeight, rearDepth), bodyMat);
      rearChassis.castShadow = true;
      rearChassis.receiveShadow = true;
      compGroup.add(rearChassis);

      // 2. Protruding Front Nose / 45mm Escutcheon Window
      const noseHeight = 4.7;
      const noseMesh = new THREE.Mesh(
        new THREE.BoxGeometry(modWidth - 0.08, noseHeight, noseDepth),
        bodyMat
      );
      noseMesh.position.set(0, 0, rearDepth / 2 + noseDepth / 2);
      noseMesh.castShadow = true;
      compGroup.add(noseMesh);

      // 3. Ultra-Crisp PBR Faceplate Texture
      const faceplateTexture = createComponentFaceplateTexture(
        comp.type,
        comp.tag || '',
        comp.name,
        comp.ampacity,
        comp.curve,
        isThreePhase,
        comp.isOverflow,
        isEnergized,
        comp.isOff,
        liveVolts
      );

      const labelMat = new THREE.MeshBasicMaterial({
        map: faceplateTexture,
        transparent: true,
      });
      const labelMesh = new THREE.Mesh(
        new THREE.PlaneGeometry(modWidth - 0.12, noseHeight - 0.1),
        labelMat
      );
      labelMesh.position.set(0, 0, rearDepth / 2 + noseDepth + 0.015);
      compGroup.add(labelMesh);

      // 4. Embornamiento / Terminal Screw Cavities with Real Metallic Screws (Top & Bottom)
      for (let p = 0; p < poles; p++) {
        const poleX = -modWidth / 2 + 0.925 + p * 1.85;

        // Top Terminal Cavity
        const topCavity = new THREE.Mesh(new THREE.CylinderGeometry(0.38, 0.38, 0.9, 16), new THREE.MeshStandardMaterial({ color: 0x1e293b }));
        topCavity.position.set(poleX, totalHeight / 2 - 0.65, rearDepth / 2 - 0.4);
        compGroup.add(topCavity);

        const topScrew = new THREE.Mesh(new THREE.CylinderGeometry(0.26, 0.26, 0.45, 12), screwMat);
        topScrew.position.set(poleX, totalHeight / 2 - 0.55, rearDepth / 2 - 0.4);
        compGroup.add(topScrew);

        // Bottom Terminal Cavity
        const botCavity = new THREE.Mesh(new THREE.CylinderGeometry(0.38, 0.38, 0.9, 16), new THREE.MeshStandardMaterial({ color: 0x1e293b }));
        botCavity.position.set(poleX, -totalHeight / 2 + 0.65, rearDepth / 2 - 0.4);
        compGroup.add(botCavity);

        const botScrew = new THREE.Mesh(new THREE.CylinderGeometry(0.26, 0.26, 0.45, 12), screwMat);
        botScrew.position.set(poleX, -totalHeight / 2 + 0.55, rearDepth / 2 - 0.4);
        compGroup.add(botScrew);
      }

      // 5. Toggle Levers with Mechanical Flag Indicator
      let leverMesh: THREE.Mesh | undefined;

      if (comp.type === 'MCB' || comp.type === 'IGA' || comp.type === 'RCD') {
        const leverGroup = new THREE.Group();
        leverGroup.position.set(0, 0.2, rearDepth / 2 + noseDepth);

        const isTripped = comp.isTripped;
        const isOff = comp.isOff;

        const toggleMat = new THREE.MeshPhysicalMaterial({
          color: isTripped ? 0xef4444 : isOff ? 0x334155 : 0x16a34a,
          metalness: 0.15,
          roughness: 0.3,
          clearcoat: 0.2,
        });

        leverMesh = new THREE.Mesh(new THREE.BoxGeometry(0.85 * poles, 1.55, 0.95), toggleMat);
        leverMesh.position.set(0, isTripped || isOff ? -0.42 : 0.42, 0.48);
        leverMesh.castShadow = true;
        leverGroup.add(leverMesh);

        // Mechanical Flag Status (Red "I" = Closed / Green "0" = Open)
        const flagMat = new THREE.MeshBasicMaterial({
          color: isTripped || isOff ? 0x22c55e : 0xef4444,
        });
        const flagMesh = new THREE.Mesh(new THREE.PlaneGeometry(0.65, 0.38), flagMat);
        flagMesh.position.set(0, -1.25, 0.05);
        leverGroup.add(flagMesh);

        compGroup.add(leverGroup);
      } else if (comp.type === 'PILOT_LIGHTS') {
        // High-Quality Glass Jeweled Pilot Indicator Domes with Emissive Lighting
        const colors = isThreePhase ? [0xef4444, 0x0284c7, 0xf59e0b] : [0xef4444, 0x0284c7];
        colors.forEach((c, idx) => {
          const jewelMat = new THREE.MeshPhysicalMaterial({
            color: isEnergized ? c : 0x334155,
            emissive: isEnergized ? c : 0x000000,
            emissiveIntensity: isEnergized ? 3.5 : 0,
            transmission: isEnergized ? 0.4 : 0.85,
            roughness: 0.05,
            metalness: 0.05,
            ior: 1.54,
          });
          const jewel = new THREE.Mesh(new THREE.SphereGeometry(0.42, 24, 24), jewelMat);
          const xOffset = -modWidth / 2 + 0.925 + idx * 1.35;
          jewel.position.set(xOffset, 0, rearDepth / 2 + noseDepth + 0.35);
          compGroup.add(jewel);

          // Real PointLight emitting onto surrounding hardware when energized!
          if (isEnergized) {
            const pilotLight = new THREE.PointLight(c, 2.4, 14, 2);
            pilotLight.position.set(xOffset, 0, rearDepth / 2 + noseDepth + 0.6);
            compGroup.add(pilotLight);
            pilotLightSourcesRef.current.push(pilotLight);
          }
        });
      }

      // Visual Overflow Red Glowing Frame in 3D
      if (comp.isOverflow) {
        const warnRingGeo = new THREE.BoxGeometry(modWidth + 0.7, totalHeight + 0.7, rearDepth + noseDepth + 0.8);
        const warnRingMat = new THREE.MeshBasicMaterial({
          color: 0xef4444,
          wireframe: true,
        });
        const warnRing = new THREE.Mesh(warnRingGeo, warnRingMat);
        warnRing.position.set(0, 0, (rearDepth + noseDepth) / 2);
        compGroup.add(warnRing);
      }

      const compWorldX = currentX + modWidth / 2;
      compGroup.position.set(compWorldX, railY, zBase);
      cabinetGroup.add(compGroup);

      // Register terminals in 3D world space
      comp.terminals?.forEach((term) => {
        const termX = compWorldX + (term.x / (comp.w || 50) - 0.5) * modWidth;
        const termY = term.position === 'top' ? railY + totalHeight / 2 - 0.6 : railY - totalHeight / 2 + 0.6;
        const termZ = zBase + rearDepth / 2 - 0.4;
        terminal3DPosMap.set(`${comp.id}_${term.id}`, new THREE.Vector3(termX, termY, termZ));
      });

      clickableMeshesRef.current.push({
        mesh: compGroup,
        comp: comp as InteractiveComponent,
        leverMesh,
      });

      currentX += modWidth + 0.45;
    });

    // 7. REAL 3D WIRES ROUTING (Splines from Terminals into Cable Ducts)
    if (show3DWires && wires && wires.length > 0) {
      const wireGroup = new THREE.Group();

      wires.forEach((w) => {
        const p1 = terminal3DPosMap.get(`${w.fromCompId}_${w.fromTermId}`);
        const p2 = terminal3DPosMap.get(`${w.toCompId}_${w.toTermId}`);

        if (p1 && p2) {
          // Generate realistic catenary / duct route spline
          const midY = (p1.y + p2.y) / 2 + (p1.y > 0 ? 2.5 : -2.5);
          const midZ = zBase + 2.8;
          const curve = new THREE.CatmullRomCurve3([
            p1,
            new THREE.Vector3(p1.x, midY, midZ),
            new THREE.Vector3(p2.x, midY, midZ),
            p2,
          ]);

          const wireMat = new THREE.MeshStandardMaterial({
            color: new THREE.Color(w.color || '#ef4444'),
            metalness: 0.1,
            roughness: 0.4,
          });

          const wireGeo = new THREE.TubeGeometry(curve, 24, 0.16, 8, false);
          const wireMesh = new THREE.Mesh(wireGeo, wireMat);
          wireMesh.castShadow = true;
          wireGroup.add(wireMesh);
        }
      });

      cabinetGroup.add(wireGroup);
    }

    // 8. SUBTLE IONIZED ENERGY PARTICLES (When Energized)
    if (isEnergized) {
      const particleCount = 70;
      const particleGeo = new THREE.BufferGeometry();
      const positions = new Float32Array(particleCount * 3);
      const colors = new Float32Array(particleCount * 3);

      for (let i = 0; i < particleCount; i++) {
        // Cluster near energized components and busbars
        positions[i * 3] = (Math.random() - 0.5) * (cabWidth - 8);
        positions[i * 3 + 1] = railY + (Math.random() - 0.5) * 8.0;
        positions[i * 3 + 2] = zBase + 2.5 + (Math.random() - 0.5) * 3.0;

        // Subtle glowing cyan and amber spark colors
        const isCyan = Math.random() > 0.4;
        colors[i * 3] = isCyan ? 0.2 : 0.95;
        colors[i * 3 + 1] = isCyan ? 0.75 : 0.8;
        colors[i * 3 + 2] = isCyan ? 0.98 : 0.2;
      }

      particleGeo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
      particleGeo.setAttribute('color', new THREE.BufferAttribute(colors, 3));

      const particleMat = new THREE.PointsMaterial({
        size: 0.35,
        vertexColors: true,
        transparent: true,
        opacity: 0.75,
        blending: THREE.AdditiveBlending,
      });

      const particleSystem = new THREE.Points(particleGeo, particleMat);
      cabinetGroup.add(particleSystem);
      particleSystemRef.current = particleSystem;
    }

    // 9. ANIMATION LOOP
    let animationFrameId: number;
    const clock = new THREE.Clock();

    const animate = () => {
      animationFrameId = requestAnimationFrame(animate);
      const elapsedTime = clock.getElapsedTime();

      // Smooth Door Transition
      if (doorMeshRef.current) {
        const targetAngle = doorOpen ? -Math.PI / 1.75 : 0;
        doorMeshRef.current.rotation.y = THREE.MathUtils.lerp(
          doorMeshRef.current.rotation.y,
          targetAngle,
          0.08
        );
      }

      // Gentle floating animation of energy particles
      if (particleSystemRef.current && isEnergized) {
        const positions = particleSystemRef.current.geometry.attributes.position.array as Float32Array;
        for (let i = 0; i < positions.length / 3; i++) {
          positions[i * 3 + 1] += Math.sin(elapsedTime * 3 + i) * 0.015;
          positions[i * 3] += Math.cos(elapsedTime * 2 + i) * 0.01;
        }
        particleSystemRef.current.geometry.attributes.position.needsUpdate = true;
      }

      renderer.render(scene, camera);
    };
    animate();

    // 10. INTUITIVE CAMERA CONTROLS: ORBIT (Left Click), PAN (Right/Middle Click), ZOOM (Wheel)
    const raycaster = new THREE.Raycaster();
    const mouse = new THREE.Vector2();

    const handleMouseDown = (e: MouseEvent) => {
      if (e.button === 0 && !e.shiftKey) {
        // Left Click: Orbit
        isOrbitingRef.current = true;
        isPanningRef.current = false;
      } else if (e.button === 2 || e.button === 1 || (e.button === 0 && e.shiftKey)) {
        // Right Click, Middle Click or Shift+Left Click: Pan
        isPanningRef.current = true;
        isOrbitingRef.current = false;
      }
      previousMousePosRef.current = { x: e.clientX, y: e.clientY };
    };

    const handleMouseMove = (e: MouseEvent) => {
      const deltaX = e.clientX - previousMousePosRef.current.x;
      const deltaY = e.clientY - previousMousePosRef.current.y;
      previousMousePosRef.current = { x: e.clientX, y: e.clientY };

      if (isOrbitingRef.current) {
        cameraSphericalRef.current.theta -= deltaX * 0.007;
        cameraSphericalRef.current.phi = Math.max(
          0.08,
          Math.min(Math.PI - 0.08, cameraSphericalRef.current.phi - deltaY * 0.007)
        );
        updateCameraTransform();
      } else if (isPanningRef.current) {
        // Pan Camera & Target along screen-space basis vectors
        const panSpeed = cameraSphericalRef.current.radius * 0.0018;
        const right = new THREE.Vector3();
        const up = new THREE.Vector3();

        camera.matrix.extractBasis(right, up, new THREE.Vector3());
        right.multiplyScalar(-deltaX * panSpeed);
        up.multiplyScalar(deltaY * panSpeed);

        cameraTargetRef.current.add(right).add(up);
        updateCameraTransform();
      }
    };

    const handleMouseUp = () => {
      isOrbitingRef.current = false;
      isPanningRef.current = false;
    };

    const handleWheel = (e: WheelEvent) => {
      e.preventDefault();
      cameraSphericalRef.current.radius = Math.max(
        12,
        Math.min(95, cameraSphericalRef.current.radius + e.deltaY * 0.035)
      );
      updateCameraTransform();
    };

    const handleContextMenu = (e: MouseEvent) => {
      e.preventDefault(); // Prevent default browser context menu for smooth right-click panning
    };

    const handleClick = (e: MouseEvent) => {
      // Breaker lever click toggle
      if (e.button !== 0) return;
      const rect = container.getBoundingClientRect();
      mouse.x = ((e.clientX - rect.left) / container.clientWidth) * 2 - 1;
      mouse.y = -((e.clientY - rect.top) / container.clientHeight) * 2 + 1;

      raycaster.setFromCamera(mouse, camera);

      const interactiveObjects = clickableMeshesRef.current.map(c => c.mesh);
      const intersects = raycaster.intersectObjects(interactiveObjects, true);

      if (intersects.length > 0) {
        let hitObj: THREE.Object3D | null = intersects[0].object;
        while (hitObj && hitObj.parent && hitObj.parent !== cabinetGroup) {
          hitObj = hitObj.parent;
        }

        const found = clickableMeshesRef.current.find(item => item.mesh === hitObj);
        if (found) {
          setSelectedComp(found.comp);
          if (onToggleBreaker) {
            onToggleBreaker(found.comp.id);
          }
        }
      }
    };

    const domElem = renderer.domElement;
    domElem.addEventListener('mousedown', handleMouseDown);
    domElem.addEventListener('mousemove', handleMouseMove);
    domElem.addEventListener('mouseup', handleMouseUp);
    domElem.addEventListener('wheel', handleWheel, { passive: false });
    domElem.addEventListener('contextmenu', handleContextMenu);
    domElem.addEventListener('click', handleClick);

    const handleResize = () => {
      if (!container || !rendererRef.current || !cameraRef.current) return;
      const w = container.clientWidth;
      const h = container.clientHeight;
      cameraRef.current.aspect = w / h;
      cameraRef.current.updateProjectionMatrix();
      rendererRef.current.setSize(w, h);
    };
    window.addEventListener('resize', handleResize);

    return () => {
      cancelAnimationFrame(animationFrameId);
      domElem.removeEventListener('mousedown', handleMouseDown);
      domElem.removeEventListener('mousemove', handleMouseMove);
      domElem.removeEventListener('mouseup', handleMouseUp);
      domElem.removeEventListener('wheel', handleWheel);
      domElem.removeEventListener('contextmenu', handleContextMenu);
      domElem.removeEventListener('click', handleClick);
      window.removeEventListener('resize', handleResize);
      renderer.dispose();
    };
  }, [components, wires, isThreePhase, doorOpen, showWireDucts, show3DWires, isEnergized, liveVolts]);

  // Handle Camera Presets with Terminal Inspection Focus
  const setCameraPreset = (preset: 'iso' | 'front' | 'top' | 'side' | 'bornes_top' | 'bornes_bot') => {
    setViewPreset(preset);
    if (preset === 'iso') {
      cameraTargetRef.current.set(0, 0, 0);
      cameraSphericalRef.current = { radius: 48, theta: Math.PI / 4, phi: Math.PI / 3 };
    } else if (preset === 'front') {
      cameraTargetRef.current.set(0, 0, 0);
      cameraSphericalRef.current = { radius: 42, theta: 0, phi: Math.PI / 2 };
    } else if (preset === 'top') {
      cameraTargetRef.current.set(0, 0, 0);
      cameraSphericalRef.current = { radius: 48, theta: 0, phi: 0.15 };
    } else if (preset === 'side') {
      cameraTargetRef.current.set(0, 0, 0);
      cameraSphericalRef.current = { radius: 46, theta: Math.PI / 2.2, phi: Math.PI / 2 };
    } else if (preset === 'bornes_top') {
      // Direct focus on top screw terminal cages
      cameraTargetRef.current.set(0, 8.5, 0);
      cameraSphericalRef.current = { radius: 26, theta: 0.1, phi: Math.PI / 3.2 };
    } else if (preset === 'bornes_bot') {
      // Direct focus on bottom load terminal cages
      cameraTargetRef.current.set(0, 1.5, 0);
      cameraSphericalRef.current = { radius: 26, theta: -0.1, phi: Math.PI / 1.7 };
    }

    if (cameraRef.current) {
      const { radius, theta, phi } = cameraSphericalRef.current;
      const target = cameraTargetRef.current;
      cameraRef.current.position.x = target.x + radius * Math.sin(phi) * Math.sin(theta);
      cameraRef.current.position.y = target.y + radius * Math.cos(phi);
      cameraRef.current.position.z = target.z + radius * Math.sin(phi) * Math.cos(theta);
      cameraRef.current.lookAt(target);
    }
  };

  // High-Resolution Screenshot Capture (PNG / JPEG)
  const handleTakeScreenshot = async (format: 'png' | 'jpeg' = 'png', copyToClipboard: boolean = false) => {
    if (!rendererRef.current || !sceneRef.current || !cameraRef.current) return;

    setIsCapturing(true);
    setShowCaptureMenu(false);
    setShutterFlash(true);
    setTimeout(() => setShutterFlash(false), 250);

    try {
      rendererRef.current.render(sceneRef.current, cameraRef.current);
      const mimeType = format === 'jpeg' ? 'image/jpeg' : 'image/png';
      const dataUrl = rendererRef.current.domElement.toDataURL(mimeType, format === 'jpeg' ? 0.95 : 1.0);

      try {
        localStorage.setItem('neovolt_last_3d_screenshot', dataUrl);
        localStorage.setItem('neovolt_last_3d_screenshot_timestamp', new Date().toISOString());
        window.dispatchEvent(new CustomEvent('neovolt_3d_screenshot_saved', {
          detail: { dataUrl, format, timestamp: new Date().toISOString() }
        }));
      } catch (e) {
        console.warn('Could not cache 3D screenshot to localStorage:', e);
      }

      if (onCaptureScreenshot) {
        onCaptureScreenshot(dataUrl);
      }

      if (copyToClipboard && navigator.clipboard && (window as any).ClipboardItem) {
        const res = await fetch(dataUrl);
        const blob = await res.blob();
        await navigator.clipboard.write([
          new (window as any).ClipboardItem({ [blob.type]: blob })
        ]);
        setCaptureFeedback('¡Copiado al portapapeles!');
      } else {
        const dateStr = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
        const fileName = `tablero-3d-pbr-sec-${dateStr}.${format === 'jpeg' ? 'jpg' : 'png'}`;
        const a = document.createElement('a');
        a.href = dataUrl;
        a.download = fileName;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        setCaptureFeedback(`Descargado como .${format === 'jpeg' ? 'jpg' : 'png'}`);
      }

      setTimeout(() => setCaptureFeedback(null), 3500);
    } catch (err) {
      console.error('Error capturing 3D screenshot:', err);
      setCaptureFeedback('Error al capturar imagen 3D');
      setTimeout(() => setCaptureFeedback(null), 3000);
    } finally {
      setIsCapturing(false);
    }
  };

  return (
    <div className="relative w-full h-[740px] bg-slate-950 rounded-2xl border border-slate-800 overflow-hidden shadow-2xl flex flex-col select-none">
      {/* Shutter Flash Animation */}
      {shutterFlash && (
        <div className="absolute inset-0 bg-white/45 z-50 pointer-events-none transition-opacity duration-200" />
      )}

      {/* Top Floating Controls Bar */}
      <div className="absolute top-3.5 left-3.5 right-3.5 z-20 flex flex-wrap items-center justify-between gap-2.5 pointer-events-none">
        {/* Left: 3D Info & Lighting Preset Badge */}
        <div className="pointer-events-auto bg-slate-900/95 backdrop-blur-md border border-slate-700/90 px-3.5 py-2 rounded-xl shadow-2xl flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400">
            <Box className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-black text-white">Gabinete 3D PBR Studio</span>
              <span className="text-[9px] font-extrabold uppercase px-1.5 py-0.2 rounded bg-cyan-950 text-cyan-300 border border-cyan-800">
                Materiales PBR
              </span>
            </div>
            <p className="text-[10px] text-slate-400">IEC 60898-1 • Iluminación Studio 3-Puntos • Bornes Metálicos</p>
          </div>
        </div>

        {/* Right: Camera Presets, Power Toggle, Ducts, Door & Screenshot Controls */}
        <div className="pointer-events-auto flex items-center gap-2 flex-wrap">
          {/* TABLERO APAGADO / ENERGIZADO MASTER TOGGLE */}
          <button
            onClick={handleToggleEnergized}
            className={`flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-black border transition-all shadow-xl active:scale-95 cursor-pointer ${
              isEnergized
                ? 'bg-emerald-500 hover:bg-emerald-400 text-slate-950 border-emerald-300 shadow-emerald-500/40 animate-pulse'
                : 'bg-slate-900/95 hover:bg-slate-800 text-slate-300 border-slate-700'
            }`}
            title="Alternar entre Tablero Energizado y Tablero Apagado"
          >
            <Zap className={`w-3.5 h-3.5 ${isEnergized ? 'fill-current text-slate-950' : 'text-emerald-400'}`} />
            <span>{isEnergized ? '⚡ Tablero Energizado (ON)' : '⭕ Tablero Apagado (OFF)'}</span>
          </button>

          {/* Camera View Presets */}
          <div className="bg-slate-900/95 backdrop-blur-md border border-slate-700/90 p-1 rounded-xl shadow-lg flex items-center gap-1">
            <button
              onClick={() => setCameraPreset('iso')}
              className={`px-2.5 py-1 rounded-lg text-[11px] font-bold transition-all ${
                viewPreset === 'iso' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Isométrica
            </button>
            <button
              onClick={() => setCameraPreset('front')}
              className={`px-2.5 py-1 rounded-lg text-[11px] font-bold transition-all ${
                viewPreset === 'front' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Frontal
            </button>
            <button
              onClick={() => setCameraPreset('bornes_top')}
              className={`px-2 py-1 rounded-lg text-[11px] font-bold transition-all ${
                viewPreset === 'bornes_top' ? 'bg-amber-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
              title="Inspeccionar bornes superiores de alimentación"
            >
              Bornes Sup.
            </button>
            <button
              onClick={() => setCameraPreset('bornes_bot')}
              className={`px-2 py-1 rounded-lg text-[11px] font-bold transition-all ${
                viewPreset === 'bornes_bot' ? 'bg-amber-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
              title="Inspeccionar bornes inferiores de carga"
            >
              Bornes Inf.
            </button>
          </div>

          {/* 3D Wires Toggle */}
          <button
            onClick={() => setShow3DWires(!show3DWires)}
            className={`flex items-center gap-1.5 px-2.5 py-2 rounded-xl text-xs font-bold border transition-all shadow-lg backdrop-blur-md ${
              show3DWires
                ? 'bg-slate-800 text-cyan-300 border-cyan-700'
                : 'bg-slate-900/90 text-slate-400 border-slate-700 hover:bg-slate-800'
            }`}
            title="Mostrar / Ocultar cables 3D en bornes"
          >
            <Radio className="w-3.5 h-3.5" />
            <span>Cables 3D</span>
          </button>

          {/* Door Toggle Button */}
          <button
            onClick={() => setDoorOpen(!doorOpen)}
            className={`flex items-center gap-1.5 px-2.5 py-2 rounded-xl text-xs font-bold border transition-all shadow-lg backdrop-blur-md ${
              doorOpen
                ? 'bg-emerald-950/80 text-emerald-300 border-emerald-700'
                : 'bg-slate-900/90 text-slate-300 border-slate-700 hover:bg-slate-800'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>{doorOpen ? 'Puerta Abierta' : 'Puerta Cerrada'}</span>
          </button>

          {/* 3D Screenshot Menu Button */}
          <div className="relative">
            <button
              onClick={() => setShowCaptureMenu(!showCaptureMenu)}
              disabled={isCapturing}
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-black bg-gradient-to-r from-cyan-600 to-indigo-600 hover:from-cyan-500 hover:to-indigo-500 text-white shadow-lg transition-all active:scale-95 disabled:opacity-50"
              title="Tomar captura en alta definición de la vista 3D actual"
            >
              {isCapturing ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <Camera className="w-3.5 h-3.5 text-cyan-200" />
              )}
              <span>Capturar 3D</span>
            </button>

            {showCaptureMenu && (
              <div className="absolute right-0 top-full mt-2 w-64 bg-slate-900/95 backdrop-blur-md border border-slate-700 rounded-xl p-2 shadow-2xl z-30 space-y-1 text-xs">
                <div className="text-[10px] text-slate-400 font-bold px-2 py-1 uppercase tracking-wider border-b border-slate-800">
                  Exportar Captura 3D
                </div>
                <button
                  onClick={() => handleTakeScreenshot('png')}
                  className="w-full text-left px-2.5 py-2 hover:bg-slate-800 rounded-lg text-slate-200 flex items-center justify-between transition-colors"
                >
                  <span className="flex items-center gap-2">
                    <Download className="w-3.5 h-3.5 text-cyan-400" />
                    <span>Descargar PNG (Alta Calidad)</span>
                  </span>
                  <span className="text-[10px] font-mono text-cyan-400 font-bold">.PNG</span>
                </button>
                <button
                  onClick={() => handleTakeScreenshot('jpeg')}
                  className="w-full text-left px-2.5 py-2 hover:bg-slate-800 rounded-lg text-slate-200 flex items-center justify-between transition-colors"
                >
                  <span className="flex items-center gap-2">
                    <ImageIcon className="w-3.5 h-3.5 text-indigo-400" />
                    <span>Descargar JPEG (Comprimido)</span>
                  </span>
                  <span className="text-[10px] font-mono text-indigo-400 font-bold">.JPG</span>
                </button>
                <button
                  onClick={() => handleTakeScreenshot('png', true)}
                  className="w-full text-left px-2.5 py-2 hover:bg-slate-800 rounded-lg text-slate-200 flex items-center justify-between transition-colors"
                >
                  <span className="flex items-center gap-2">
                    <Copy className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Copiar al Portapapeles</span>
                  </span>
                  <span className="text-[10px] font-mono text-emerald-400 font-bold">CLIP</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Capture Feedback Toast */}
      {captureFeedback && (
        <div className="absolute top-20 right-4 z-30 bg-emerald-950/90 border border-emerald-500/80 backdrop-blur-md px-3.5 py-2 rounded-xl text-xs text-emerald-200 font-bold shadow-2xl flex items-center gap-2 animate-fadeIn">
          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>{captureFeedback}</span>
        </div>
      )}

      {/* 3D WebGL Canvas Container */}
      <div ref={mountRef} className="w-full h-full cursor-grab active:cursor-grabbing" />

      {/* Bottom Floating Navigation Hint & Status Legend */}
      <div className="absolute bottom-3.5 left-3.5 right-3.5 z-20 flex flex-wrap items-center justify-between text-xs text-slate-400 pointer-events-none gap-2">
        {/* Navigation Hint Bar */}
        <div className="pointer-events-auto bg-slate-900/90 backdrop-blur-md border border-slate-800 px-3 py-1.5 rounded-xl flex items-center gap-3 text-[11px]">
          <span className="flex items-center gap-1 text-slate-300 font-bold">
            <Move className="w-3.5 h-3.5 text-cyan-400" />
            <span>Orbitar: <kbd className="bg-slate-800 px-1.5 py-0.5 rounded text-cyan-300 font-mono">Clic Izq</kbd></span>
          </span>
          <span className="text-slate-600">•</span>
          <span className="flex items-center gap-1 text-slate-300 font-bold">
            <Sliders className="w-3.5 h-3.5 text-amber-400" />
            <span>Pan / Desplazar: <kbd className="bg-slate-800 px-1.5 py-0.5 rounded text-amber-300 font-mono">Clic Der</kbd></span>
          </span>
          <span className="text-slate-600">•</span>
          <span className="flex items-center gap-1 text-slate-300 font-bold">
            <span>Zoom: <kbd className="bg-slate-800 px-1.5 py-0.5 rounded text-emerald-300 font-mono">Scroll</kbd></span>
          </span>
        </div>

        {/* State Indicators */}
        <div className="pointer-events-auto bg-slate-900/90 backdrop-blur-md border border-slate-800 px-3 py-1.5 rounded-xl flex items-center gap-4 text-[11px]">
          <span className="flex items-center gap-1.5">
            <span className={`w-2.5 h-2.5 rounded-full inline-block ${isEnergized ? 'bg-emerald-400 shadow-[0_0_8px_#34d399]' : 'bg-slate-600'}`} />
            <span className={isEnergized ? 'text-emerald-300 font-bold' : 'text-slate-400'}>
              {isEnergized ? `Energizado (${liveVolts.toFixed(1)}V)` : 'Desenergizado'}
            </span>
          </span>
          <span className="flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-amber-400 inline-block" />
            <span>Bornes IEC 60715</span>
          </span>
        </div>
      </div>
    </div>
  );
};

export const BoardSimulator3D = memo(BoardSimulator3DComponent);
export default BoardSimulator3D;
