import React, { useState, useMemo } from 'react';
import { RoomData, HighAppliance, AutoGeneratedCircuit, BoardProtectionSpecs, BudgetItem } from '../types';
import { ShieldAlert, Cpu, Sparkles, AlertTriangle, Layers, Zap, Info, CheckCircle2, Plus, Edit2, Trash2, RotateCcw, ShoppingCart, Check, FileSpreadsheet, ChevronRight } from 'lucide-react';

interface BoardAssemblerTabProps {
  rooms: RoomData[];
  highAppliances: HighAppliance[];
  feederLength: number;
  setFeederLength: (len: number) => void;
  isThreePhase: boolean;
  setIsThreePhase: (val: boolean) => void;
  feederWireSection: number;
  setFeederWireSection: (sec: number) => void;
  onImportMaterialsToQuote?: (items: BudgetItem[]) => void;
}

export const BoardAssemblerTab: React.FC<BoardAssemblerTabProps> = ({
  rooms,
  highAppliances,
  feederLength,
  setFeederLength,
  isThreePhase,
  setIsThreePhase,
  feederWireSection,
  setFeederWireSection,
  onImportMaterialsToQuote,
}) => {
  const [aiAdvice, setAiAdvice] = useState<string | null>(null);
  const [loadingAi, setLoadingAi] = useState(false);
  const [importSuccess, setImportSuccess] = useState(false);

  // Editable Circuits State (If null, uses autogenerated logic)
  const [customCircuits, setCustomCircuits] = useState<AutoGeneratedCircuit[] | null>(null);

  // Circuit Editing Modal State
  const [isEditingCircuitOpen, setIsEditingCircuitOpen] = useState(false);
  const [editingCircuitId, setEditingCircuitId] = useState<string | null>(null);
  const [cName, setCName] = useState('');
  const [cBreakerRating, setCBreakerRating] = useState('1x16A Curva C 6kA');
  const [cLoadWatts, setCLoadWatts] = useState<number>(1500);
  const [cWireSection, setCWireSection] = useState('2.5 mm² EVA Libre Halógenos');
  const [cConduitType, setCConduitType] = useState('Tubo PVC Conduit 25mm');
  const [cRcdGroup, CRcdGroup] = useState<number>(1);

  // 1. Calculate totals from Load Census
  const totalLights = rooms.reduce((sum, r) => sum + r.lightPoints, 0);
  const totalSockets = rooms.reduce((sum, r) => sum + r.socketPoints, 0);

  const roomDevicesPowerW = rooms.reduce((sum, r) => {
    return sum + r.devices.reduce((dSum, d) => dSum + d.powerWatts * d.quantity, 0);
  }, 0);

  const lightPowerW = totalLights * 100;
  const socketPowerW = totalSockets * 150;
  const highPowerW = highAppliances.reduce((sum, h) => sum + h.powerWatts, 0);

  const totalProjectPowerW = roomDevicesPowerW + lightPowerW + socketPowerW + highPowerW;

  // 2. Calculate Feeder Current & Voltage Drop (RIC N°03 & RIC N°04)
  const voltageNominal = isThreePhase ? 380 : 220;
  const cosPhi = 0.93;
  const rhoCopper = 0.018;

  let calculatedInAmps = 0;
  let voltageDropV = 0;

  if (isThreePhase) {
    calculatedInAmps = totalProjectPowerW / (1.732 * voltageNominal * cosPhi);
    voltageDropV = (1.732 * feederLength * calculatedInAmps * rhoCopper) / feederWireSection;
  } else {
    calculatedInAmps = totalProjectPowerW / (voltageNominal * cosPhi);
    voltageDropV = (2 * feederLength * calculatedInAmps * rhoCopper) / feederWireSection;
  }

  const voltageDropPercent = (voltageDropV / voltageNominal) * 100;

  // --- AUTOMATIC MINIMUM SECTION CALCULATOR ACCORDING TO RIC N°04 ---
  // Table of standard sections & Method B1 75°C EVA Cu ampacities
  const standardSectionsTable = [
    { section: 2.5, ampacity: 21 },
    { section: 4.0, ampacity: 28 },
    { section: 6.0, ampacity: 36 },
    { section: 10.0, ampacity: 50 },
    { section: 16.0, ampacity: 66 },
    { section: 25.0, ampacity: 89 },
    { section: 35.0, ampacity: 111 },
    { section: 50.0, ampacity: 134 },
    { section: 70.0, ampacity: 171 },
  ];

  const minRequiredSectionObj = standardSectionsTable.find((row) => {
    let testDropV = 0;
    if (isThreePhase) {
      testDropV = (1.732 * feederLength * calculatedInAmps * rhoCopper) / row.section;
    } else {
      testDropV = (2 * feederLength * calculatedInAmps * rhoCopper) / row.section;
    }
    const testDropPercent = (testDropV / voltageNominal) * 100;
    return testDropPercent <= 3.0 && row.ampacity >= calculatedInAmps;
  }) || standardSectionsTable[standardSectionsTable.length - 1];

  const minRequiredWireSection = minRequiredSectionObj.section;

  // 3. Compute Auto Generated Circuits
  let lightCircuitsCount = Math.ceil(totalLights / 12);
  if (lightCircuitsCount === 0 && totalLights > 0) lightCircuitsCount = 1;

  let socketCircuitsCount = Math.ceil(totalSockets / 10);
  if (socketCircuitsCount === 0 && totalSockets > 0) socketCircuitsCount = 1;

  const defaultGeneratedCircuits: AutoGeneratedCircuit[] = [];
  let circuitIndex = 1;

  // Light Circuits
  for (let i = 0; i < lightCircuitsCount; i++) {
    defaultGeneratedCircuits.push({
      id: `c_${circuitIndex}`,
      code: `C${circuitIndex}`,
      name: `Alumbrado General (Zona ${i + 1})`,
      type: 'alumbrado',
      loadWatts: Math.round(lightPowerW / (lightCircuitsCount || 1)),
      currentAmps: Math.round(((lightPowerW / (lightCircuitsCount || 1)) / 220) * 10) / 10,
      breakerRating: '1x10A Curva C 6kA',
      breakerAmps: 10,
      wireSection: '1.5 mm² EVA Libre Halógenos',
      conduitType: 'Tubo PVC Conduit 20mm',
      rcdAssignedGroup: 1,
      pointsCount: Math.ceil(totalLights / (lightCircuitsCount || 1)),
      status: 'active',
    });
    circuitIndex++;
  }

  // Socket Circuits
  for (let i = 0; i < socketCircuitsCount; i++) {
    defaultGeneratedCircuits.push({
      id: `c_${circuitIndex}`,
      code: `C${circuitIndex}`,
      name: `Enchufes Generales 10A (Zona ${i + 1})`,
      type: 'enchufes',
      loadWatts: Math.round((socketPowerW + roomDevicesPowerW) / (socketCircuitsCount || 1)),
      currentAmps: Math.round((((socketPowerW + roomDevicesPowerW) / (socketCircuitsCount || 1)) / 220) * 10) / 10,
      breakerRating: '1x16A Curva C 6kA',
      breakerAmps: 16,
      wireSection: '2.5 mm² EVA Libre Halógenos',
      conduitType: 'Tubo PVC Conduit 25mm',
      rcdAssignedGroup: 1,
      pointsCount: Math.ceil(totalSockets / (socketCircuitsCount || 1)),
      status: 'active',
    });
    circuitIndex++;
  }

  // Heavy Loads
  highAppliances.forEach((app) => {
    const appAmps = Math.round((app.powerWatts / 220) * 10) / 10;
    let bAmps = 16;
    let wire = '2.5 mm² EVA Libre Halógenos';
    let pipe = 'Tubo PVC Conduit 25mm';

    if (app.powerWatts > 5000) {
      bAmps = 32;
      wire = '6.0 mm² EVA Libre Halógenos';
      pipe = 'Tubo PVC Conduit 25mm / EMT 3/4"';
    } else if (app.powerWatts > 3000) {
      bAmps = 20;
      wire = '4.0 mm² EVA Libre Halógenos';
      pipe = 'Tubo PVC Conduit 25mm';
    }

    defaultGeneratedCircuits.push({
      id: `c_${circuitIndex}`,
      code: `C${circuitIndex}`,
      name: `Carga Dedicada - ${app.name}`,
      type: app.name.toLowerCase().includes('clima') ? 'clima' : 'fuerza_dedicada',
      loadWatts: app.powerWatts,
      currentAmps: appAmps,
      breakerRating: `1x${bAmps}A Curva C 6kA`,
      breakerAmps: bAmps,
      wireSection: wire,
      conduitType: pipe,
      rcdAssignedGroup: 1,
      status: 'active',
    });
    circuitIndex++;
  });

  if (defaultGeneratedCircuits.length === 0) {
    defaultGeneratedCircuits.push({
      id: 'c_1',
      code: 'C1',
      name: 'Circuito Mixto Básico',
      type: 'enchufes',
      loadWatts: 2000,
      currentAmps: 9.1,
      breakerRating: '1x16A Curva C 6kA',
      breakerAmps: 16,
      wireSection: '2.5 mm² EVA Libre Halógenos',
      conduitType: 'Tubo PVC Conduit 25mm',
      rcdAssignedGroup: 1,
      status: 'active',
    });
  }

  // Active Circuits in Use
  const activeCircuits = customCircuits !== null ? customCircuits : defaultGeneratedCircuits;

  // Assign RCD Groups (SEC RIC N°05: MAX 3 CIRCUITS PER RCD!)
  const totalCircuitsCount = activeCircuits.length;
  const requiredRcdCount = Math.max(1, Math.ceil(totalCircuitsCount / 3));

  const rcdList: BoardProtectionSpecs['rcdList'] = [];
  for (let r = 0; r < requiredRcdCount; r++) {
    const assignedCircuitCodes: string[] = [];
    const startIndex = r * 3;
    const endIndex = Math.min(startIndex + 3, totalCircuitsCount);

    for (let c = startIndex; c < endIndex; c++) {
      activeCircuits[c].rcdAssignedGroup = r + 1;
      assignedCircuitCodes.push(activeCircuits[c].code);
    }

    rcdList.push({
      id: r + 1,
      name: `Protector Diferencial RCD ${r + 1}`,
      rating: calculatedInAmps > 25 ? '2x40A 30mA Clase AC' : '2x25A 30mA Clase AC',
      circuitsAssigned: assignedCircuitCodes,
    });
  }

  // IGA Selection
  let igaAmps = 25;
  if (calculatedInAmps > 40) igaAmps = 50;
  else if (calculatedInAmps > 32) igaAmps = 40;
  else if (calculatedInAmps > 25) igaAmps = 32;
  else if (calculatedInAmps > 16) igaAmps = 25;
  else igaAmps = 16;

  const igaRating = isThreePhase ? `3x${igaAmps}A 6kA Curva C` : `1x${igaAmps}A 6kA Curva C`;
  const dpsRating = isThreePhase ? '3x Trifásico 400V 40kA (Tipo 2)' : '1x Monofásico 275V 20kA (Tipo 2)';

  // DIN Modules Calculation (RIC N°02: +25% Reserve)
  const igaModules = isThreePhase ? 3 : 2;
  const dpsModules = 2;
  const rcdModulesTotal = requiredRcdCount * 2;
  const circuitBreakerModulesTotal = totalCircuitsCount * 1;

  const activeModulesNeeded = igaModules + dpsModules + rcdModulesTotal + circuitBreakerModulesTotal;
  const reserveModulesNeeded = Math.ceil(activeModulesNeeded * 0.25);
  const totalModulesNeeded = activeModulesNeeded + reserveModulesNeeded;

  let recommendedEnclosureSize = 'Tablero DIN 12 Módulos';
  if (totalModulesNeeded > 36) recommendedEnclosureSize = 'Tablero DIN 48 Módulos (2 Filas de 24)';
  else if (totalModulesNeeded > 24) recommendedEnclosureSize = 'Tablero DIN 36 Módulos (2 Filas de 18)';
  else if (totalModulesNeeded > 18) recommendedEnclosureSize = 'Tablero DIN 24 Módulos (2 Filas de 12)';
  else if (totalModulesNeeded > 12) recommendedEnclosureSize = 'Tablero DIN 18 Módulos';

  // --- REAL-TIME RIC N°01 VALIDATION ENGINE ---
  const ric01Validation = useMemo(() => {
    const checks: Array<{
      id: string;
      normRef: string;
      title: string;
      passed: boolean;
      statusText: string;
      recommendation?: string;
    }> = [];

    // 1. Reserve Capacity (RIC N°01 Numeral 6.2.1.3 - 25% Reserve)
    const reservePercent = activeModulesNeeded > 0 ? (reserveModulesNeeded / activeModulesNeeded) * 100 : 0;
    const reservePassed = reservePercent >= 24.5;
    checks.push({
      id: 'reserve_25',
      normRef: 'RIC N°01 - Numeral 6.2.1.3',
      title: 'Espacio de Reserva de Módulos DIN (Mín. 25%)',
      passed: reservePassed,
      statusText: reservePassed
        ? `Reserva conforme: ${reserveModulesNeeded} módulos libres (${Math.round(reservePercent)}% del volumen ocupado)`
        : `Reserva insuficiente: ${reserveModulesNeeded} módulos (${Math.round(reservePercent)}%). La normativa exige mín. 25% libre.`,
      recommendation: reservePassed
        ? undefined
        : `Dimensiona una envolvente DIN superior (${recommendedEnclosureSize}) para asegurar la capacidad de expansión futura.`,
    });

    // 2. Maximum Circuits per RCD (RIC N°01 / RIC N°05 - Max 3 circuits per RCD 30mA)
    const circuitsPerRcd = activeCircuits.length / Math.max(1, requiredRcdCount);
    const rcdCountPassed = circuitsPerRcd <= 3.01;
    checks.push({
      id: 'circuits_per_rcd',
      normRef: 'RIC N°01 / RIC N°05',
      title: 'Límite Máximo de Circuitos por Interruptor Diferencial (Máx 3)',
      passed: rcdCountPassed,
      statusText: rcdCountPassed
        ? `Densidad RCD conforme: Promedio ${circuitsPerRcd.toFixed(1)} circuitos/RCD`
        : `Supera límite normativo: Se detectan ${activeCircuits.length} circuitos para ${requiredRcdCount} RCD(s). Máximo permitido: 3 circuitos por RCD.`,
      recommendation: rcdCountPassed
        ? undefined
        : `Aumenta los interruptores diferenciales RCD 30mA a al menos ${Math.ceil(activeCircuits.length / 3)} unidades.`,
    });

    // 3. Breaker vs Wire Coordination (In <= Iz)
    let wireCoordinationViolations = 0;
    const violationDetails: string[] = [];

    activeCircuits.forEach((c) => {
      const wireSec = parseFloat(c.wireSection) || 2.5;
      const breakerA = c.breakerAmps || 16;
      if (wireSec <= 1.5 && breakerA > 16) {
        wireCoordinationViolations++;
        violationDetails.push(`${c.code} (${c.name}): Conductor 1.5mm² con disyuntor ${breakerA}A > 16A`);
      } else if (wireSec <= 2.5 && breakerA > 20) {
        wireCoordinationViolations++;
        violationDetails.push(`${c.code} (${c.name}): Conductor 2.5mm² con disyuntor ${breakerA}A > 20A`);
      }
    });

    const wirePassed = wireCoordinationViolations === 0;
    checks.push({
      id: 'wire_coordination',
      normRef: 'RIC N°01 / RIC N°04',
      title: 'Coordinación Protección vs Capacidad Conductor (In ≤ Iz)',
      passed: wirePassed,
      statusText: wirePassed
        ? 'Todas las protecciones termomagnéticas coordinan correctamente con la capacidad de los conductores.'
        : `Se detectaron ${wireCoordinationViolations} inobservancias: ${violationDetails.join('; ')}`,
      recommendation: wirePassed
        ? undefined
        : 'Disminuye la capacidad nominal del disyuntor o aumenta la sección del conductor para prevenir sobrecalentamiento.',
    });

    // 4. IGA Capacity vs Project Power
    const totalProjectPowerAmps = calculatedInAmps;
    const igaAmpsVal = parseInt(igaRating) || 25;
    const igaPassed = igaAmpsVal >= totalProjectPowerAmps * 0.85;
    checks.push({
      id: 'iga_capacity',
      normRef: 'RIC N°01 - Numeral 6.1',
      title: 'Capacidad Nominal Interruptor General (IGA) vs Carga',
      passed: igaPassed,
      statusText: igaPassed
        ? `IGA conforme: ${igaAmpsVal}A para una demanda proyectada de ${totalProjectPowerAmps.toFixed(1)}A`
        : `Capacidad de IGA ajustada: Demandado ${totalProjectPowerAmps.toFixed(1)}A vs IGA ${igaAmpsVal}A`,
      recommendation: igaPassed
        ? undefined
        : 'Aumenta la capacidad nominal del IGA General o solicita un tramo mayor de empalme.',
    });

    const totalPassed = checks.filter((c) => c.passed).length;
    const isFullyCompliant = totalPassed === checks.length;

    return {
      checks,
      totalPassed,
      totalChecks: checks.length,
      isFullyCompliant,
    };
  }, [activeModulesNeeded, reserveModulesNeeded, activeCircuits, requiredRcdCount, calculatedInAmps, igaRating, recommendedEnclosureSize]);

  // --- EDITING & ADDING PROTECTIONS HANDLERS ---
  const handleAddNewCircuit = () => {
    const nextCodeNum = activeCircuits.length + 1;
    const newCto: AutoGeneratedCircuit = {
      id: `c_custom_${Date.now()}`,
      code: `C${nextCodeNum}`,
      name: 'Nuevo Circuito Adicional',
      type: 'enchufes',
      loadWatts: 1500,
      currentAmps: 6.8,
      breakerRating: '1x16A Curva C 6kA',
      breakerAmps: 16,
      wireSection: '2.5 mm² EVA Libre Halógenos',
      conduitType: 'Tubo PVC Conduit 25mm',
      rcdAssignedGroup: 1,
      status: 'active',
    };

    setCustomCircuits([...activeCircuits, newCto]);
  };

  const handleOpenEditCircuit = (cto: AutoGeneratedCircuit) => {
    setEditingCircuitId(cto.id);
    setCName(cto.name);
    setCBreakerRating(cto.breakerRating);
    setCLoadWatts(cto.loadWatts);
    setCWireSection(cto.wireSection);
    setCConduitType(cto.conduitType);
    CRcdGroup(cto.rcdAssignedGroup || 1);
    setIsEditingCircuitOpen(true);
  };

  const handleSaveCircuitEdit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingCircuitId) return;

    const updated = activeCircuits.map((cto) => {
      if (cto.id === editingCircuitId) {
        return {
          ...cto,
          name: cName,
          breakerRating: cBreakerRating,
          loadWatts: Number(cLoadWatts) || 0,
          currentAmps: Math.round(((Number(cLoadWatts) || 0) / 220) * 10) / 10,
          wireSection: cWireSection,
          conduitType: cConduitType,
          rcdAssignedGroup: cRcdGroup,
        };
      }
      return cto;
    });

    setCustomCircuits(updated);
    setIsEditingCircuitOpen(false);
  };

  const handleDeleteCircuit = (id: string) => {
    if (activeCircuits.length <= 1) {
      alert('El tablero debe conservar al menos 1 circuito.');
      return;
    }
    const filtered = activeCircuits.filter((c) => c.id !== id);
    // Renumber code sequentially
    const renumbered = filtered.map((c, idx) => ({
      ...c,
      code: `C${idx + 1}`,
    }));
    setCustomCircuits(renumbered);
  };

  const handleResetToAuto = () => {
    setCustomCircuits(null);
  };

  // --- AUTOMATIC MATERIALS LIST GENERATION (BILL OF MATERIALS) ---
  const generateProjectMaterialsBOM = (): BudgetItem[] => {
    const bom: BudgetItem[] = [];

    // 1. Enclosure
    let enclosurePrice = 24990;
    if (totalModulesNeeded > 36) enclosurePrice = 42990;
    else if (totalModulesNeeded > 24) enclosurePrice = 36990;
    else if (totalModulesNeeded > 18) enclosurePrice = 29990;
    else if (totalModulesNeeded > 12) enclosurePrice = 24990;
    else enclosurePrice = 18990;

    bom.push({
      id: 'bom_enc',
      name: `Gabinete Tablero Eléctrico ${recommendedEnclosureSize} IP40`,
      quantity: 1,
      price: enclosurePrice,
      category: 'PROTECCIONES Y TABLEROS',
      unit: 'unid',
      skuCode: 'SKU-119284',
    });

    // 2. IGA Breaker
    bom.push({
      id: 'bom_iga',
      name: `Interruptor General IGA Bticino ${igaRating}`,
      quantity: 1,
      price: isThreePhase ? 21990 : 7490,
      category: 'PROTECCIONES Y TABLEROS',
      unit: 'unid',
      skuCode: 'SKU-382914',
    });

    // 3. DPS Surge Protector
    bom.push({
      id: 'bom_dps',
      name: `Protector de Sobretensión DPS ${dpsRating}`,
      quantity: 1,
      price: 24990,
      category: 'PROTECCIONES Y TABLEROS',
      unit: 'unid',
      skuCode: 'SKU-591029',
    });

    // 4. Differential RCDs
    bom.push({
      id: 'bom_rcd',
      name: `Interruptor Diferencial Bticino 2x25A 30mA Clase AC`,
      quantity: requiredRcdCount,
      price: 19990,
      category: 'PROTECCIONES Y TABLEROS',
      unit: 'unid',
      skuCode: 'SKU-482101',
    });

    // 5. Individual Circuit Breakers
    activeCircuits.forEach((cto) => {
      let price = 5990;
      if (cto.breakerRating.includes('32A')) price = 7490;
      else if (cto.breakerRating.includes('20A') || cto.breakerRating.includes('25A')) price = 6490;

      bom.push({
        id: `bom_brk_${cto.id}`,
        name: `Disyuntor Bticino ${cto.breakerRating} (${cto.name})`,
        quantity: 1,
        price,
        category: 'PROTECCIONES Y TABLEROS',
        unit: 'unid',
        skuCode: 'SKU-382911',
      });
    });

    // 6. Cables (Estimated meters)
    const totalLightCircuits = activeCircuits.filter((c) => c.type === 'alumbrado').length;
    const totalSocketCircuits = activeCircuits.filter((c) => c.type === 'enchufes' || c.type === 'fuerza_dedicada').length;

    const meters15 = Math.max(30, totalLightCircuits * 40);
    const meters25 = Math.max(45, totalSocketCircuits * 50);

    bom.push({
      id: 'bom_cable_15_b',
      name: 'Cable EVA 1.5mm² Blanco Libre Halógenos',
      quantity: meters15,
      price: 450,
      category: 'CONDUCTORES EVA',
      unit: 'metro',
      skuCode: 'SKU-210193',
    });

    bom.push({
      id: 'bom_cable_15_a',
      name: 'Cable EVA 1.5mm² Azul Libre Halógenos',
      quantity: meters15,
      price: 450,
      category: 'CONDUCTORES EVA',
      unit: 'metro',
      skuCode: 'SKU-210192',
    });

    bom.push({
      id: 'bom_cable_25_b',
      name: 'Cable EVA 2.5mm² Blanco Libre Halógenos',
      quantity: meters25,
      price: 690,
      category: 'CONDUCTORES EVA',
      unit: 'metro',
      skuCode: 'SKU-210196',
    });

    bom.push({
      id: 'bom_cable_25_a',
      name: 'Cable EVA 2.5mm² Azul Libre Halógenos',
      quantity: meters25,
      price: 690,
      category: 'CONDUCTORES EVA',
      unit: 'metro',
      skuCode: 'SKU-210195',
    });

    bom.push({
      id: 'bom_cable_25_v',
      name: 'Cable EVA 2.5mm² Verde Tierra PE',
      quantity: Math.round(meters25 * 0.8),
      price: 690,
      category: 'CONDUCTORES EVA',
      unit: 'metro',
      skuCode: 'SKU-210197',
    });

    // 7. Feeder Cable
    bom.push({
      id: 'bom_feeder_cable',
      name: `Cable EVA ${feederWireSection}mm² Alimentador Principal`,
      quantity: Math.round(feederLength * 3),
      price: feederWireSection >= 6 ? 1850 : 1150,
      category: 'CONDUCTORES EVA',
      unit: 'metro',
      skuCode: 'SKU-210199',
    });

    // 8. Conduit PVC & Boxes
    const conduitStrips = Math.max(10, Math.ceil((meters15 + meters25) / 10));
    bom.push({
      id: 'bom_pvc_25',
      name: 'Tubo PVC Conduit 25mm x 3m (Gris)',
      quantity: conduitStrips,
      price: 2490,
      category: 'CANALIZACIÓN Y TUBERÍAS',
      unit: 'tira',
      skuCode: 'SKU-881925',
    });

    bom.push({
      id: 'bom_cajas_chuqui',
      name: 'Caja Chuqui PVC Embutida Bticino',
      quantity: Math.max(8, totalSockets + totalLights),
      price: 890,
      category: 'CANALIZACIÓN Y TUBERÍAS',
      unit: 'unid',
      skuCode: 'SKU-881940',
    });

    // 9. Grounding system
    bom.push({
      id: 'bom_ground_rod',
      name: 'Barra Cooperweld Puesta a Tierra 5/8" x 1.5m',
      quantity: 1,
      price: 14990,
      category: 'PUESTA A TIERRA',
      unit: 'unid',
      skuCode: 'SKU-982103',
    });

    bom.push({
      id: 'bom_ground_pit',
      name: 'Cámara Registro Puesta a Tierra PVC Con Tapa',
      quantity: 1,
      price: 4990,
      category: 'PUESTA A TIERRA',
      unit: 'unid',
      skuCode: 'SKU-982104',
    });

    // 10. Mounting supplies pack
    bom.push({
      id: 'bom_supplies_pack',
      name: 'Pack Accesorios de Montaje (Cinta 3M, Ferrules, Marrett, Amarras)',
      quantity: 1,
      price: 12900,
      category: 'INSUMOS MONTAJE',
      unit: 'pack',
      skuCode: 'SKU-310022',
    });

    return bom;
  };

  const generatedBOM = generateProjectMaterialsBOM();
  const bomTotalCLP = generatedBOM.reduce((sum, item) => sum + item.quantity * item.price, 0);

  const handleAttachBOMToQuote = () => {
    if (onImportMaterialsToQuote) {
      onImportMaterialsToQuote(generatedBOM);
      setImportSuccess(true);
      setTimeout(() => setImportSuccess(false), 3000);
    }
  };

  // AI Advisor Request
  const handleConsultAiAdvisor = async () => {
    setLoadingAi(true);
    try {
      const res = await fetch('/api/board-advisor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          rooms,
          highAppliances,
          feederLength,
          isThreePhase,
        }),
      });
      const data = await res.json();
      setAiAdvice(data.advice || 'Evaluación SEC realizada exitosamente.');
    } catch (err) {
      setAiAdvice('Sugerencia SEC: Recuerde que el RIC N°05 exige un máximo estricto de 3 circuitos asociados a cada Interruptor Diferencial de 30mA.');
    } finally {
      setLoadingAi(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-fuchsia-400 text-xs font-bold uppercase tracking-wider mb-1">
            <Cpu className="w-4 h-4" />
            <span>Etapa 2 • Armador Normado de Tableros Eléctricos TDA Editables</span>
          </div>
          <h2 className="text-xl font-bold text-white">Dimensionamiento y Edición Personalizada de Protecciones</h2>
          <p className="text-xs text-slate-400 mt-1">
            Agrega, modifica o quita protecciones, calcula reserva del 25% (RIC N°02) y autogenera el listado completo de materiales de obra.
          </p>
        </div>

        <button
          onClick={handleConsultAiAdvisor}
          disabled={loadingAi}
          className="flex items-center gap-2 bg-gradient-to-r from-fuchsia-600 to-indigo-600 hover:from-fuchsia-500 hover:to-indigo-500 text-white text-xs font-bold px-4 py-2.5 rounded-xl shadow-lg transition-all"
        >
          <Sparkles className="w-4 h-4" />
          <span>{loadingAi ? 'Analizando con IA SEC...' : 'Auditar Tablero con IA'}</span>
        </button>
      </div>

      {/* AI Advisory Callout */}
      {aiAdvice && (
        <div className="bg-fuchsia-950/40 border border-fuchsia-500/30 p-4 rounded-xl text-xs text-fuchsia-200 space-y-1 animate-fadeIn">
          <div className="font-bold flex items-center gap-2 text-fuchsia-300">
            <Sparkles className="w-4 h-4" />
            <span>Dictamen Técnico Eléctrico IA (SEC Chile):</span>
          </div>
          <p className="leading-relaxed whitespace-pre-line text-slate-300">{aiAdvice}</p>
        </div>
      )}

      {/* PANEL VALIDADOR EN TIEMPO REAL NORMATIVA RIC N°01 */}
      <div className={`p-5 rounded-2xl border shadow-xl space-y-4 transition-all ${ric01Validation.isFullyCompliant ? 'bg-emerald-950/20 border-emerald-500/40' : 'bg-amber-950/20 border-amber-500/40'}`}>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2.5">
            <ShieldAlert className={`w-5 h-5 ${ric01Validation.isFullyCompliant ? 'text-emerald-400' : 'text-amber-400'}`} />
            <div>
              <h3 className="text-sm font-extrabold text-white flex items-center gap-2">
                <span>Validador en Tiempo Real RIC N°01 SEC</span>
                <span className="text-[11px] font-mono text-slate-400 font-normal">(Dimensionamiento de Tableros)</span>
              </h3>
              <p className="text-xs text-slate-400">Verificación continua de módulos DIN, reserva del 25% y coordinación de protecciones.</p>
            </div>
          </div>

          <div className={`px-3 py-1 rounded-full border text-xs font-bold font-mono flex items-center gap-1.5 shrink-0 ${ric01Validation.isFullyCompliant ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30' : 'bg-amber-500/10 text-amber-400 border-amber-500/30'}`}>
            {ric01Validation.isFullyCompliant ? (
              <>
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span>CUMPLE 100% NORMATIVA RIC N°01</span>
              </>
            ) : (
              <>
                <AlertTriangle className="w-3.5 h-3.5" />
                <span>{ric01Validation.totalPassed}/{ric01Validation.totalChecks} CRITERIOS APROBADOS</span>
              </>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {ric01Validation.checks.map((chk) => (
            <div
              key={chk.id}
              className={`p-3 rounded-xl border text-xs space-y-1 ${chk.passed ? 'bg-slate-950/80 border-slate-800' : 'bg-amber-950/30 border-amber-500/30'}`}
            >
              <div className="flex items-center justify-between">
                <span className="font-bold text-white">{chk.title}</span>
                <span className={`text-[10px] font-mono font-extrabold px-2 py-0.5 rounded ${chk.passed ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 'bg-amber-500/10 text-amber-400 border border-amber-500/20'}`}>
                  {chk.passed ? '✓ NORMATIVO' : '⚠️ OBSERVADO'}
                </span>
              </div>

              <div className="text-[10px] text-slate-400 font-mono">{chk.normRef}</div>
              <p className="text-slate-300 leading-relaxed text-[11px]">{chk.statusText}</p>

              {chk.recommendation && (
                <div className="text-amber-300 text-[11px] bg-amber-500/10 p-2 rounded-lg border border-amber-500/20 font-medium flex items-start gap-1.5 mt-1">
                  <Info className="w-3.5 h-3.5 shrink-0 mt-0.5 text-amber-400" />
                  <span>{chk.recommendation}</span>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* 1. Cálculo de Alimentador Principal (RIC N°03) */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4 shadow-md">
        <h3 className="text-sm font-bold text-slate-200 flex items-center gap-2">
          <Zap className="w-4 h-4 text-emerald-400" />
          1. Cálculo de Alimentador Principal y Caída de Tensión (RIC N°03)
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1">Tipo Suministro</label>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => setIsThreePhase(false)}
                className={`flex-1 py-1.5 px-2 rounded-lg text-xs font-semibold border ${
                  !isThreePhase
                    ? 'bg-fuchsia-600 border-fuchsia-500 text-white'
                    : 'bg-slate-800 border-slate-700 text-slate-400'
                }`}
              >
                Monofásico 220V
              </button>
              <button
                type="button"
                onClick={() => setIsThreePhase(true)}
                className={`flex-1 py-1.5 px-2 rounded-lg text-xs font-semibold border ${
                  isThreePhase
                    ? 'bg-fuchsia-600 border-fuchsia-500 text-white'
                    : 'bg-slate-800 border-slate-700 text-slate-400'
                }`}
              >
                Trifásico 380V
              </button>
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1">Largo Alimentador (m)</label>
            <input
              type="number"
              value={feederLength}
              onChange={(e) => setFeederLength(Number(e.target.value) || 1)}
              className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-white focus:outline-none focus:border-fuchsia-500 font-bold"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1">Sección Conductor EVA</label>
            <select
              value={feederWireSection}
              onChange={(e) => setFeederWireSection(Number(e.target.value))}
              className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-white focus:outline-none focus:border-fuchsia-500 font-bold"
            >
              <option value={2.5}>2.5 mm² Cu EVA (21A)</option>
              <option value={4.0}>4.0 mm² Cu EVA (28A)</option>
              <option value={6.0}>6.0 mm² Cu EVA (36A)</option>
              <option value={10.0}>10.0 mm² Cu EVA (50A)</option>
              <option value={16.0}>16.0 mm² Cu EVA (66A)</option>
              <option value={25.0}>25.0 mm² Cu EVA (89A)</option>
              <option value={35.0}>35.0 mm² Cu EVA (111A)</option>
              <option value={50.0}>50.0 mm² Cu EVA (134A)</option>
              <option value={70.0}>70.0 mm² Cu EVA (171A)</option>
            </select>
          </div>

          <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 flex flex-col justify-center">
            <div className="text-[10px] text-slate-400">Caída de Tensión Alimentador:</div>
            <div
              className={`text-sm font-extrabold flex items-center gap-1.5 ${
                voltageDropPercent > 3.0 ? 'text-rose-400' : 'text-emerald-400'
              }`}
            >
              <span>
                {voltageDropV.toFixed(2)}V ({voltageDropPercent.toFixed(2)}%)
              </span>
              {voltageDropPercent > 3.0 ? (
                <AlertTriangle className="w-4 h-4 text-rose-400" />
              ) : (
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              )}
            </div>
            <div className="text-[10px] text-slate-500">Máx permitido RIC N°04: 3.0%</div>
          </div>
        </div>

        {/* RIC N°04 Minimum Section Auto-Calculator Callout */}
        <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div className="space-y-1">
            <div className="text-xs font-bold text-white flex items-center gap-2">
              <Zap className="w-4 h-4 text-amber-400" />
              <span>Calculadora de Sección Mínima (Norma SEC RIC N°04):</span>
            </div>
            <p className="text-[11px] text-slate-400">
              Para corriente proyectada de <strong className="text-amber-300">{calculatedInAmps.toFixed(1)}A</strong> a <strong className="text-amber-300">{feederLength}m</strong> de distancia, la sección mínima normada es <strong className="text-emerald-400">{minRequiredWireSection} mm² Cu EVA</strong>.
            </p>
            {voltageDropPercent > 3.0 && (
              <div className="mt-2 bg-rose-950/40 border border-rose-800/60 p-2 rounded-lg text-rose-400 text-[10px] font-bold flex items-center gap-1.5">
                <AlertTriangle className="w-3.5 h-3.5 shrink-0" />
                <span>¡ADVERTENCIA SEC! La caída de tensión actual ({voltageDropPercent.toFixed(2)}%) excede el máximo normativo permitido (3.0%).</span>
              </div>
            )}
          </div>

          <button
            type="button"
            onClick={() => setFeederWireSection(minRequiredWireSection)}
            disabled={feederWireSection === minRequiredWireSection}
            className={`px-3.5 py-2 rounded-xl text-xs font-extrabold transition-all flex items-center gap-1.5 shrink-0 ${
              feederWireSection === minRequiredWireSection
                ? 'bg-emerald-950/60 text-emerald-300 border border-emerald-800/60 cursor-default'
                : 'bg-gradient-to-r from-amber-500 to-fuchsia-600 hover:from-amber-400 hover:to-fuchsia-500 text-white shadow-lg shadow-amber-500/20'
            }`}
          >
            {feederWireSection === minRequiredWireSection ? (
              <>
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                <span>Sección Mínima Aplicada ({minRequiredWireSection} mm²)</span>
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                <span>Aplicar Sección RIC N°04 ({minRequiredWireSection} mm²)</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* 2. Cuadro de Protecciones Cabecera y RCDs */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4 shadow-md">
        <h3 className="text-sm font-bold text-slate-200 flex items-center gap-2">
          <Layers className="w-4 h-4 text-fuchsia-400" />
          2. Esquema de Protecciones de Cabecera (RIC N°02 & N°05)
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 space-y-1">
            <span className="text-[10px] uppercase tracking-wider text-slate-400 font-bold block">
              Interruptor General (IGA)
            </span>
            <div className="text-base font-black text-white">{igaRating}</div>
            <p className="text-[10px] text-slate-400">
              Corriente de diseño estimada: <strong className="text-emerald-400">{calculatedInAmps.toFixed(1)} A</strong>
            </p>
          </div>

          <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 space-y-1">
            <span className="text-[10px] uppercase tracking-wider text-slate-400 font-bold block">
              Protección Sobretensión (DPS)
            </span>
            <div className="text-base font-black text-amber-400">{dpsRating}</div>
            <p className="text-[10px] text-slate-400">Protección contra transitorios atmosféricos/red</p>
          </div>

          <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 space-y-1">
            <span className="text-[10px] uppercase tracking-wider text-slate-400 font-bold block">
              Protectores Diferenciales (RCD)
            </span>
            <div className="text-base font-black text-fuchsia-400">
              {requiredRcdCount} x Diferencial(es) 30mA
            </div>
            <p className="text-[10px] text-slate-400">
              Cumpliendo límite normativo SEC: <strong className="text-white">Máx 3 circuitos/RCD</strong>
            </p>
          </div>
        </div>

        {/* Grouping List */}
        <div className="space-y-2 pt-2">
          <div className="text-xs font-bold text-slate-300">Agrupación Normada de Circuitos por Diferencial:</div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
            {rcdList.map((rcd) => (
              <div
                key={rcd.id}
                className="bg-slate-800/80 border border-slate-700/80 p-3 rounded-xl text-xs space-y-2"
              >
                <div className="flex items-center justify-between border-b border-slate-700 pb-1.5">
                  <span className="font-bold text-fuchsia-300">{rcd.name}</span>
                  <span className="text-[10px] bg-fuchsia-500/20 text-fuchsia-300 font-bold px-1.5 py-0.5 rounded">
                    {rcd.rating}
                  </span>
                </div>
                <div className="text-[11px] text-slate-300">
                  Circuitos Asignados ({rcd.circuitsAssigned.length}/3):
                </div>
                <div className="flex flex-wrap gap-1">
                  {rcd.circuitsAssigned.map((code) => (
                    <span
                      key={code}
                      className="bg-slate-900 text-emerald-400 font-mono font-bold px-2 py-0.5 rounded text-[10px] border border-slate-700"
                    >
                      {code}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 3. Cuadro de Circuitos Generados Editables TDA */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4 shadow-md">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div>
            <h3 className="text-sm font-bold text-slate-200">
              3. Cuadro de Circuitos y Protecciones del Tablero TDA (Editable)
            </h3>
            <p className="text-xs text-slate-400 mt-0.5">
              Puedes agregar nuevos circuitos, modificar amperajes/calibres o eliminar protecciones según requerimientos de obra.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleAddNewCircuit}
              className="flex items-center gap-1.5 bg-fuchsia-600 hover:bg-fuchsia-500 text-white font-bold text-xs px-3 py-1.5 rounded-xl shadow transition-all"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>+ Agregar Proteccion</span>
            </button>

            {customCircuits !== null && (
              <button
                onClick={handleResetToAuto}
                className="flex items-center gap-1 bg-slate-800 hover:bg-slate-700 text-slate-300 font-semibold text-xs px-2.5 py-1.5 rounded-xl border border-slate-700 transition-all"
                title="Restablecer a Cálculo Automático SEC"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                <span>Restablecer</span>
              </button>
            )}
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="bg-slate-950 text-slate-400 border-b border-slate-800 text-[11px] uppercase">
                <th className="p-3">Cto</th>
                <th className="p-3">Destino / Función</th>
                <th className="p-3">Carga (W)</th>
                <th className="p-3">Corriente</th>
                <th className="p-3">Disyuntor SEC</th>
                <th className="p-3">Conductor EVA</th>
                <th className="p-3">Canalización</th>
                <th className="p-3">RCD No.</th>
                <th className="p-3 text-right">Acciones</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 font-medium">
              {activeCircuits.map((cto) => (
                <tr key={cto.id} className="hover:bg-slate-800/40 transition-colors">
                  <td className="p-3 font-mono font-bold text-emerald-400">{cto.code}</td>
                  <td className="p-3 text-white font-semibold">{cto.name}</td>
                  <td className="p-3 text-slate-300">{cto.loadWatts} W</td>
                  <td className="p-3 text-slate-300">{cto.currentAmps} A</td>
                  <td className="p-3">
                    <span className="bg-slate-800 border border-slate-700 text-slate-200 px-2 py-0.5 rounded font-mono text-[10px]">
                      {cto.breakerRating}
                    </span>
                  </td>
                  <td className="p-3 text-slate-300">{cto.wireSection}</td>
                  <td className="p-3 text-slate-400">{cto.conduitType}</td>
                  <td className="p-3">
                    <span className="bg-fuchsia-500/10 text-fuchsia-300 font-bold px-2 py-0.5 rounded text-[10px] border border-fuchsia-500/20">
                      RCD #{cto.rcdAssignedGroup || 1}
                    </span>
                  </td>
                  <td className="p-3 text-right">
                    <div className="flex items-center justify-end gap-1">
                      <button
                        onClick={() => handleOpenEditCircuit(cto)}
                        className="p-1.5 bg-slate-800 hover:bg-fuchsia-600 text-slate-300 hover:text-white rounded-lg border border-slate-700 transition-colors"
                        title="Editar Protección"
                      >
                        <Edit2 className="w-3 h-3" />
                      </button>
                      <button
                        onClick={() => handleDeleteCircuit(cto.id)}
                        className="p-1.5 bg-slate-800 hover:bg-rose-600 text-slate-300 hover:text-white rounded-lg border border-slate-700 transition-colors"
                        title="Quitar Protección"
                      >
                        <Trash2 className="w-3 h-3" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* 4. AUTOGENERATED BILL OF MATERIALS FOR THE WORK (LISTADO DE MATERIALES POR OBRA) */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4 shadow-md">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div>
            <div className="flex items-center gap-2 text-emerald-400 text-xs font-bold uppercase tracking-wider mb-0.5">
              <FileSpreadsheet className="w-4 h-4" />
              <span>Cálculo Autogenerado de Insumos • Precios Referenciales Mercado Chile</span>
            </div>
            <h3 className="text-sm font-bold text-white">Listado Completo de Materiales Necesarios para la Obra</h3>
            <p className="text-xs text-slate-400 mt-0.5">
              Cubación automática de gabinete, protecciones, cables EVA, canalizaciones conduit, tierra de protección e insumos.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <div className="text-right">
              <div className="text-[10px] text-slate-400 uppercase font-semibold">Total Estimado Materiales</div>
              <div className="text-lg font-black text-emerald-400">
                ${bomTotalCLP.toLocaleString('es-CL')} <span className="text-xs font-normal text-slate-400">CLP</span>
              </div>
            </div>

            <button
              onClick={handleAttachBOMToQuote}
              className="flex items-center gap-2 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-extrabold text-xs px-4 py-2.5 rounded-xl shadow-lg transition-all active:scale-95"
            >
              <ShoppingCart className="w-4 h-4" />
              <span>Adjuntar a Cotización Comercial</span>
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>

        {importSuccess && (
          <div className="bg-emerald-500/10 border border-emerald-500/30 p-3 rounded-xl flex items-center gap-2 text-emerald-300 text-xs font-semibold animate-fadeIn">
            <Check className="w-4 h-4 text-emerald-400" />
            <span>¡Listado de materiales adjuntado e importado con éxito a la pestaña de Cotización!</span>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {generatedBOM.map((mat) => (
            <div
              key={mat.id}
              className="bg-slate-950 border border-slate-800/80 p-3 rounded-xl text-xs flex flex-col justify-between gap-2"
            >
              <div>
                <div className="font-bold text-white leading-tight">{mat.name}</div>
                <div className="text-[10px] text-slate-500 mt-1 flex items-center justify-between">
                  <span>Cant: <strong className="text-fuchsia-400 font-mono text-xs">{mat.quantity} {mat.unit || 'unid'}</strong></span>
                  <span className="font-mono text-slate-400">{mat.skuCode || 'SKU-SEC'}</span>
                </div>
              </div>

              <div className="flex items-center justify-between pt-2 border-t border-slate-900 text-slate-300">
                <span className="text-[10px] text-slate-400">P.U: ${mat.price.toLocaleString('es-CL')}</span>
                <span className="font-extrabold text-emerald-400 text-xs">
                  ${(mat.quantity * mat.price).toLocaleString('es-CL')} CLP
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 5. Dimensionamiento del Gabinete DIN y Reserva Obligatoria (RIC N°02) */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4 shadow-md">
        <h3 className="text-sm font-bold text-slate-200 flex items-center justify-between">
          <span>5. Dimensionamiento del Gabinete DIN y Reserva Obligatoria (RIC N°02)</span>
          <span className="text-xs bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 px-2.5 py-1 rounded-lg font-bold">
            {recommendedEnclosureSize}
          </span>
        </h3>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center">
          <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
            <div className="text-xs text-slate-400">Módulos En Uso</div>
            <div className="text-xl font-extrabold text-white mt-1">{activeModulesNeeded} M</div>
          </div>

          <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
            <div className="text-xs text-amber-400 font-semibold">+ 25% Reserva SEC</div>
            <div className="text-xl font-extrabold text-amber-400 mt-1">{reserveModulesNeeded} M</div>
          </div>

          <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
            <div className="text-xs text-slate-400">Total Necesario</div>
            <div className="text-xl font-extrabold text-fuchsia-400 mt-1">{totalModulesNeeded} M</div>
          </div>

          <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
            <div className="text-xs text-slate-400">Gabinete Sugerido</div>
            <div className="text-xs font-bold text-emerald-400 mt-2">{recommendedEnclosureSize}</div>
          </div>
        </div>
      </div>

      {/* CIRCUIT EDITING MODAL */}
      {isEditingCircuitOpen && (
        <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-md w-full p-6 shadow-2xl space-y-4 animate-fadeIn">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <h3 className="text-sm font-bold text-white flex items-center gap-2">
                <Edit2 className="w-4 h-4 text-fuchsia-400" />
                <span>Editar Configuración de Protección / Circuito</span>
              </h3>
            </div>

            <form onSubmit={handleSaveCircuitEdit} className="space-y-3 text-xs">
              <div>
                <label className="block text-slate-400 mb-1 font-semibold">Destino / Nombre del Circuito:</label>
                <input
                  type="text"
                  value={cName}
                  onChange={(e) => setCName(e.target.value)}
                  required
                  className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-fuchsia-500 font-semibold"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-slate-400 mb-1 font-semibold">Capacidad Disyuntor:</label>
                  <select
                    value={cBreakerRating}
                    onChange={(e) => setCBreakerRating(e.target.value)}
                    className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white font-bold focus:outline-none focus:border-fuchsia-500"
                  >
                    <option value="1x10A Curva C 6kA">1x10A Curva C 6kA</option>
                    <option value="1x16A Curva C 6kA">1x16A Curva C 6kA</option>
                    <option value="1x20A Curva C 6kA">1x20A Curva C 6kA</option>
                    <option value="1x25A Curva C 6kA">1x25A Curva C 6kA</option>
                    <option value="1x32A Curva C 6kA">1x32A Curva C 6kA</option>
                    <option value="3x25A Curva C 6kA">3x25A Curva C 6kA (Trifásico)</option>
                    <option value="3x32A Curva C 6kA">3x32A Curva C 6kA (Trifásico)</option>
                  </select>
                </div>

                <div>
                  <label className="block text-slate-400 mb-1 font-semibold">Carga Instalada (Watts):</label>
                  <input
                    type="number"
                    value={cLoadWatts}
                    onChange={(e) => setCLoadWatts(Number(e.target.value))}
                    required
                    className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-emerald-400 font-bold focus:outline-none focus:border-fuchsia-500"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-slate-400 mb-1 font-semibold">Conductor EVA:</label>
                  <select
                    value={cWireSection}
                    onChange={(e) => setCWireSection(e.target.value)}
                    className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-fuchsia-500"
                  >
                    <option value="1.5 mm² EVA Libre Halógenos">1.5 mm² EVA</option>
                    <option value="2.5 mm² EVA Libre Halógenos">2.5 mm² EVA</option>
                    <option value="4.0 mm² EVA Libre Halógenos">4.0 mm² EVA</option>
                    <option value="6.0 mm² EVA Libre Halógenos">6.0 mm² EVA</option>
                  </select>
                </div>

                <div>
                  <label className="block text-slate-400 mb-1 font-semibold">Grupo RCD Asignado:</label>
                  <select
                    value={cRcdGroup}
                    onChange={(e) => CRcdGroup(Number(e.target.value))}
                    className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white font-bold focus:outline-none focus:border-fuchsia-500"
                  >
                    <option value={1}>Diferencial RCD #1</option>
                    <option value={2}>Diferencial RCD #2</option>
                    <option value={3}>Diferencial RCD #3</option>
                    <option value={4}>Diferencial RCD #4</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-slate-400 mb-1 font-semibold">Canalización:</label>
                <input
                  type="text"
                  value={cConduitType}
                  onChange={(e) => setCConduitType(e.target.value)}
                  className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-fuchsia-500"
                />
              </div>

              <div className="flex gap-2 pt-2">
                <button
                  type="submit"
                  className="flex-1 bg-fuchsia-600 hover:bg-fuchsia-500 text-white font-bold py-2.5 rounded-xl shadow transition-all"
                >
                  Guardar Cambios
                </button>
                <button
                  type="button"
                  onClick={() => setIsEditingCircuitOpen(false)}
                  className="bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold px-4 py-2.5 rounded-xl"
                >
                  Cancelar
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
