import React, { useEffect, useRef, useState, useMemo, memo } from 'react';
import * as THREE from 'three';
import {
  RotateCcw,
  Maximize2,
  ZoomIn,
  ZoomOut,
  Eye,
  EyeOff,
  Layers,
  Sparkles,
  Info,
  ShieldCheck,
  Zap,
  Box,
  Compass,
  Flame,
  CheckCircle2,
  Camera,
  Download,
  Image as ImageIcon,
  Check,
  Loader2,
  Copy
} from 'lucide-react';
import { InteractiveComponent } from './PhysicalBoardSimulationTab';
import { AutoGeneratedCircuit } from '../types';

export interface BoardSimulator3DProps {
  components: InteractiveComponent[];
  circuits?: AutoGeneratedCircuit[];
  isThreePhase?: boolean;
  onToggleBreaker?: (compId: string) => void;
  onCaptureScreenshot?: (dataUrl: string) => void;
}

export const BoardSimulator3DComponent: React.FC<BoardSimulator3DProps> = ({
  components,
  circuits = [],
  isThreePhase = false,
  onToggleBreaker,
  onCaptureScreenshot,
}) => {
  const mountRef = useRef<HTMLDivElement | null>(null);
  const [selectedComp, setSelectedComp] = useState<InteractiveComponent | null>(null);
  const [doorOpen, setDoorOpen] = useState(true);
  const [showWireDucts, setShowWireDucts] = useState(true);
  const [thermalView, setThermalView] = useState(false);
  const [viewPreset, setViewPreset] = useState<'iso' | 'front' | 'top' | 'side'>('iso');

  // Screenshot capture states
  const [showCaptureMenu, setShowCaptureMenu] = useState(false);
  const [isCapturing, setIsCapturing] = useState(false);
  const [captureFeedback, setCaptureFeedback] = useState<string | null>(null);
  const [shutterFlash, setShutterFlash] = useState(false);

  // Animation and scene refs
  const sceneRef = useRef<THREE.Scene | null>(null);
  const rendererRef = useRef<THREE.WebGLRenderer | null>(null);
  const cameraRef = useRef<THREE.PerspectiveCamera | null>(null);
  const doorMeshRef = useRef<THREE.Group | null>(null);
  const clickableMeshesRef = useRef<Array<{ mesh: THREE.Mesh; comp: InteractiveComponent }>>([]);

  // Mouse orbit state
  const isDraggingRef = useRef(false);
  const previousMousePosition = useRef({ x: 0, y: 0 });
  const cameraRotationRef = useRef({ theta: Math.PI / 4, phi: Math.PI / 3, radius: 48 });

  // Initialize Three.js Scene
  useEffect(() => {
    const container = mountRef.current;
    if (!container) return;

    const width = container.clientWidth || 800;
    const height = container.clientHeight || 550;

    // 1. Scene & Background
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x070b14);
    scene.fog = new THREE.FogExp2(0x070b14, 0.015);
    sceneRef.current = scene;

    // 2. Camera
    const camera = new THREE.PerspectiveCamera(45, width / height, 0.1, 1000);
    cameraRef.current = camera;

    const updateCameraPos = () => {
      const { theta, phi, radius } = cameraRotationRef.current;
      camera.position.x = radius * Math.sin(phi) * Math.sin(theta);
      camera.position.y = radius * Math.cos(phi);
      camera.position.z = radius * Math.sin(phi) * Math.cos(theta);
      camera.lookAt(0, 0, 0);
    };
    updateCameraPos();

    // 3. Renderer with preserveDrawingBuffer enabled for high-res screenshots
    const renderer = new THREE.WebGLRenderer({
      antialias: true,
      alpha: false,
      powerPreference: 'high-performance',
      preserveDrawingBuffer: true,
    });
    renderer.setSize(width, height);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    rendererRef.current = renderer;

    container.replaceChildren(renderer.domElement);

    // 4. Lighting
    const ambientLight = new THREE.AmbientLight(0xffffff, 0.7);
    scene.add(ambientLight);

    const dirLight1 = new THREE.DirectionalLight(0x00e5ff, 1.2);
    dirLight1.position.set(20, 40, 30);
    dirLight1.castShadow = true;
    dirLight1.shadow.mapSize.width = 1024;
    dirLight1.shadow.mapSize.height = 1024;
    scene.add(dirLight1);

    const dirLight2 = new THREE.DirectionalLight(0xe83d84, 0.6);
    dirLight2.position.set(-25, 20, 20);
    scene.add(dirLight2);

    const topWhiteLight = new THREE.DirectionalLight(0xffffff, 0.8);
    topWhiteLight.position.set(0, 30, 10);
    scene.add(topWhiteLight);

    // 5. Build 3D Cabinet Structure
    const cabinetGroup = new THREE.Group();
    scene.add(cabinetGroup);

    // Cabinet Enclosure Body (Metallic Dark Grey)
    const cabWidth = 36;
    const cabHeight = 28;
    const cabDepth = 10;

    const backPlateMat = new THREE.MeshStandardMaterial({
      color: 0x0f172a,
      metalness: 0.6,
      roughness: 0.4,
    });

    // Backplate
    const backPlate = new THREE.Mesh(new THREE.BoxGeometry(cabWidth - 1, cabHeight - 1, 0.6), backPlateMat);
    backPlate.position.set(0, 0, -cabDepth / 2 + 0.3);
    backPlate.receiveShadow = true;
    cabinetGroup.add(backPlate);

    // Outer Enclosure Frame (Top, Bottom, Left, Right)
    const frameMat = new THREE.MeshStandardMaterial({
      color: 0x334155,
      metalness: 0.9,
      roughness: 0.2,
    });

    const topWall = new THREE.Mesh(new THREE.BoxGeometry(cabWidth, 0.8, cabDepth), frameMat);
    topWall.position.set(0, cabHeight / 2, 0);
    cabinetGroup.add(topWall);

    const bottomWall = new THREE.Mesh(new THREE.BoxGeometry(cabWidth, 0.8, cabDepth), frameMat);
    bottomWall.position.set(0, -cabHeight / 2, 0);
    cabinetGroup.add(bottomWall);

    const leftWall = new THREE.Mesh(new THREE.BoxGeometry(0.8, cabHeight, cabDepth), frameMat);
    leftWall.position.set(-cabWidth / 2, 0, 0);
    cabinetGroup.add(leftWall);

    const rightWall = new THREE.Mesh(new THREE.BoxGeometry(0.8, cabHeight, cabDepth), frameMat);
    rightWall.position.set(cabWidth / 2, 0, 0);
    cabinetGroup.add(rightWall);

    // DIN 35mm Metallic Rails (Top & Bottom Rieles DIN)
    const railMat = new THREE.MeshStandardMaterial({
      color: 0xd4d4d8,
      metalness: 0.95,
      roughness: 0.15,
    });

    const dinRail1 = new THREE.Mesh(new THREE.BoxGeometry(cabWidth - 4, 1.2, 0.4), railMat);
    dinRail1.position.set(0, 4.5, -cabDepth / 2 + 1.2);
    cabinetGroup.add(dinRail1);

    const dinRail2 = new THREE.Mesh(new THREE.BoxGeometry(cabWidth - 4, 1.2, 0.4), railMat);
    dinRail2.position.set(0, -5.5, -cabDepth / 2 + 1.2);
    cabinetGroup.add(dinRail2);

    // Earth (PE) and Neutral (N) Brass Terminal Bars
    const brassMat = new THREE.MeshStandardMaterial({
      color: 0xca8a04,
      metalness: 0.9,
      roughness: 0.2,
    });

    const peBar = new THREE.Mesh(new THREE.BoxGeometry(16, 0.8, 0.8), brassMat);
    peBar.position.set(0, cabHeight / 2 - 2, -cabDepth / 2 + 1.2);
    cabinetGroup.add(peBar);

    const nBar = new THREE.Mesh(new THREE.BoxGeometry(16, 0.8, 0.8), brassMat);
    nBar.position.set(0, -cabHeight / 2 + 2, -cabDepth / 2 + 1.2);
    cabinetGroup.add(nBar);

    // Front Smoked Acrylic Door with Hinge
    const doorGroup = new THREE.Group();
    doorGroup.position.set(-cabWidth / 2, 0, cabDepth / 2);
    doorMeshRef.current = doorGroup;

    const acrylicMat = new THREE.MeshPhysicalMaterial({
      color: 0x0284c7,
      transparent: true,
      opacity: 0.35,
      roughness: 0.1,
      metalness: 0.1,
      transmission: 0.7,
      ior: 1.5,
    });

    const doorMesh = new THREE.Mesh(new THREE.BoxGeometry(cabWidth, cabHeight, 0.4), acrylicMat);
    doorMesh.position.set(cabWidth / 2, 0, 0);
    doorGroup.add(doorMesh);

    // Door Handle
    const handleMat = new THREE.MeshStandardMaterial({ color: 0x00e5ff, metalness: 0.9, roughness: 0.1 });
    const handle = new THREE.Mesh(new THREE.BoxGeometry(0.6, 3, 1), handleMat);
    handle.position.set(cabWidth - 1.5, 0, 0.6);
    doorGroup.add(handle);

    cabinetGroup.add(doorGroup);

    // 6. Build 3D DIN Modular Breakers & Devices
    clickableMeshesRef.current = [];

    const effectiveComps = components && components.length > 0 ? components : [
      { id: 'iga', type: 'IGA', name: 'IGA General 25A 2P Curva C', x: 0, y: 0, w: 58, h: 100, terminals: [], ampacity: 25, poles: 2, curve: 'C' },
      { id: 'dps', type: 'DPS', name: 'DPS Sobretensión 20kA', x: 0, y: 0, w: 32, h: 100, terminals: [] },
      { id: 'rcd1', type: 'RCD', name: 'Diferencial RCD 25A 30mA', x: 0, y: 0, w: 58, h: 100, terminals: [], ampacity: 25, poles: 2 },
      { id: 'mcb1', type: 'MCB', name: 'C1 Alumbrado 10A Curva B', x: 0, y: 0, w: 30, h: 100, terminals: [], ampacity: 10, curve: 'B' },
      { id: 'mcb2', type: 'MCB', name: 'C2 Enchufes 16A Curva C', x: 0, y: 0, w: 30, h: 100, terminals: [], ampacity: 16, curve: 'C' },
      { id: 'mcb3', type: 'MCB', name: 'C3 Cocina 16A Curva C', x: 0, y: 0, w: 30, h: 100, terminals: [], ampacity: 16, curve: 'C' },
      { id: 'mcb4', type: 'MCB', name: 'C4 Clima 16A Curva C', x: 0, y: 0, w: 30, h: 100, terminals: [], ampacity: 16, curve: 'C' },
    ];

    let currentX = -cabWidth / 2 + 3.5;
    const railY = 4.5;
    const zPos = -cabDepth / 2 + 2.4;

    effectiveComps.forEach((comp) => {
      const poles = comp.poles || (comp.type === 'IGA' ? (isThreePhase ? 4 : 2) : comp.type === 'RCD' ? 2 : 1);
      const modWidth = poles * 1.8;
      const modHeight = 7.5;
      const modDepth = 5.0;

      // Base Body Material
      let bodyColor = 0xf1f5f9; // Standard Light Grey
      if (comp.type === 'DPS') bodyColor = 0x0284c7; // DPS Blue
      if (comp.type === 'RCD') bodyColor = 0xe2e8f0; // RCD Light

      const compMat = new THREE.MeshStandardMaterial({
        color: bodyColor,
        metalness: 0.2,
        roughness: 0.4,
      });

      const compMesh = new THREE.Mesh(
        new THREE.BoxGeometry(modWidth, modHeight, modDepth),
        compMat
      );
      compMesh.position.set(currentX + modWidth / 2, railY, zPos);
      compMesh.castShadow = true;
      compMesh.receiveShadow = true;
      cabinetGroup.add(compMesh);

      // Breaker Front Panel Notch & Lever
      const toggleMat = new THREE.MeshStandardMaterial({
        color: comp.powerStatus === 'OFF' ? 0xef4444 : 0x10b981,
        metalness: 0.5,
        roughness: 0.2,
      });
      const leverMesh = new THREE.Mesh(new THREE.BoxGeometry(0.8 * poles, 1.4, 1.2), toggleMat);
      leverMesh.position.set(0, 0.4, modDepth / 2 + 0.4);
      compMesh.add(leverMesh);

      // Mark clickable
      clickableMeshesRef.current.push({ mesh: compMesh, comp: comp as InteractiveComponent });

      currentX += modWidth + 0.4;
    });

    // 7. Render Loop
    let animationFrameId: number;
    const animate = () => {
      animationFrameId = requestAnimationFrame(animate);

      // Animate Door Opening / Closing
      if (doorMeshRef.current) {
        const targetAngle = doorOpen ? -Math.PI / 1.7 : 0;
        doorMeshRef.current.rotation.y = THREE.MathUtils.lerp(
          doorMeshRef.current.rotation.y,
          targetAngle,
          0.08
        );
      }

      renderer.render(scene, camera);
    };
    animate();

    // 8. Event Listeners for Orbit Dragging
    const handleMouseDown = (e: MouseEvent) => {
      if (e.button === 0) {
        isDraggingRef.current = true;
        previousMousePosition.current = { x: e.clientX, y: e.clientY };
      }
    };

    const handleMouseMove = (e: MouseEvent) => {
      if (!isDraggingRef.current) return;
      const deltaX = e.clientX - previousMousePosition.current.x;
      const deltaY = e.clientY - previousMousePosition.current.y;

      cameraRotationRef.current.theta -= deltaX * 0.008;
      cameraRotationRef.current.phi = Math.max(
        0.1,
        Math.min(Math.PI - 0.1, cameraRotationRef.current.phi - deltaY * 0.008)
      );

      previousMousePosition.current = { x: e.clientX, y: e.clientY };
      updateCameraPos();
    };

    const handleMouseUp = () => {
      isDraggingRef.current = false;
    };

    const handleWheel = (e: WheelEvent) => {
      e.preventDefault();
      cameraRotationRef.current.radius = Math.max(
        15,
        Math.min(90, cameraRotationRef.current.radius + e.deltaY * 0.04)
      );
      updateCameraPos();
    };

    const domElem = renderer.domElement;
    domElem.addEventListener('mousedown', handleMouseDown);
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
    domElem.addEventListener('wheel', handleWheel, { passive: false });

    // Handle Window Resize
    const handleResize = () => {
      if (!container || !rendererRef.current || !cameraRef.current) return;
      const w = container.clientWidth;
      const h = container.clientHeight;
      cameraRef.current.aspect = w / h;
      cameraRef.current.updateProjectionMatrix();
      rendererRef.current.setSize(w, h);
    };
    window.addEventListener('resize', handleResize);

    return () => {
      cancelAnimationFrame(animationFrameId);
      domElem.removeEventListener('mousedown', handleMouseDown);
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
      domElem.removeEventListener('wheel', handleWheel);
      window.removeEventListener('resize', handleResize);
      renderer.dispose();
    };
  }, [components, isThreePhase, doorOpen]);

  // Handle Camera Presets
  const setCameraPreset = (preset: 'iso' | 'front' | 'top' | 'side') => {
    setViewPreset(preset);
    if (preset === 'iso') {
      cameraRotationRef.current = { theta: Math.PI / 4, phi: Math.PI / 3, radius: 48 };
    } else if (preset === 'front') {
      cameraRotationRef.current = { theta: 0, phi: Math.PI / 2, radius: 42 };
    } else if (preset === 'top') {
      cameraRotationRef.current = { theta: 0, phi: 0.15, radius: 48 };
    } else if (preset === 'side') {
      cameraRotationRef.current = { theta: Math.PI / 2.2, phi: Math.PI / 2, radius: 46 };
    }

    if (cameraRef.current) {
      const { theta, phi, radius } = cameraRotationRef.current;
      cameraRef.current.position.x = radius * Math.sin(phi) * Math.sin(theta);
      cameraRef.current.position.y = radius * Math.cos(phi);
      cameraRef.current.position.z = radius * Math.sin(phi) * Math.cos(theta);
      cameraRef.current.lookAt(0, 0, 0);
    }
  };

  // Capture High-Res 3D Screenshot (PNG or JPEG)
  const handleTakeScreenshot = async (format: 'png' | 'jpeg' = 'png', copyToClipboard: boolean = false) => {
    if (!rendererRef.current || !sceneRef.current || !cameraRef.current) return;

    setIsCapturing(true);
    setShowCaptureMenu(false);
    setShutterFlash(true);
    setTimeout(() => setShutterFlash(false), 250);

    try {
      // Ensure current frame is freshly rendered before export
      rendererRef.current.render(sceneRef.current, cameraRef.current);
      const mimeType = format === 'jpeg' ? 'image/jpeg' : 'image/png';
      const dataUrl = rendererRef.current.domElement.toDataURL(mimeType, format === 'jpeg' ? 0.95 : 1.0);

      // Save in LocalStorage & Dispatch event so work reports and project galleries can use it
      try {
        localStorage.setItem('neovolt_last_3d_screenshot', dataUrl);
        localStorage.setItem('neovolt_last_3d_screenshot_timestamp', new Date().toISOString());
        window.dispatchEvent(new CustomEvent('neovolt_3d_screenshot_saved', {
          detail: { dataUrl, format, timestamp: new Date().toISOString() }
        }));
      } catch (e) {
        console.warn('Could not cache 3D screenshot to localStorage:', e);
      }

      if (onCaptureScreenshot) {
        onCaptureScreenshot(dataUrl);
      }

      if (copyToClipboard && navigator.clipboard && (window as any).ClipboardItem) {
        // Copy to clipboard
        const res = await fetch(dataUrl);
        const blob = await res.blob();
        await navigator.clipboard.write([
          new (window as any).ClipboardItem({ [blob.type]: blob })
        ]);
        setCaptureFeedback('¡Copiado al portapapeles!');
      } else {
        // Download file
        const dateStr = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
        const fileName = `simulacion-tablero-3d-sec-${dateStr}.${format === 'jpeg' ? 'jpg' : 'png'}`;
        const a = document.createElement('a');
        a.href = dataUrl;
        a.download = fileName;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        setCaptureFeedback(`Descargado como .${format === 'jpeg' ? 'jpg' : 'png'}`);
      }

      setTimeout(() => setCaptureFeedback(null), 3500);
    } catch (err) {
      console.error('Error capturing 3D screenshot:', err);
      setCaptureFeedback('Error al capturar imagen 3D');
      setTimeout(() => setCaptureFeedback(null), 3000);
    } finally {
      setIsCapturing(false);
    }
  };

  return (
    <div className="relative w-full h-[740px] bg-slate-950 rounded-2xl border border-slate-800 overflow-hidden shadow-2xl flex flex-col select-none">
      {/* Shutter Flash Animation */}
      {shutterFlash && (
        <div className="absolute inset-0 bg-white/40 z-50 pointer-events-none transition-opacity duration-200" />
      )}

      {/* Top Floating Controls Bar */}
      <div className="absolute top-4 left-4 right-4 z-20 flex flex-wrap items-center justify-between gap-3 pointer-events-none">
        {/* Left: 3D Info Badge */}
        <div className="pointer-events-auto bg-slate-900/90 backdrop-blur-md border border-slate-700/80 px-3.5 py-2 rounded-xl shadow-lg flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400">
            <Box className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold text-white">Gabinete 3D Interactivo</span>
              <span className="text-[10px] font-extrabold uppercase px-1.5 py-0.2 rounded bg-cyan-950 text-cyan-300 border border-cyan-800">
                WebGL
              </span>
            </div>
            <p className="text-[11px] text-slate-400">Arrastra para rotar • Rueda para zoom</p>
          </div>
        </div>

        {/* Right: Camera Presets, Door Toggle & Screenshot Controls */}
        <div className="pointer-events-auto flex items-center gap-2 flex-wrap">
          {/* Preset Buttons */}
          <div className="bg-slate-900/90 backdrop-blur-md border border-slate-700/80 p-1 rounded-xl shadow-lg flex items-center gap-1">
            <button
              onClick={() => setCameraPreset('iso')}
              className={`px-2.5 py-1.5 rounded-lg text-xs font-bold transition-all ${
                viewPreset === 'iso' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              3D Isométrica
            </button>
            <button
              onClick={() => setCameraPreset('front')}
              className={`px-2.5 py-1.5 rounded-lg text-xs font-bold transition-all ${
                viewPreset === 'front' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Frontal
            </button>
            <button
              onClick={() => setCameraPreset('top')}
              className={`px-2.5 py-1.5 rounded-lg text-xs font-bold transition-all ${
                viewPreset === 'top' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Superior
            </button>
            <button
              onClick={() => setCameraPreset('side')}
              className={`px-2.5 py-1.5 rounded-lg text-xs font-bold transition-all ${
                viewPreset === 'side' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Lateral
            </button>
          </div>

          {/* Door Toggle Button */}
          <button
            onClick={() => setDoorOpen(!doorOpen)}
            className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold border transition-all shadow-lg backdrop-blur-md ${
              doorOpen
                ? 'bg-emerald-950/80 text-emerald-300 border-emerald-700'
                : 'bg-slate-900/90 text-slate-300 border-slate-700 hover:bg-slate-800'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>{doorOpen ? 'Puerta Abierta' : 'Puerta Cerrada'}</span>
          </button>

          {/* 3D Screenshot Menu Button */}
          <div className="relative">
            <button
              onClick={() => setShowCaptureMenu(!showCaptureMenu)}
              disabled={isCapturing}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold bg-gradient-to-r from-cyan-600 to-indigo-600 hover:from-cyan-500 hover:to-indigo-500 text-white shadow-lg transition-all active:scale-95 disabled:opacity-50"
              title="Tomar captura en alta definición de la configuración 3D actual"
            >
              {isCapturing ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <Camera className="w-3.5 h-3.5 text-cyan-200" />
              )}
              <span>Capturar 3D</span>
            </button>

            {showCaptureMenu && (
              <div className="absolute right-0 top-full mt-2 w-64 bg-slate-900/95 backdrop-blur-md border border-slate-700 rounded-xl p-2 shadow-2xl z-30 space-y-1 text-xs">
                <div className="text-[10px] text-slate-400 font-bold px-2 py-1 uppercase tracking-wider border-b border-slate-800">
                  Exportar Captura 3D
                </div>
                <button
                  onClick={() => handleTakeScreenshot('png')}
                  className="w-full text-left px-2.5 py-2 hover:bg-slate-800 rounded-lg text-slate-200 flex items-center justify-between transition-colors"
                >
                  <span className="flex items-center gap-2">
                    <Download className="w-3.5 h-3.5 text-cyan-400" />
                    <span>Descargar PNG (Alta Calidad)</span>
                  </span>
                  <span className="text-[10px] font-mono text-cyan-400 font-bold">.PNG</span>
                </button>
                <button
                  onClick={() => handleTakeScreenshot('jpeg')}
                  className="w-full text-left px-2.5 py-2 hover:bg-slate-800 rounded-lg text-slate-200 flex items-center justify-between transition-colors"
                >
                  <span className="flex items-center gap-2">
                    <ImageIcon className="w-3.5 h-3.5 text-indigo-400" />
                    <span>Descargar JPEG (Comprimido)</span>
                  </span>
                  <span className="text-[10px] font-mono text-indigo-400 font-bold">.JPG</span>
                </button>
                <button
                  onClick={() => handleTakeScreenshot('png', true)}
                  className="w-full text-left px-2.5 py-2 hover:bg-slate-800 rounded-lg text-slate-200 flex items-center justify-between transition-colors"
                >
                  <span className="flex items-center gap-2">
                    <Copy className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Copiar al Portapapeles</span>
                  </span>
                  <span className="text-[10px] font-mono text-emerald-400 font-bold">CLIP</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Capture Feedback Toast */}
      {captureFeedback && (
        <div className="absolute top-20 right-4 z-30 bg-emerald-950/90 border border-emerald-500/80 backdrop-blur-md px-3.5 py-2 rounded-xl text-xs text-emerald-200 font-bold shadow-2xl flex items-center gap-2 animate-fadeIn">
          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>{captureFeedback}</span>
        </div>
      )}

      {/* 3D WebGL Canvas Container */}
      <div ref={mountRef} className="w-full h-full cursor-grab active:cursor-grabbing" />

      {/* Bottom Floating Legend / Dimensions */}
      <div className="absolute bottom-4 left-4 right-4 z-20 flex items-center justify-between text-xs text-slate-400 pointer-events-none">
        <div className="pointer-events-auto bg-slate-900/80 backdrop-blur-md border border-slate-800 px-3 py-1.5 rounded-xl flex items-center gap-4">
          <span className="flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 inline-block" />
            <span>ON (Energizado)</span>
          </span>
          <span className="flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-cyan-400 inline-block" />
            <span>DPS Clase II</span>
          </span>
          <span className="flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-amber-400 inline-block" />
            <span>Barras PE / N</span>
          </span>
        </div>

        <div className="pointer-events-auto bg-slate-900/80 backdrop-blur-md border border-slate-800 px-3 py-1.5 rounded-xl">
          <span className="text-slate-300 font-mono">Gabinete IP65 • Riel DIN 35mm • 24 Módulos</span>
        </div>
      </div>
    </div>
  );
};

// Memoize component to prevent unneeded WebGL re-initializations
export const BoardSimulator3D = memo(BoardSimulator3DComponent);
export default BoardSimulator3D;
