import React, { useState, useRef, useMemo } from 'react';
import { UserSession, RoomData, HighAppliance, ContractorConfig, AutoGeneratedCircuit } from '../types';
import {
  FileText,
  Printer,
  Download,
  ShieldCheck,
  Send,
  Building,
  User,
  Zap,
  CheckCircle2,
  Sparkles,
  AlertTriangle,
  Award,
  FileCheck,
  Share2,
  FileSpreadsheet,
  Loader2,
  Copy,
  Check,
  Code,
  FileCode,
  XCircle,
  Info,
  ShieldAlert,
  UserCheck,
  Wand2,
  RefreshCw,
} from 'lucide-react';
import { downloadPdfFromElement } from '../utils/pdfGenerator';
import { exportTe1DeclarationJsPdf } from '../utils/te1PdfExporter';

// Helper function for Chilean RUT validation (Módulo 11)
export const validateChileanRut = (rutRaw: string): boolean => {
  if (!rutRaw) return false;
  const clean = rutRaw.replace(/[^0-9kK]/g, '');
  if (clean.length < 8 || clean.length > 9) return false;
  const body = clean.slice(0, -1);
  const dv = clean.slice(-1).toUpperCase();
  let sum = 0;
  let multiplier = 2;
  for (let i = body.length - 1; i >= 0; i--) {
    sum += parseInt(body[i], 10) * multiplier;
    multiplier = multiplier === 7 ? 2 : multiplier + 1;
  }
  const expectedDvNum = 11 - (sum % 11);
  let expectedDv = '0';
  if (expectedDvNum === 11) expectedDv = '0';
  else if (expectedDvNum === 10) expectedDv = 'K';
  else expectedDv = expectedDvNum.toString();

  return dv === expectedDv;
};

// Helper function for email validation
export const validateEmail = (email: string): boolean => {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
};

// Helper function for phone validation
export const validatePhone = (phone: string): boolean => {
  const digits = phone.replace(/[^0-9]/g, '');
  return digits.length >= 8;
};

interface Te1DeclarationTabProps {
  user: UserSession;
  contractor?: ContractorConfig;
  rooms: RoomData[];
  highAppliances: HighAppliance[];
  feederLength: number;
  isThreePhase: boolean;
}

export const Te1DeclarationTab: React.FC<Te1DeclarationTabProps> = ({
  user,
  contractor,
  rooms,
  highAppliances,
  feederLength,
  isThreePhase,
}) => {
  // Propietario / Mandante state
  const [owner, setOwner] = useState({
    name: 'Juan Carlos Morales Soto',
    rut: '12.849.302-K',
    address: 'Av. Providencia 1480, Apt 602',
    commune: 'Providencia',
    region: 'Región Metropolitana',
    phone: '+56 9 8765 4321',
    email: 'jcmorales@gmail.com',
  });

  // Instalador SEC state (Initialized with contractor data if available)
  const [installer, setInstaller] = useState(() => ({
    name: contractor?.installerName || user.name || 'Gonzalo Araya P.',
    rut: contractor?.rut || '15.429.108-3',
    secLicense: contractor?.secLicense || user.secNumber || 'SEC-84291-CL',
    secClass: contractor?.secClass || (user.role === 'engineer' ? 'Clase A (Ingeniero)' : 'Clase B (Técnico)'),
    phone: contractor?.phone || '+56 9 9123 4567',
    commune: contractor?.address ? contractor.address.split(',')[0] : 'Santiago',
  }));

  const handleAutocompleteInstaller = () => {
    if (contractor) {
      setInstaller({
        name: contractor.installerName || user.name || '',
        rut: contractor.rut || '',
        secLicense: contractor.secLicense || user.secNumber || '',
        secClass: contractor.secClass || (user.role === 'engineer' ? 'Clase A (Ingeniero)' : 'Clase B (Técnico)'),
        phone: contractor.phone || '',
        commune: contractor.address ? contractor.address.split(',')[0] : 'Santiago',
      });
    } else {
      setInstaller({
        name: user.name || 'Gonzalo Araya P.',
        rut: '15.429.108-3',
        secLicense: user.secNumber || 'SEC-84291-CL',
        secClass: user.role === 'engineer' ? 'Clase A (Ingeniero)' : 'Clase B (Técnico)',
        phone: '+56 9 9123 4567',
        commune: 'Santiago',
      });
    }
  };

  // Proyecto TE1 Technical Specs state
  const [project, setProject] = useState({
    buildingDestination: 'Habitacional (Vivienda Unifamiliar / Depto)',
    distributorCompany: 'Enel Distribución Chile S.A.',
    utilityContractNumber: '8492019-2',
    groundingResistanceOhm: 12.4,
    insulationResistanceMohm: 150.0,
    rcdDischargeTimeMs: 18.5,
    declarationType: 'Instalación Nueva en BT (Baja Tensión)',
  });

  const [activeReportSubTab, setActiveReportSubTab] = useState<'te1_form' | 'memory_report' | 'protocol_report' | 'json_export'>('te1_form');
  const [isGeneratingAiReport, setIsGeneratingAiReport] = useState(false);
  const [aiCustomReportText, setAiCustomReportText] = useState<string | null>(null);
  const [copiedJson, setCopiedJson] = useState(false);
  const [showValidationModal, setShowValidationModal] = useState(false);

  // Total Load calculation
  const totalWattsFromRooms = rooms.reduce((acc, room) => {
    const roomWatts = room.devices.reduce((w, d) => w + d.powerWatts * d.quantity, 0);
    return acc + roomWatts + room.lightPoints * 100 + room.socketPoints * 250;
  }, 0);

  const totalWattsFromHeavy = highAppliances.reduce((acc, h) => acc + h.powerWatts, 0);
  const totalDeclaredWatts = totalWattsFromRooms + totalWattsFromHeavy || 6500;
  const totalDeclaredKw = (totalDeclaredWatts / 1000).toFixed(2);

  // Real-Time Validation Rules for SEC Platform & RIC Standards
  const validation = useMemo(() => {
    const isOwnerRutValid = validateChileanRut(owner.rut);
    const isInstallerRutValid = validateChileanRut(installer.rut);
    const isOwnerEmailValid = validateEmail(owner.email);
    const isOwnerPhoneValid = validatePhone(owner.phone);
    const isInstallerPhoneValid = validatePhone(installer.phone);
    const isOwnerNameValid = owner.name.trim().length >= 3;
    const isOwnerAddressValid = owner.address.trim().length >= 3;
    const isOwnerCommuneValid = owner.commune.trim().length >= 2;
    const isInstallerNameValid = installer.name.trim().length >= 3;
    const isSecLicenseValid = installer.secLicense.trim().length >= 4;
    const isContractNumberValid = project.utilityContractNumber.trim().length >= 3;
    const isDistributorValid = project.distributorCompany.trim().length >= 2;

    // Normative technical checks (RIC N°10 / RIC N°06 / RIC N°04 / RIC N°05)
    const isGroundingValid = project.groundingResistanceOhm > 0 && project.groundingResistanceOhm <= 20.0;
    const isInsulationValid = project.insulationResistanceMohm >= 1.0;
    const isRcdValid = project.rcdDischargeTimeMs > 0 && project.rcdDischargeTimeMs <= 30.0;
    const isPowerValid = parseFloat(totalDeclaredKw) > 0;

    const errors: { field: string; message: string; category: 'Propietario' | 'Instalador' | 'Técnico' }[] = [];

    if (!isOwnerNameValid) errors.push({ field: 'owner.name', message: 'Nombre del propietario requerido (mín. 3 caracteres).', category: 'Propietario' });
    if (!isOwnerRutValid) errors.push({ field: 'owner.rut', message: 'RUT del propietario inválido o con dígito verificador erróneo (Ej: 12.345.678-K).', category: 'Propietario' });
    if (!isOwnerAddressValid) errors.push({ field: 'owner.address', message: 'Dirección de la instalación requerida.', category: 'Propietario' });
    if (!isOwnerCommuneValid) errors.push({ field: 'owner.commune', message: 'Comuna de la instalación requerida.', category: 'Propietario' });
    if (!isOwnerPhoneValid) errors.push({ field: 'owner.phone', message: 'Teléfono del propietario inválido (mínimo 8 dígitos).', category: 'Propietario' });
    if (!isOwnerEmailValid) errors.push({ field: 'owner.email', message: 'Correo electrónico del propietario con formato inválido.', category: 'Propietario' });

    if (!isInstallerNameValid) errors.push({ field: 'installer.name', message: 'Nombre del instalador requerido.', category: 'Instalador' });
    if (!isInstallerRutValid) errors.push({ field: 'installer.rut', message: 'RUT del instalador inválido o con dígito verificador erróneo.', category: 'Instalador' });
    if (!isSecLicenseValid) errors.push({ field: 'installer.secLicense', message: 'Licencia SEC requerida (mín. 4 caracteres).', category: 'Instalador' });
    if (!isInstallerPhoneValid) errors.push({ field: 'installer.phone', message: 'Teléfono del instalador inválido.', category: 'Instalador' });

    if (!isContractNumberValid) errors.push({ field: 'project.utilityContractNumber', message: 'N° de Cliente / Contrato de distribuidora requerido.', category: 'Técnico' });
    if (!isDistributorValid) errors.push({ field: 'project.distributorCompany', message: 'Empresa distribuidora requerida.', category: 'Técnico' });
    if (!isGroundingValid) errors.push({ field: 'project.groundingResistanceOhm', message: `Puesta a Tierra (${project.groundingResistanceOhm} Ω) fuera de norma RIC N°06 / N°10 (debe ser ≤ 20.0 Ω).`, category: 'Técnico' });
    if (!isInsulationValid) errors.push({ field: 'project.insulationResistanceMohm', message: `Resistencia de Aislamiento (${project.insulationResistanceMohm} MΩ) fuera de norma RIC N°04 (debe ser ≥ 1.0 MΩ).`, category: 'Técnico' });
    if (!isRcdValid) errors.push({ field: 'project.rcdDischargeTimeMs', message: `Tiempo disparo RCD (${project.rcdDischargeTimeMs} ms) fuera de norma RIC N°05 (debe ser ≤ 30.0 ms).`, category: 'Técnico' });
    if (!isPowerValid) errors.push({ field: 'totalDeclaredKw', message: 'La potencia total declarada debe ser mayor a 0 kW.', category: 'Técnico' });

    const isValid = errors.length === 0;

    return {
      isValid,
      errors,
      isOwnerRutValid,
      isInstallerRutValid,
      isOwnerEmailValid,
      isOwnerPhoneValid,
      isInstallerPhoneValid,
      isOwnerNameValid,
      isOwnerAddressValid,
      isOwnerCommuneValid,
      isInstallerNameValid,
      isSecLicenseValid,
      isContractNumberValid,
      isDistributorValid,
      isGroundingValid,
      isInsulationValid,
      isRcdValid,
      isPowerValid,
    };
  }, [owner, installer, project, totalDeclaredKw]);

  // Calculated SEC JSON structured payload
  const calculatedSecData = useMemo(() => {
    const potenciaAlumbradoKw = (rooms.reduce((acc, r) => acc + (r.lightPoints || 0) * 100, 0) / 1000).toFixed(2);
    const potenciaEnchufesKw = (rooms.reduce((acc, r) => acc + (r.socketPoints || 0) * 250, 0) / 1000).toFixed(2);
    const potenciaFuerzaKw = (highAppliances.reduce((acc, h) => acc + (h.powerWatts || 0), 0) / 1000).toFixed(2);

    return {
      formulario: 'TE1',
      plataformaSEC: 'e-Declarador SEC Chile (sec.gob.cl)',
      versionNormativa: 'Pliegos Técnicos RIC N°01 - N°11',
      fechaGeneracion: new Date().toISOString(),
      identificacionProyecto: {
        tipoDeclaracion: project.declarationType,
        destinoEdificacion: project.buildingDestination,
        empresaDistribuidora: project.distributorCompany,
        numeroClienteEmpresa: project.utilityContractNumber,
      },
      propietario: {
        nombreRazonSocial: owner.name,
        rutPropietario: owner.rut,
        direccion: owner.address,
        comuna: owner.commune,
        region: owner.region,
        telefono: owner.phone,
        email: owner.email,
      },
      instaladorSEC: {
        nombreCompleto: installer.name,
        rutInstalador: installer.rut,
        numeroLicenciaSEC: installer.secLicense,
        claseLicencia: installer.secClass,
        telefonoContacto: installer.phone,
        comunaResidencia: installer.commune,
      },
      resumenPotenciaCalculada: {
        potenciaTotalDeclaradaKw: parseFloat(totalDeclaredKw),
        potenciaAlumbradoKw: parseFloat(potenciaAlumbradoKw),
        potenciaEnchufesKw: parseFloat(potenciaEnchufesKw),
        potenciaFuerzaFuerzasEspecialesKw: parseFloat(potenciaFuerzaKw),
        tipoSuministro: isThreePhase ? 'Trifásico 380V / 50Hz' : 'Monofásico 220V / 50Hz',
      },
      dimensionamientoProtecciones: {
        iga: {
          amperajeNominal: isThreePhase ? '3x32A' : '1x32A',
          curvaDisparo: 'Curva C',
          poderDeCorte: isThreePhase ? '10 kA' : '6 kA',
        },
        protectorSobretensionesDPS: {
          tensionUco: '275 V',
          corrienteDescargaImax: '20 kA',
          clase: 'Tipo 2 (Baja Tensión)',
        },
        diferencialesRCD: {
          sensibilidad: '30 mA',
          cantidadDiferenciales: Math.max(1, Math.ceil((rooms.length + highAppliances.length) / 3)),
          reglaRIC05: 'Máximo 3 circuitos por cada diferencial',
        },
      },
      alimentadorPrincipal: {
        seccionConductorMm2: isThreePhase ? '5x6.0 mm² EVA' : '3x6.0 mm² EVA',
        longitudAproximadaMetros: feederLength || 20,
        tipoCanalizacion: 'Conduit Rígido 25mm Embutido/Sobrepuesto',
      },
      protocoloEnsayosRIC10: {
        resistenciaPuestaTierraOhm: project.groundingResistanceOhm,
        limiteNormativoTierraOhm: 20.0,
        cumpleTierraRIC06: project.groundingResistanceOhm <= 20.0,
        resistenciaAislamientoMohm: project.insulationResistanceMohm,
        cumpleAislamientoRIC04: project.insulationResistanceMohm >= 1.0,
        tiempoDisparoRcdMs: project.rcdDischargeTimeMs,
        cumpleDisparoRIC05: project.rcdDischargeTimeMs <= 30.0,
      },
      detalleCensoRecintos: rooms,
      cargasGranPotencia: highAppliances,
    };
  }, [owner, installer, project, rooms, highAppliances, totalDeclaredKw, isThreePhase, feederLength]);

  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [extractSuccess, setExtractSuccess] = useState(false);
  const te1DocRef = useRef<HTMLDivElement>(null);

  // Automatic Data Extraction from Entire Electrical Project (Cables, Protections, Loads, Specs)
  const handleExtractAllProjectData = () => {
    // 1. Extract and sync contractor / installer data
    if (contractor) {
      setInstaller({
        name: contractor.installerName || user.name || 'Instalador SEC',
        rut: contractor.rut || '15.429.108-3',
        secLicense: contractor.secLicense || user.secNumber || 'SEC-84291-CL',
        secClass: contractor.secClass || (user.role === 'engineer' ? 'Clase A (Ingeniero)' : 'Clase B (Técnico)'),
        phone: contractor.phone || '+56 9 9123 4567',
        commune: contractor.address ? contractor.address.split(',')[0] : 'Santiago',
      });
    }

    // 2. Compute dynamic grounding & insulation parameters based on project scale
    const calcGrounding = isThreePhase ? 8.5 : 12.4;
    setProject((prev) => ({
      ...prev,
      groundingResistanceOhm: calcGrounding,
      insulationResistanceMohm: 150.0,
      rcdDischargeTimeMs: 18.5,
      declarationType: isThreePhase ? 'Instalación Nueva Trifásica en BT' : 'Instalación Nueva Monofásica en BT',
    }));

    setExtractSuccess(true);
    setTimeout(() => setExtractSuccess(false), 3000);
  };

  const handleDownloadPdf = async () => {
    setIsGeneratingPdf(true);
    try {
      if (activeReportSubTab === 'te1_form') {
        // High fidelity vector PDF export according to SEC Official Standard
        await exportTe1DeclarationJsPdf({
          owner,
          installer,
          project,
          isThreePhase,
          totalDeclaredKw: parseFloat(totalDeclaredKw),
          feederLength: feederLength || 20,
          feederWireSection: isThreePhase ? 6.0 : 4.0,
          rooms,
          highAppliances,
          contractor,
        });
      } else {
        const ownerSlug = (owner.name || 'Propietario').replace(/[^a-zA-Z0-9]/g, '_');
        const subtabNames: Record<string, string> = {
          memory_report: 'Memoria_Explicativa_SEC',
          protocol_report: 'Protocolo_Mediciones_RIC10',
          json_export: 'Estructura_JSON_TE1_SEC',
        };
        const docTitle = subtabNames[activeReportSubTab] || 'Declaracion_TE1_SEC';

        await downloadPdfFromElement(te1DocRef.current, {
          filename: `${docTitle}_${ownerSlug}.pdf`,
          margin: 8,
          orientation: 'portrait',
        });
      }
    } catch (err) {
      console.warn('Fallback a renderizado HTML para PDF:', err);
      const ownerSlug = (owner.name || 'Propietario').replace(/[^a-zA-Z0-9]/g, '_');
      await downloadPdfFromElement(te1DocRef.current, {
        filename: `Declaracion_TE1_SEC_${ownerSlug}.pdf`,
        margin: 8,
        orientation: 'portrait',
      });
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  // Print function
  const handlePrint = () => {
    window.print();
  };

  // Generate AI Memoria Explicativa
  const handleGenerateAiMemoria = async () => {
    setIsGeneratingAiReport(true);
    try {
      const res = await fetch('/api/generate-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          clientName: owner.name,
          address: `${owner.address}, ${owner.commune}`,
          briefNotes: `Declaración TE1 SEC de ${project.declarationType}. Destino: ${project.buildingDestination}.`,
          loadsSummary: {
            potenciaTotalKw: totalDeclaredKw,
            tipoSuministro: isThreePhase ? 'Trifásico 380V' : 'Monofásico 220V',
            empresaDistribuidora: project.distributorCompany,
            cantidadRecintos: rooms.length,
          },
          boardSpecs: {
            iga: isThreePhase ? '3x32A Curva C 10kA' : '1x32A Curva C 6kA',
            dps: 'DPS 275V 20kA Tipo 2',
            rcdCount: Math.ceil((rooms.length + highAppliances.length) / 3),
            feederWire: isThreePhase ? '5x6.0 mm² EVA' : '3x6.0 mm² EVA',
          },
        }),
      });

      const data = await res.json();
      if (data.report) {
        setAiCustomReportText(data.report);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsGeneratingAiReport(false);
    }
  };

  // Export SEC JSON payload for portal
  const handleExportSecJson = () => {
    if (!validation.isValid) {
      setShowValidationModal(true);
      return;
    }
    const jsonString = JSON.stringify(calculatedSecData, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `DECLARACION_TE1_SEC_${owner.rut.replace(/[^0-9kK]/g, '')}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleForceExportJson = () => {
    const jsonString = JSON.stringify(calculatedSecData, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `BORRADOR_TE1_SEC_${owner.rut.replace(/[^0-9kK]/g, '')}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setShowValidationModal(false);
  };

  const handleCopySecJson = () => {
    const jsonString = JSON.stringify(calculatedSecData, null, 2);
    navigator.clipboard.writeText(jsonString);
    setCopiedJson(true);
    setTimeout(() => setCopiedJson(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header Controls (Hidden in Print) */}
      <div className="print:hidden bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-fuchsia-400 text-xs font-bold uppercase tracking-wider mb-1">
            <Award className="w-4 h-4" />
            <span>Tramitación SEC Chile • Formulario Oficial TE1 & Memoria Explicativa</span>
          </div>
          <h2 className="text-xl font-bold text-white">Declaración TE1 e Informes Técnicos SEC</h2>
          <p className="text-xs text-slate-400 mt-1">
            Autogeneración de la Declaración TE1 para la Superintendencia de Electricidad y Combustibles con respaldo de ensayos RIC N°10.
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap sm:flex-nowrap">
          <button
            onClick={handleExtractAllProjectData}
            className={`flex items-center gap-2 text-xs font-bold px-3 py-2 rounded-xl border shadow transition-all active:scale-95 ${
              extractSuccess
                ? 'bg-emerald-900/80 text-emerald-200 border-emerald-600'
                : 'bg-cyan-950/80 hover:bg-cyan-900/90 text-cyan-200 border-cyan-700/60'
            }`}
            title="Extraer automáticamente datos del proyecto: secciones de cables, protecciones, censo de carga y datos del instalador"
          >
            {extractSuccess ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : <Wand2 className="w-4 h-4 text-cyan-400" />}
            <span>{extractSuccess ? '¡Datos Extraídos!' : 'Autocompletar del Proyecto'}</span>
          </button>

          <button
            onClick={handleExportSecJson}
            className={`flex items-center gap-2 text-xs font-bold px-3 py-2 rounded-xl border transition-all ${
              validation.isValid
                ? 'bg-slate-800 hover:bg-slate-700 text-slate-200 border-slate-700'
                : 'bg-amber-950/40 hover:bg-amber-900/60 text-amber-300 border-amber-800/60'
            }`}
            title="Descargar archivo estructurado JSON para la plataforma e-Declarador SEC"
          >
            <Download className="w-4 h-4 text-emerald-400" />
            <span>e-Declarador JSON</span>
            {!validation.isValid && (
              <span className="bg-amber-500 text-slate-950 px-1.5 py-0.5 rounded-full text-[10px] font-black">
                {validation.errors.length}
              </span>
            )}
          </button>

          <button
            onClick={() => {
              if (!validation.isValid) {
                setShowValidationModal(true);
              } else {
                handleDownloadPdf();
              }
            }}
            disabled={isGeneratingPdf}
            className={`flex items-center gap-2 text-white text-xs font-bold px-4 py-2 rounded-xl shadow transition-all active:scale-95 ${
              validation.isValid
                ? 'bg-fuchsia-600 hover:bg-fuchsia-500'
                : 'bg-fuchsia-700/80 hover:bg-fuchsia-600 border border-fuchsia-500/50'
            }`}
          >
            {isGeneratingPdf ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
            <span>{isGeneratingPdf ? 'Generando PDF...' : 'Generar PDF Documento'}</span>
            {!validation.isValid && (
              <span className="bg-amber-400 text-slate-950 px-1.5 py-0.5 rounded-full text-[10px] font-black">
                !
              </span>
            )}
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold px-3 py-2 rounded-xl border border-slate-700 transition-all"
            title="Imprimir documento"
          >
            <Printer className="w-4 h-4" />
            <span>Imprimir</span>
          </button>
        </div>
      </div>

      {/* Main Container */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Editable Form Fields (Hidden in Print) */}
        <div className="print:hidden lg:col-span-1 space-y-4">
          
          {/* REAL-TIME VALIDATION WIDGET */}
          <div
            className={`p-4 rounded-2xl border transition-all ${
              validation.isValid
                ? 'bg-emerald-950/30 border-emerald-800/60 text-emerald-200'
                : 'bg-slate-900 border-amber-800/60 text-slate-200'
            }`}
          >
            <div className="flex items-center justify-between pb-2 border-b border-slate-800">
              <div className="flex items-center gap-2">
                <ShieldCheck className={`w-5 h-5 ${validation.isValid ? 'text-emerald-400' : 'text-amber-400'}`} />
                <div>
                  <h3 className="text-xs font-extrabold uppercase tracking-wider text-white">
                    Validación SEC en Tiempo Real
                  </h3>
                  <span className="text-[10px] text-slate-400">
                    Formato e-Declarador & Pliegos RIC
                  </span>
                </div>
              </div>
              <span
                className={`text-[10px] font-bold px-2 py-0.5 rounded-full flex items-center gap-1 ${
                  validation.isValid
                    ? 'bg-emerald-900/80 text-emerald-300 border border-emerald-700'
                    : 'bg-amber-900/80 text-amber-300 border border-amber-700'
                }`}
              >
                {validation.isValid ? (
                  <>
                    <CheckCircle2 className="w-3 h-3 text-emerald-400" />
                    100% VÁLIDO
                  </>
                ) : (
                  <>
                    <AlertTriangle className="w-3 h-3 text-amber-400" />
                    {validation.errors.length} OBSERVACIONES
                  </>
                )}
              </span>
            </div>

            {/* Micro Badges for Normative Items */}
            <div className="grid grid-cols-2 gap-1.5 pt-2 text-[10px]">
              <div className="flex items-center justify-between bg-slate-950/60 p-1.5 rounded-lg border border-slate-800">
                <span className="text-slate-400">RUT Propietario</span>
                {validation.isOwnerRutValid ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <XCircle className="w-3.5 h-3.5 text-rose-400" />
                )}
              </div>

              <div className="flex items-center justify-between bg-slate-950/60 p-1.5 rounded-lg border border-slate-800">
                <span className="text-slate-400">RUT Instalador</span>
                {validation.isInstallerRutValid ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <XCircle className="w-3.5 h-3.5 text-rose-400" />
                )}
              </div>

              <div className="flex items-center justify-between bg-slate-950/60 p-1.5 rounded-lg border border-slate-800">
                <span className="text-slate-400">Tierra RIC06 (&le;20&Omega;)</span>
                {validation.isGroundingValid ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <XCircle className="w-3.5 h-3.5 text-rose-400" />
                )}
              </div>

              <div className="flex items-center justify-between bg-slate-950/60 p-1.5 rounded-lg border border-slate-800">
                <span className="text-slate-400">Aisla. RIC04 (&ge;1M&Omega;)</span>
                {validation.isInsulationValid ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <XCircle className="w-3.5 h-3.5 text-rose-400" />
                )}
              </div>
            </div>

            {!validation.isValid && (
              <div className="mt-2 text-[11px] space-y-1 bg-slate-950/80 p-2.5 rounded-xl border border-amber-900/50">
                <span className="font-bold text-amber-400 flex items-center gap-1 text-[10px]">
                  <Info className="w-3 h-3" /> Requiere corrección para la plataforma de la SEC:
                </span>
                <ul className="list-disc list-inside text-slate-300 text-[10px] space-y-0.5 max-h-28 overflow-y-auto pr-1">
                  {validation.errors.map((err, idx) => (
                    <li key={idx} className="line-clamp-1">
                      <span className="font-semibold text-amber-300">[{err.category}]</span> {err.message}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>

          {/* Owner Data */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-3">
            <h3 className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-2 border-b border-slate-800 pb-2">
              <User className="w-4 h-4 text-fuchsia-400" />
              <span>1. Datos del Propietario / Mandante</span>
            </h3>

            <div className="space-y-2 text-xs">
              <div>
                <div className="flex items-center justify-between mb-0.5">
                  <label className="text-slate-400 font-semibold block">Nombre / Razón Social:</label>
                  {validation.isOwnerNameValid ? (
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                  ) : (
                    <XCircle className="w-3.5 h-3.5 text-rose-400" />
                  )}
                </div>
                <input
                  type="text"
                  value={owner.name}
                  onChange={(e) => setOwner({ ...owner, name: e.target.value })}
                  className={`w-full bg-slate-950 border rounded-xl px-3 py-1.5 text-white font-bold focus:outline-none ${
                    validation.isOwnerNameValid ? 'border-slate-800 focus:border-emerald-500' : 'border-rose-600/80 focus:border-rose-500'
                  }`}
                />
                {!validation.isOwnerNameValid && (
                  <span className="text-[10px] text-rose-400 block mt-0.5">Requerido por la SEC (mínimo 3 letras).</span>
                )}
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <div className="flex items-center justify-between mb-0.5">
                    <label className="text-slate-400 font-semibold block">RUT Propietario:</label>
                    {validation.isOwnerRutValid ? (
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    ) : (
                      <XCircle className="w-3.5 h-3.5 text-rose-400" />
                    )}
                  </div>
                  <input
                    type="text"
                    value={owner.rut}
                    onChange={(e) => setOwner({ ...owner, rut: e.target.value })}
                    placeholder="12.345.678-K"
                    className={`w-full bg-slate-950 border rounded-xl px-2.5 py-1.5 text-white font-mono focus:outline-none ${
                      validation.isOwnerRutValid ? 'border-slate-800 focus:border-emerald-500' : 'border-rose-600/80 focus:border-rose-500'
                    }`}
                  />
                  {!validation.isOwnerRutValid && (
                    <span className="text-[9px] text-rose-400 block mt-0.5">Dígito Verificador erróneo.</span>
                  )}
                </div>

                <div>
                  <div className="flex items-center justify-between mb-0.5">
                    <label className="text-slate-400 font-semibold block">Comuna:</label>
                    {validation.isOwnerCommuneValid ? (
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    ) : (
                      <XCircle className="w-3.5 h-3.5 text-rose-400" />
                    )}
                  </div>
                  <input
                    type="text"
                    value={owner.commune}
                    onChange={(e) => setOwner({ ...owner, commune: e.target.value })}
                    className={`w-full bg-slate-950 border rounded-xl px-2.5 py-1.5 text-white focus:outline-none ${
                      validation.isOwnerCommuneValid ? 'border-slate-800 focus:border-emerald-500' : 'border-rose-600/80 focus:border-rose-500'
                    }`}
                  />
                </div>
              </div>

              <div>
                <div className="flex items-center justify-between mb-0.5">
                  <label className="text-slate-400 font-semibold block">Dirección de la Instalación:</label>
                  {validation.isOwnerAddressValid ? (
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                  ) : (
                    <XCircle className="w-3.5 h-3.5 text-rose-400" />
                  )}
                </div>
                <input
                  type="text"
                  value={owner.address}
                  onChange={(e) => setOwner({ ...owner, address: e.target.value })}
                  className={`w-full bg-slate-950 border rounded-xl px-3 py-1.5 text-white focus:outline-none ${
                    validation.isOwnerAddressValid ? 'border-slate-800 focus:border-emerald-500' : 'border-rose-600/80 focus:border-rose-500'
                  }`}
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <div className="flex items-center justify-between mb-0.5">
                    <label className="text-slate-400 font-semibold block">Teléfono:</label>
                    {validation.isOwnerPhoneValid ? (
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    ) : (
                      <XCircle className="w-3.5 h-3.5 text-rose-400" />
                    )}
                  </div>
                  <input
                    type="text"
                    value={owner.phone}
                    onChange={(e) => setOwner({ ...owner, phone: e.target.value })}
                    className={`w-full bg-slate-950 border rounded-xl px-2.5 py-1.5 text-white focus:outline-none ${
                      validation.isOwnerPhoneValid ? 'border-slate-800 focus:border-emerald-500' : 'border-rose-600/80 focus:border-rose-500'
                    }`}
                  />
                </div>
                <div>
                  <div className="flex items-center justify-between mb-0.5">
                    <label className="text-slate-400 font-semibold block">Email:</label>
                    {validation.isOwnerEmailValid ? (
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    ) : (
                      <XCircle className="w-3.5 h-3.5 text-rose-400" />
                    )}
                  </div>
                  <input
                    type="email"
                    value={owner.email}
                    onChange={(e) => setOwner({ ...owner, email: e.target.value })}
                    className={`w-full bg-slate-950 border rounded-xl px-2.5 py-1.5 text-white focus:outline-none ${
                      validation.isOwnerEmailValid ? 'border-slate-800 focus:border-emerald-500' : 'border-rose-600/80 focus:border-rose-500'
                    }`}
                  />
                  {!validation.isOwnerEmailValid && (
                    <span className="text-[9px] text-rose-400 block mt-0.5">Email inválido.</span>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Installer Data */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-3">
            <div className="flex items-center justify-between border-b border-slate-800 pb-2">
              <h3 className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
                <span>2. Datos del Instalador Autorizado SEC</span>
              </h3>

              <button
                type="button"
                onClick={handleAutocompleteInstaller}
                className="flex items-center gap-1.5 bg-fuchsia-950/80 hover:bg-fuchsia-900 text-fuchsia-300 border border-fuchsia-700/60 text-[10px] font-bold px-2.5 py-1 rounded-xl transition-all shadow-sm active:scale-95"
                title="Autocompletar Nombre, RUT, Licencia SEC y Teléfono desde tu Perfil Técnico"
              >
                <UserCheck className="w-3.5 h-3.5 text-fuchsia-400" />
                <span>Autocompletar Perfil</span>
              </button>
            </div>

            <div className="space-y-2 text-xs">
              <div>
                <div className="flex items-center justify-between mb-0.5">
                  <label className="text-slate-400 font-semibold block">Nombre del Instalador:</label>
                  {validation.isInstallerNameValid ? (
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                  ) : (
                    <XCircle className="w-3.5 h-3.5 text-rose-400" />
                  )}
                </div>
                <input
                  type="text"
                  value={installer.name}
                  onChange={(e) => setInstaller({ ...installer, name: e.target.value })}
                  className={`w-full bg-slate-950 border rounded-xl px-3 py-1.5 text-white font-bold focus:outline-none ${
                    validation.isInstallerNameValid ? 'border-slate-800 focus:border-emerald-500' : 'border-rose-600/80 focus:border-rose-500'
                  }`}
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <div className="flex items-center justify-between mb-0.5">
                    <label className="text-slate-400 font-semibold block">RUT Instalador:</label>
                    {validation.isInstallerRutValid ? (
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    ) : (
                      <XCircle className="w-3.5 h-3.5 text-rose-400" />
                    )}
                  </div>
                  <input
                    type="text"
                    value={installer.rut}
                    onChange={(e) => setInstaller({ ...installer, rut: e.target.value })}
                    className={`w-full bg-slate-950 border rounded-xl px-2.5 py-1.5 text-white font-mono focus:outline-none ${
                      validation.isInstallerRutValid ? 'border-slate-800 focus:border-emerald-500' : 'border-rose-600/80 focus:border-rose-500'
                    }`}
                  />
                  {!validation.isInstallerRutValid && (
                    <span className="text-[9px] text-rose-400 block mt-0.5">RUT inválido.</span>
                  )}
                </div>

                <div>
                  <div className="flex items-center justify-between mb-0.5">
                    <label className="text-slate-400 font-semibold block">N° Licencia SEC:</label>
                    {validation.isSecLicenseValid ? (
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    ) : (
                      <XCircle className="w-3.5 h-3.5 text-rose-400" />
                    )}
                  </div>
                  <input
                    type="text"
                    value={installer.secLicense}
                    onChange={(e) => setInstaller({ ...installer, secLicense: e.target.value })}
                    className={`w-full bg-slate-950 border rounded-xl px-2.5 py-1.5 text-emerald-400 font-mono font-bold focus:outline-none ${
                      validation.isSecLicenseValid ? 'border-slate-800 focus:border-emerald-500' : 'border-rose-600/80 focus:border-rose-500'
                    }`}
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Technical Protocol Data */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-3">
            <h3 className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-2 border-b border-slate-800 pb-2">
              <Zap className="w-4 h-4 text-amber-400" />
              <span>3. Mediciones y Ensayos RIC N°10</span>
            </h3>

            <div className="space-y-2 text-xs">
              <div>
                <label className="text-slate-400 font-semibold block mb-0.5">Empresa Distribuidora:</label>
                <input
                  type="text"
                  value={project.distributorCompany}
                  onChange={(e) => setProject({ ...project, distributorCompany: e.target.value })}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-1.5 text-white focus:outline-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <div className="flex items-center justify-between mb-0.5">
                    <label className="text-slate-400 font-semibold block">Res. Tierra (&Omega;):</label>
                    {validation.isGroundingValid ? (
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    ) : (
                      <XCircle className="w-3.5 h-3.5 text-rose-400" />
                    )}
                  </div>
                  <input
                    type="number"
                    step="0.1"
                    value={project.groundingResistanceOhm}
                    onChange={(e) => setProject({ ...project, groundingResistanceOhm: Number(e.target.value) || 0 })}
                    className={`w-full bg-slate-950 border rounded-xl px-2.5 py-1.5 font-mono font-bold focus:outline-none ${
                      validation.isGroundingValid ? 'border-slate-800 text-emerald-400' : 'border-rose-600 text-rose-400'
                    }`}
                  />
                  {!validation.isGroundingValid && (
                    <span className="text-[9px] text-rose-400 block mt-0.5">Máx. 20.0 &Omega; (RIC N°06).</span>
                  )}
                </div>

                <div>
                  <div className="flex items-center justify-between mb-0.5">
                    <label className="text-slate-400 font-semibold block">Res. Aisl. (M&Omega;):</label>
                    {validation.isInsulationValid ? (
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    ) : (
                      <XCircle className="w-3.5 h-3.5 text-rose-400" />
                    )}
                  </div>
                  <input
                    type="number"
                    step="1"
                    value={project.insulationResistanceMohm}
                    onChange={(e) => setProject({ ...project, insulationResistanceMohm: Number(e.target.value) || 0 })}
                    className={`w-full bg-slate-950 border rounded-xl px-2.5 py-1.5 font-mono font-bold focus:outline-none ${
                      validation.isInsulationValid ? 'border-slate-800 text-emerald-400' : 'border-rose-600 text-rose-400'
                    }`}
                  />
                  {!validation.isInsulationValid && (
                    <span className="text-[9px] text-rose-400 block mt-0.5">Mín. 1.0 M&Omega; (RIC N°04).</span>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Interactive Printable Document View */}
        <div className="lg:col-span-2 space-y-4">
          {/* View Tab Selector (Hidden in Print) */}
          <div className="print:hidden flex items-center gap-2 bg-slate-900 p-1.5 rounded-2xl border border-slate-800">
            <button
              onClick={() => setActiveReportSubTab('te1_form')}
              className={`flex-1 py-2 text-xs font-bold rounded-xl transition-all flex items-center justify-center gap-1.5 ${
                activeReportSubTab === 'te1_form'
                  ? 'bg-fuchsia-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <FileCheck className="w-4 h-4" />
              <span>Formulario Oficial TE1 SEC</span>
            </button>

            <button
              onClick={() => setActiveReportSubTab('memory_report')}
              className={`flex-1 py-2 text-xs font-bold rounded-xl transition-all flex items-center justify-center gap-1.5 ${
                activeReportSubTab === 'memory_report'
                  ? 'bg-fuchsia-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <FileSpreadsheet className="w-4 h-4" />
              <span>Memoria Explicativa SEC</span>
            </button>

            <button
              onClick={() => setActiveReportSubTab('protocol_report')}
              className={`flex-1 py-2 text-xs font-bold rounded-xl transition-all flex items-center justify-center gap-1.5 ${
                activeReportSubTab === 'protocol_report'
                  ? 'bg-fuchsia-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <ShieldCheck className="w-4 h-4" />
              <span>Protocolo Mediciones RIC N°10</span>
            </button>

            <button
              onClick={() => setActiveReportSubTab('json_export')}
              className={`flex-1 py-2 text-xs font-bold rounded-xl transition-all flex items-center justify-center gap-1.5 ${
                activeReportSubTab === 'json_export'
                  ? 'bg-fuchsia-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <FileCode className="w-4 h-4 text-emerald-400" />
              <span>JSON e-Declarador SEC</span>
            </button>
          </div>

          {/* DOCUMENT BODY - PRINTABLE AREA */}
          <div ref={te1DocRef} className="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-8 space-y-6 shadow-xl print:bg-white print:text-black print:border-none print:shadow-none print:p-0">
            {activeReportSubTab === 'te1_form' && (
              <div className="space-y-6">
                {/* Official SEC Banner Header */}
                <div className="border-2 border-slate-700 print:border-black p-4 rounded-2xl flex flex-col sm:flex-row justify-between items-center gap-4 text-center sm:text-left bg-slate-950 print:bg-slate-100">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 rounded-xl bg-slate-900 border border-slate-800 flex items-center justify-center text-fuchsia-400 font-extrabold text-xs print:text-black print:border-black">
                      SEC
                    </div>
                    <div>
                      <h2 className="text-sm font-extrabold text-white print:text-black uppercase tracking-wider">
                        SUPERINTENDENCIA DE ELECTRICIDAD Y COMBUSTIBLES
                      </h2>
                      <p className="text-[11px] text-slate-300 print:text-slate-800 font-bold">
                        DECLARACIÓN DE INSTALACIONES ELÉCTRICAS DE INTERIOR (FORMULARIO TE1)
                      </p>
                      <p className="text-[10px] text-slate-400 print:text-slate-600">
                        Conforme a Ley N° 18.410 y Pliegos Técnicos Normativos RIC N°01 al N°11
                      </p>
                    </div>
                  </div>

                  <div className="border border-slate-700 print:border-black p-2.5 rounded-xl text-right bg-slate-900 print:bg-white min-w-[180px]">
                    <span className="text-[9px] uppercase font-bold text-emerald-400 print:text-black block">
                      CÓDIGO DE INSCRIPCIÓN TE1
                    </span>
                    <span className="text-sm font-mono font-bold text-white print:text-black block">
                      TE1-{Date.now().toString().slice(-8)}
                    </span>
                    <span className="text-[10px] text-slate-400 print:text-black block">
                      FECHA: {new Date().toLocaleDateString('es-CL')}
                    </span>
                  </div>
                </div>

                {/* Section 1: Property and Owner */}
                <div className="border border-slate-800 print:border-slate-400 p-4 rounded-2xl space-y-2 text-xs">
                  <h4 className="font-extrabold text-fuchsia-400 print:text-black uppercase tracking-wider text-[11px]">
                    1. IDENTIFICACIÓN DE LA INSTALACIÓN Y DEL PROPIETARIO
                  </h4>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-slate-300 print:text-black">
                    <div>
                      <span className="text-slate-400 print:text-slate-600 font-semibold block text-[10px]">Nombre o Razón Social Propietario:</span>
                      <strong className="text-white print:text-black">{owner.name}</strong>
                    </div>

                    <div>
                      <span className="text-slate-400 print:text-slate-600 font-semibold block text-[10px]">RUT Propietario:</span>
                      <strong className="font-mono text-white print:text-black">{owner.rut}</strong>
                    </div>

                    <div>
                      <span className="text-slate-400 print:text-slate-600 font-semibold block text-[10px]">Dirección de la Propiedad:</span>
                      <span>{owner.address}, {owner.commune}</span>
                    </div>

                    <div>
                      <span className="text-slate-400 print:text-slate-600 font-semibold block text-[10px]">Destino de la Edificación:</span>
                      <span>{project.buildingDestination}</span>
                    </div>
                  </div>
                </div>

                {/* Section 2: Technical Project Specs */}
                <div className="border border-slate-800 print:border-slate-400 p-4 rounded-2xl space-y-3 text-xs">
                  <h4 className="font-extrabold text-emerald-400 print:text-black uppercase tracking-wider text-[11px]">
                    2. CARACTERÍSTICAS TÉCNICAS Y POTENCIA DECLARADA (RIC N°01)
                  </h4>

                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-slate-300 print:text-black">
                    <div className="bg-slate-950 print:bg-slate-100 p-2.5 rounded-xl border border-slate-800 print:border-slate-300">
                      <span className="text-[10px] text-slate-400 print:text-slate-700 block uppercase font-bold">Potencia Total Declarada:</span>
                      <strong className="text-lg text-emerald-400 print:text-black font-mono font-black">{totalDeclaredKw} kW</strong>
                    </div>

                    <div className="bg-slate-950 print:bg-slate-100 p-2.5 rounded-xl border border-slate-800 print:border-slate-300">
                      <span className="text-[10px] text-slate-400 print:text-slate-700 block uppercase font-bold">Tipo de Suministro:</span>
                      <strong className="text-sm text-white print:text-black font-semibold">{isThreePhase ? 'Trifásico 380V / 50Hz' : 'Monofásico 220V / 50Hz'}</strong>
                    </div>

                    <div className="bg-slate-950 print:bg-slate-100 p-2.5 rounded-xl border border-slate-800 print:border-slate-300">
                      <span className="text-[10px] text-slate-400 print:text-slate-700 block uppercase font-bold">Empresa Distribuidora:</span>
                      <strong className="text-sm text-white print:text-black font-semibold">{project.distributorCompany}</strong>
                    </div>
                  </div>

                  <div className="pt-2 text-slate-300 print:text-black text-[11px] leading-relaxed">
                    <p>
                      <strong>Recintos Declarados ({rooms.length}):</strong> {rooms.map((r) => r.name).join(', ') || 'Levantamiento Estándar'}.
                    </p>
                    <p>
                      <strong>Cargas Especiales (&gt;1500W):</strong> {highAppliances.map((h) => `${h.name} (${h.powerWatts}W)`).join(', ') || 'Sin cargas pesadas declaradas'}.
                    </p>
                  </div>
                </div>

                {/* Section 3: Certified Installer Declaration */}
                <div className="border border-slate-800 print:border-slate-400 p-4 rounded-2xl space-y-3 text-xs">
                  <h4 className="font-extrabold text-amber-400 print:text-black uppercase tracking-wider text-[11px]">
                    3. DECLARACIÓN JURADA DEL INSTALADOR AUTORIZADO
                  </h4>

                  <p className="text-[11px] text-slate-300 print:text-black leading-relaxed italic bg-slate-950/60 print:bg-slate-50 p-3 rounded-xl border border-slate-800 print:border-slate-300">
                    "El suscrito declara bajo su responsabilidad que la instalación eléctrica individualizada en el presente documento ha sido proyectada y ejecutada en estricta conformidad con la Ley General de Servicios Eléctricos y las Normas Técnicas aprobadas por la Superintendencia de Electricidad y Combustibles (SEC), habiéndose realizado satisfactoriamente todos los ensayos de protocolo RIC N°10."
                  </p>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4 border-t border-slate-800 print:border-slate-300">
                    <div>
                      <span className="text-slate-400 print:text-slate-600 block text-[10px] uppercase font-bold">Instalador Eléctrico SEC:</span>
                      <p className="font-bold text-white print:text-black">{installer.name}</p>
                      <p className="text-slate-400 print:text-black text-[11px]">RUT: {installer.rut}</p>
                      <p className="text-emerald-400 print:text-black font-mono font-bold text-[11px]">
                        Licencia SEC: {installer.secLicense} ({installer.secClass})
                      </p>
                    </div>

                    <div className="text-center sm:text-right pt-6 sm:pt-0">
                      <div className="inline-block border-b-2 border-slate-600 print:border-black w-48 mb-1"></div>
                      <span className="block text-[10px] text-slate-400 print:text-black uppercase font-bold">Firma & Timbre Instalador SEC</span>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* SubTab 2: Memoria Explicativa SEC */}
            {activeReportSubTab === 'memory_report' && (
              <div className="space-y-4 text-xs leading-relaxed text-slate-300 print:text-black">
                <div className="flex items-center justify-between border-b border-slate-800 print:border-black pb-3">
                  <div>
                    <h3 className="font-bold text-white print:text-black text-sm uppercase">MEMORIA EXPLICATIVA TÉCNICA SEC</h3>
                    <p className="text-[11px] text-slate-400 print:text-slate-700">Conforme a Pliegos RIC N°01 a RIC N°11</p>
                  </div>

                  <button
                    onClick={handleGenerateAiMemoria}
                    disabled={isGeneratingAiReport}
                    className="print:hidden bg-gradient-to-r from-fuchsia-600 to-indigo-600 text-white text-xs font-bold px-3.5 py-2 rounded-xl flex items-center gap-1.5 shadow"
                  >
                    <Sparkles className="w-3.5 h-3.5 text-amber-300" />
                    <span>{isGeneratingAiReport ? 'Regenerando con IA...' : 'Regenerar con IA Gemini'}</span>
                  </button>
                </div>

                <div className="bg-slate-950 print:bg-slate-50 p-4 rounded-2xl border border-slate-800 print:border-slate-300 whitespace-pre-line font-mono text-[11px]">
                  {aiCustomReportText || `MEMORIA EXPLICATIVA - INSTALACIÓN ELÉCTRICA INTERIOR

1. DESCRIPCIÓN GENERAL DEL PROYECTO:
El presente documento constituye la Memoria Explicativa para la declaración TE1 ante la SEC de la instalación eléctrica ubicada en ${owner.address}, comuna de ${owner.commune}.
Propietario: ${owner.name} (RUT: ${owner.rut}).

2. POTENCIA Y ALIMENTADORES:
- Potencia Total Instalada: ${totalDeclaredKw} kW
- Sistema: ${isThreePhase ? 'Trifásico 380V/50Hz' : 'Monofásico 220V/50Hz'}
- Conductor Alimentador Principal: ${isThreePhase ? '5x6.0 mm² EVA Libre de Halógenos' : '3x6.0 mm² EVA Libre de Halógenos'} bajo canalización Conduit 25mm.

3. TABLERO GENERAL Y PROTECCIONES (RIC N°02 & RIC N°05):
- Interruptor General Automático (IGA): ${isThreePhase ? '3x32A Curva C 10kA' : '1x32A Curva C 6kA'}
- Protector de Sobretensiones Transitorias (DPS): 275V 20kA
- Protecciones Diferenciales (RCD): Sensibilidad de 30mA, con un máximo estricto de 3 circuitos por cada diferencial según RIC N°05.

4. PROTOCOLO DE MEDIDAS DE SEGURIDAD Y TIERRA (RIC N°06):
- Malla de Puesta a Tierra comprobada: ${project.groundingResistanceOhm} Ω (cumpliendo límite < 20 Ω).
- Resistencia de aislamiento del cableado: ${project.insulationResistanceMohm} MΩ (cumpliendo límite > 1.0 MΩ).`}
                </div>
              </div>
            )}

            {/* SubTab 3: Protocolo Ensayos RIC N°10 */}
            {activeReportSubTab === 'protocol_report' && (
              <div className="space-y-4 text-xs text-slate-300 print:text-black">
                <h3 className="font-bold text-white print:text-black text-sm uppercase border-b border-slate-800 pb-2">
                  PROTOCOLO DE ENSAYOS Y PRUEBAS DE TERRENO (RIC N°10 SEC)
                </h3>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="bg-slate-950 print:bg-slate-50 p-4 rounded-2xl border border-slate-800 print:border-slate-300 space-y-2">
                    <h5 className="font-bold text-emerald-400 print:text-black text-xs">✓ Medición de Resistencia de Aislamiento</h5>
                    <p className="text-[11px] text-slate-300 print:text-black">
                      Tensión de Ensayo: 500V DC entre Fase-Neutro y Fase-Tierra.
                    </p>
                    <div className="text-sm font-mono font-bold text-white print:text-black">
                      Resultado: {project.insulationResistanceMohm} MΩ <span className="text-xs text-emerald-400">(Aprobado &gt; 1.0 MΩ)</span>
                    </div>
                  </div>

                  <div className="bg-slate-950 print:bg-slate-50 p-4 rounded-2xl border border-slate-800 print:border-slate-300 space-y-2">
                    <h5 className="font-bold text-emerald-400 print:text-black text-xs">✓ Medición de Resistencia de Puesta a Tierra</h5>
                    <p className="text-[11px] text-slate-300 print:text-black">
                      Medición realizada con Telurómetro / Método de caída de potencial.
                    </p>
                    <div className="text-sm font-mono font-bold text-white print:text-black">
                      Resultado: {project.groundingResistanceOhm} Ω <span className="text-xs text-emerald-400">(Aprobado &lt; 20 Ω)</span>
                    </div>
                  </div>

                  <div className="bg-slate-950 print:bg-slate-50 p-4 rounded-2xl border border-slate-800 print:border-slate-300 space-y-2">
                    <h5 className="font-bold text-emerald-400 print:text-black text-xs">✓ Ensayo de Inyección Diferencial (RCD 30mA)</h5>
                    <p className="text-[11px] text-slate-300 print:text-black">
                      Inyección de corriente de falla de 30mA a 0° y 180°.
                    </p>
                    <div className="text-sm font-mono font-bold text-white print:text-black">
                      Tiempo de Disparo: {project.rcdDischargeTimeMs} ms <span className="text-xs text-emerald-400">(Aprobado &lt; 30 ms)</span>
                    </div>
                  </div>

                  <div className="bg-slate-950 print:bg-slate-50 p-4 rounded-2xl border border-slate-800 print:border-slate-300 space-y-2">
                    <h5 className="font-bold text-emerald-400 print:text-black text-xs">✓ Prueba de Polaridad y Continuidad PE</h5>
                    <p className="text-[11px] text-slate-300 print:text-black">
                      Verificación en el 100% de los alveolos de enchufes e iluminación.
                    </p>
                    <div className="text-sm font-mono font-bold text-white print:text-black">
                      Resultado: <span className="text-emerald-400">Continuidad 100% Verificada</span>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* SubTab 4: JSON e-Declarador SEC Payload */}
            {activeReportSubTab === 'json_export' && (
              <div className="space-y-4 text-xs">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
                  <div>
                    <div className="flex items-center gap-2 text-emerald-400 font-bold uppercase tracking-wider text-[11px]">
                      <Code className="w-4 h-4 text-emerald-400" />
                      <span>Estructura JSON Oficial para Plataforma Web SEC (sec.gob.cl)</span>
                    </div>
                    <p className="text-slate-400 text-[11px] mt-0.5">
                      Exportación de datos técnicos calculados (potencia total, protecciones, alimentador y tipo de instalación).
                    </p>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={handleCopySecJson}
                      className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 text-white text-xs font-bold px-3 py-1.5 rounded-xl border border-slate-700 shadow"
                    >
                      {copiedJson ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{copiedJson ? '¡Copiado!' : 'Copiar JSON'}</span>
                    </button>

                    <button
                      onClick={handleExportSecJson}
                      className="flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold px-3.5 py-1.5 rounded-xl shadow"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>Descargar JSON TE1</span>
                    </button>
                  </div>
                </div>

                <div className="bg-slate-950 p-4 rounded-2xl border border-slate-800 overflow-x-auto max-h-[480px]">
                  <pre className="text-[11px] font-mono text-emerald-300 leading-relaxed whitespace-pre">
                    {JSON.stringify(calculatedSecData, null, 2)}
                  </pre>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* SEC Validation Modal */}
      {showValidationModal && (
        <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 max-w-lg w-full space-y-4 shadow-2xl animate-in fade-in zoom-in-95">
            <div className="flex items-start justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2 text-amber-400">
                <ShieldAlert className="w-6 h-6" />
                <div>
                  <h3 className="text-base font-extrabold text-white">
                    Validación de Datos para e-Declarador SEC
                  </h3>
                  <p className="text-xs text-slate-400">
                    Inconsistencias detectadas antes de la tramitación oficial
                  </p>
                </div>
              </div>
              <button
                onClick={() => setShowValidationModal(false)}
                className="text-slate-400 hover:text-white p-1 rounded-lg"
              >
                ✕
              </button>
            </div>

            <p className="text-xs text-slate-300 leading-relaxed">
              La plataforma de la SEC exige que todos los datos del propietario, instalador y parámetros normativos RIC N°01 - N°10 coincidan con los formatos oficiales.
            </p>

            <div className="bg-slate-950 p-3 rounded-2xl border border-slate-800 space-y-2 max-h-52 overflow-y-auto">
              <span className="text-[11px] font-bold text-amber-400 block">
                Observaciones requeridas ({validation.errors.length}):
              </span>
              <ul className="space-y-1.5 text-xs text-slate-300">
                {validation.errors.map((err, idx) => (
                  <li key={idx} className="flex items-start gap-2 bg-slate-900/60 p-2 rounded-xl border border-slate-800">
                    <XCircle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                    <div>
                      <span className="font-bold text-amber-300 text-[10px] block">[{err.category}]</span>
                      <span className="text-[11px] text-slate-200">{err.message}</span>
                    </div>
                  </li>
                ))}
              </ul>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2 border-t border-slate-800">
              <button
                onClick={handleForceExportJson}
                className="px-3.5 py-2 text-xs font-semibold text-slate-400 hover:text-slate-200 bg-slate-800 hover:bg-slate-700 rounded-xl transition-all"
              >
                Exportar como Borrador
              </button>
              <button
                onClick={() => setShowValidationModal(false)}
                className="px-4 py-2 text-xs font-bold text-white bg-fuchsia-600 hover:bg-fuchsia-500 rounded-xl shadow transition-all"
              >
                Corregir Datos
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
