import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getNeovoltLogoDataUrl } from '../components/NeovoltLogo';
import { RoomData, HighAppliance, AutoGeneratedCircuit, ContractorConfig } from '../types';

export interface ExportTe1PdfOptions {
  owner: {
    name: string;
    rut: string;
    address: string;
    commune: string;
    region?: string;
    phone: string;
    email: string;
  };
  installer: {
    name: string;
    rut: string;
    secLicense: string;
    secClass: string;
    phone: string;
    commune: string;
  };
  project: {
    buildingDestination: string;
    distributorCompany: string;
    utilityContractNumber: string;
    groundingResistanceOhm: number;
    insulationResistanceMohm: number;
    rcdDischargeTimeMs: number;
    declarationType: string;
  };
  isThreePhase: boolean;
  totalDeclaredKw: number;
  feederLength: number;
  feederWireSection: number;
  rooms?: RoomData[];
  highAppliances?: HighAppliance[];
  circuits?: AutoGeneratedCircuit[];
  contractor?: ContractorConfig;
  installerSignatureUrl?: string;
  ownerSignatureUrl?: string;
}

export async function exportTe1DeclarationJsPdf(options: ExportTe1PdfOptions): Promise<jsPDF> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = 210;
  const margin = 12;
  const contentWidth = pageWidth - margin * 2;

  // 1. Fetch Neovolt Logo
  let logoDataUrl = '';
  try {
    logoDataUrl = await getNeovoltLogoDataUrl(false);
  } catch (e) {
    console.warn('Could not fetch logo data url', e);
  }

  // ----------------------------------------------------------------
  // 1. OFFICIAL CORPORATE & SEC TE1 HEADER BANNER
  // ----------------------------------------------------------------
  const headerHeight = 34;
  doc.setFillColor(11, 15, 25); // #0B0F19
  doc.rect(margin, margin, contentWidth, headerHeight, 'F');

  // Top Cyan Stripe (#00E5FF)
  doc.setFillColor(0, 229, 255);
  doc.rect(margin, margin, contentWidth, 2.5, 'F');

  // Left Magenta Accent Tag (#E83D84)
  doc.setFillColor(232, 61, 132);
  doc.rect(margin, margin + 2.5, 3.5, headerHeight - 2.5, 'F');

  let textLeft = margin + 8;
  if (logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, 'PNG', margin + 6, margin + 6, 42, 22);
      textLeft = margin + 52;
    } catch {
      textLeft = margin + 8;
    }
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('SUPERINTENDENCIA DE ELECTRICIDAD Y COMBUSTIBLES - SEC', textLeft, margin + 11);

  doc.setFontSize(8.5);
  doc.setTextColor(0, 229, 255);
  doc.text('DECLARACIÓN DE INSTALACIÓN ELÉCTRICA INTERIOR EN BT (FORMULARIO TE-1)', textLeft, margin + 17);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(203, 213, 225);
  doc.text('Pliegos Técnicos Normativos RIC N°01 al N°19 • D.S. N°08/2019 Ministerio de Energía', textLeft, margin + 23);
  doc.text(`Destino: ${options.project.buildingDestination} | Tipo: ${options.project.declarationType}`, textLeft, margin + 28);

  // Folio Badge
  const folioNumber = `TE1-${Date.now().toString().slice(-6)}`;
  doc.setFillColor(22, 30, 49);
  doc.roundedRect(pageWidth - margin - 46, margin + 5, 43, 24, 2, 2, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(232, 61, 132);
  doc.text('TRAMITACIÓN OFICIAL SEC', pageWidth - margin - 24, margin + 10, { align: 'center' });

  doc.setFontSize(9.5);
  doc.setTextColor(255, 255, 255);
  doc.text(folioNumber, pageWidth - margin - 24, margin + 17, { align: 'center' });

  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.setFont('helvetica', 'normal');
  doc.text(`Fecha: ${new Date().toLocaleDateString('es-CL')}`, pageWidth - margin - 24, margin + 23, { align: 'center' });

  let currentY = margin + headerHeight + 5;

  // ----------------------------------------------------------------
  // 2. SECCIÓN A: DATOS DEL PROPIETARIO Y UBICACIÓN DE LA INSTALACIÓN
  // ----------------------------------------------------------------
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.rect(margin, currentY, contentWidth, 23, 'FD');

  doc.setFillColor(11, 15, 25);
  doc.rect(margin, currentY, contentWidth, 5.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text('1. IDENTIFICACIÓN DEL PROPIETARIO / MANDANTE Y UBICACIÓN DE OBRA', margin + 3, currentY + 4);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(30, 41, 59);

  doc.text(`Nombre / Razón Social: ${options.owner.name || 'N/A'}`, margin + 3, currentY + 10);
  doc.text(`R.U.T.: ${options.owner.rut || 'N/A'}`, margin + 115, currentY + 10);

  doc.text(`Dirección Instalación: ${options.owner.address || 'Chile'}`, margin + 3, currentY + 15);
  doc.text(`Comuna / Región: ${options.owner.commune || 'Santiago'} - ${options.owner.region || 'R.M.'}`, margin + 115, currentY + 15);

  doc.text(`Teléfono Contacto: ${options.owner.phone || 'N/A'}`, margin + 3, currentY + 20);
  doc.text(`Correo Electrónico: ${options.owner.email || 'N/A'}`, margin + 115, currentY + 20);

  currentY += 27;

  // ----------------------------------------------------------------
  // 3. SECCIÓN B: DATOS DEL INSTALADOR AUTORIZADO SEC
  // ----------------------------------------------------------------
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.rect(margin, currentY, contentWidth, 20, 'FD');

  doc.setFillColor(11, 15, 25);
  doc.rect(margin, currentY, contentWidth, 5.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text('2. IDENTIFICACIÓN DEL INSTALADOR O PROFESIONAL RESPONSABLE SEC', margin + 3, currentY + 4);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(30, 41, 59);

  doc.text(`Nombre Instalador: ${options.installer.name || 'N/A'}`, margin + 3, currentY + 10);
  doc.text(`R.U.T. Instalador: ${options.installer.rut || 'N/A'}`, margin + 115, currentY + 10);

  doc.text(`Licencia SEC N°: ${options.installer.secLicense || 'N/A'} (Clase: ${options.installer.secClass || 'Clase A'})`, margin + 3, currentY + 16);
  doc.text(`Fono: ${options.installer.phone || 'N/A'} | Comuna: ${options.installer.commune || 'Santiago'}`, margin + 115, currentY + 16);

  currentY += 24;

  // ----------------------------------------------------------------
  // 4. SECCIÓN C: RESUMEN TÉCNICO Y SUMINISTRO ELÉCTRICO
  // ----------------------------------------------------------------
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.rect(margin, currentY, contentWidth, 18, 'FD');

  doc.setFillColor(11, 15, 25);
  doc.rect(margin, currentY, contentWidth, 5.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text('3. PARÁMETROS TÉCNICOS DEL EMPALME Y ALIMENTADOR PRINCIPAL', margin + 3, currentY + 4);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(30, 41, 59);

  const supplyStr = options.isThreePhase ? 'Trifásico 380V / 50 Hz' : 'Monofásico 220V / 50 Hz';
  doc.text(`Suministro: ${supplyStr} | Distribuidora: ${options.project.distributorCompany}`, margin + 3, currentY + 10);
  doc.text(`Potencia Total Declarada: ${options.totalDeclaredKw} kW`, margin + 115, currentY + 10);

  doc.text(`N° Cliente Distribuidora: ${options.project.utilityContractNumber}`, margin + 3, currentY + 15);
  doc.text(`Alimentador: ${options.feederWireSection} mm² EVA (${options.feederLength}m) - Ducto 25mm`, margin + 115, currentY + 15);

  currentY += 22;

  // ----------------------------------------------------------------
  // 5. SECCIÓN D: CUADRO DE CIRCUITOS Y CARGAS (autoTable)
  // ----------------------------------------------------------------
  const circuitRows = (options.circuits && options.circuits.length > 0)
    ? options.circuits.map((c) => [
        c.code,
        c.name,
        `${c.loadWatts} W`,
        c.breakerRating.split(' ')[0],
        c.wireSection.split(' ')[0] + ' mm²',
        c.conduitType.split(' ')[1] || 'Conduit 20mm',
        `RCD ${c.rcdAssignedGroup || 1}`,
      ])
    : [
        ['C1', 'Alumbrado General', '800 W', '1x10A/B', '1.5 mm²', 'Conduit 20mm', 'RCD 1 (30mA)'],
        ['C2', 'Enchufes Generales 10A', '1500 W', '1x16A/C', '2.5 mm²', 'Conduit 20mm', 'RCD 1 (30mA)'],
        ['C3', 'Cocina & Loggia', '2000 W', '1x16A/C', '2.5 mm²', 'Conduit 20mm', 'RCD 2 (30mA)'],
        ['C4', 'Termoeléctrico / Clima', '1500 W', '1x16A/C', '2.5 mm²', 'Conduit 20mm', 'RCD 2 (30mA)'],
      ];

  autoTable(doc, {
    startY: currentY,
    head: [['Cód', 'Descripción del Circuito', 'Potencia', 'Disyuntor In', 'Sección Cu', 'Canalización', 'Prot. Diferencial']],
    body: circuitRows,
    theme: 'striped',
    headStyles: {
      fillColor: [11, 15, 25],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7.5,
      cellPadding: 2,
    },
    styles: {
      fontSize: 7.2,
      cellPadding: 1.8,
      textColor: [15, 23, 42],
    },
    columnStyles: {
      0: { cellWidth: 12, halign: 'center', fontStyle: 'bold' },
      1: { cellWidth: 64 },
      2: { cellWidth: 20, halign: 'right' },
      3: { cellWidth: 22, halign: 'center' },
      4: { cellWidth: 22, halign: 'center' },
      5: { cellWidth: 26, halign: 'center' },
      6: { cellWidth: 20, halign: 'center' },
    },
    margin: { left: margin, right: margin },
  });

  currentY = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY + 4 : currentY + 50;

  // ----------------------------------------------------------------
  // 6. SECCIÓN E: PROTOCOLO DE ENSAYOS Y MEDICIONES RIC N°10
  // ----------------------------------------------------------------
  if (currentY > 225) {
    doc.addPage();
    currentY = margin;
  }

  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.rect(margin, currentY, contentWidth, 21, 'FD');

  doc.setFillColor(11, 15, 25);
  doc.rect(margin, currentY, contentWidth, 5.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text('4. PROTOCOLO DE ENSAYOS Y MEDICIONES NORMATIVAS (PLIEGO TÉCNICO RIC N°10)', margin + 3, currentY + 4);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(30, 41, 59);

  const isGroundOk = options.project.groundingResistanceOhm <= 20;
  const isIsoOk = options.project.insulationResistanceMohm >= 1.0;
  const isRcdOk = options.project.rcdDischargeTimeMs <= 30.0;

  doc.text(`• Resistencia de Puesta a Tierra: ${options.project.groundingResistanceOhm} Ω (${isGroundOk ? 'CONFORME ≤ 20Ω RIC N°06' : 'NO CONFORME'})`, margin + 3, currentY + 10);
  doc.text(`• Resistencia de Aislamiento: ${options.project.insulationResistanceMohm} MΩ (${isIsoOk ? 'CONFORME ≥ 1.0 MΩ RIC N°19' : 'NO CONFORME'})`, margin + 115, currentY + 10);

  doc.text(`• Tiempo de Disparo Diferencial RCD: ${options.project.rcdDischargeTimeMs} ms (${isRcdOk ? 'CONFORME ≤ 30ms RIC N°05' : 'NO CONFORME'})`, margin + 3, currentY + 16);
  doc.text(`• Tensión Fase-Neutro: ${options.isThreePhase ? '380V / 220V' : '220V'} (Frecuencia: 50 Hz ±1%)`, margin + 115, currentY + 16);

  currentY += 25;

  // ----------------------------------------------------------------
  // 7. SECCIÓN F: DECLARACIÓN JURADA Y CUADROS DE FIRMAS
  // ----------------------------------------------------------------
  if (currentY > 230) {
    doc.addPage();
    currentY = margin;
  }

  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.rect(margin, currentY, contentWidth, 38, 'FD');

  doc.setFillColor(11, 15, 25);
  doc.rect(margin, currentY, contentWidth, 5.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text('5. DECLARACIÓN JURADA Y ACEPTACIÓN DE RESPONSABILIDAD TÉCNICA Y LEGAL', margin + 3, currentY + 4);

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(6.8);
  doc.setTextColor(71, 85, 105);
  const legalText = 'El instalador electricista y el propietario declaran bajo juramento que las instalaciones eléctricas descritas en este documento han sido ejecutadas íntegramente conforme a las disposiciones del Reglamento de Seguridad de las Instalaciones de Consumo de Energía Eléctrica (RIC N°01 al N°19) y la Ley General de Servicios Eléctricos.';
  const splitLegal = doc.splitTextToSize(legalText, contentWidth - 6);
  doc.text(splitLegal, margin + 3, currentY + 9);

  // Cuadros de Firma (Izquierda: Instalador SEC, Derecha: Propietario)
  const boxWidth = (contentWidth - 8) / 2;
  const signBoxY = currentY + 17;

  // Firma Instalador
  doc.setDrawColor(148, 163, 184);
  doc.line(margin + 6, signBoxY + 12, margin + boxWidth - 6, signBoxY + 12);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(15, 23, 42);
  doc.text(options.installer.name || 'Instalador Autorizado SEC', margin + boxWidth / 2, signBoxY + 16, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.8);
  doc.text(`RUT: ${options.installer.rut} • Licencia SEC: ${options.installer.secLicense}`, margin + boxWidth / 2, signBoxY + 19, { align: 'center' });

  // Firma Propietario
  const rightBoxX = margin + boxWidth + 8;
  doc.line(rightBoxX + 6, signBoxY + 12, rightBoxX + boxWidth - 6, signBoxY + 12);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.text(options.owner.name || 'Propietario / Mandante', rightBoxX + boxWidth / 2, signBoxY + 16, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.8);
  doc.text(`RUT: ${options.owner.rut}`, rightBoxX + boxWidth / 2, signBoxY + 19, { align: 'center' });

  // Save PDF
  const ownerSlug = (options.owner.name || 'Propietario').replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`Declaracion_TE1_SEC_${ownerSlug}.pdf`);
  return doc;
}
