/**
 * Types & Interfaces for NEOVOLT PRO - SEC Chile Electrical Engine
 */

export interface BudgetHistoryRecord {
  id: string;
  projectId: string;
  timestamp: string;
  description: string;
  previousTotal: number;
  newTotal: number;
  previousItems: BudgetItem[];
  previousLaborCost: number;
}

export interface UserSession {
  email: string;
  name: string;
  secNumber: string;
  isLoggedIn: boolean;
  role: 'installer' | 'engineer' | 'admin';
  professionalTitle?: string;
  customGeminiApiKey?: string;
  googleAvatarUrl?: string;
}

export interface RoomDevice {
  id?: string;
  name: string;
  powerWatts: number;
  quantity: number;
  category?: string;
}

export interface RoomData {
  id: string;
  name: string;
  lightPoints: number;
  socketPoints: number;
  devices: RoomDevice[];
}

export interface HighAppliance {
  id: string;
  name: string;
  powerWatts: number;
  category: string;
  socketType: '10A' | '16A' | 'Conexión Directa';
  voltage: 220 | 380;
}

export interface AutoGeneratedCircuit {
  id: string;
  code: string; // e.g. "C1", "C2"
  name: string; // e.g. "Alumbrado Dormitorios"
  type: 'alumbrado' | 'enchufes' | 'fuerza_dedicada' | 'clima' | 'ev';
  loadWatts: number;
  currentAmps: number;
  breakerRating: string; // e.g. "1x10A Curva C 6kA"
  breakerAmps: number;
  wireSection: string; // e.g. "2.5 mm² EVA Libre Halógenos"
  conduitType: string; // e.g. "Tubo PVC Conduit 25mm"
  rcdAssignedGroup: number; // Index of assigned RCD (1, 2, 3...)
  pointsCount?: number;
  status?: 'active' | 'tripped' | 'off'; // For simulation
}

export interface BoardProtectionSpecs {
  igaRating: string; // e.g. "1x25A 6kA Curva C"
  igaAmps: number;
  dpsRating: string; // e.g. "1x Monofásico 275V 20kA (Tipo 2)"
  rcdList: {
    id: number;
    name: string;
    rating: string; // e.g. "2x25A 30mA Clase AC"
    circuitsAssigned: string[]; // e.g. ["C1", "C2", "C3"]
  }[];
  totalCircuitsCount: number;
  activeModulesNeeded: number;
  reserveModulesNeeded: number;
  totalModulesNeeded: number;
  recommendedEnclosureSize: string; // e.g. "Tablero DIN 18 Módulos"
  isThreePhase: boolean;
  calculatedInAmps: number;
  feederVoltageDropV: number;
  feederVoltageDropPercent: number;
}

export interface BudgetItem {
  id: string;
  name: string;
  quantity: number;
  price: number;
  category: string;
  unit?: string;
  imageUrl?: string;
  skuCode?: string;
  retailCode?: string;
}

export interface CatalogMaterialSpecifications {
  diametro?: string;
  calibre?: string;
  amperaje?: string;
  tension?: string;
  ipRating?: string;
  medidas?: string;
  tipoConexion?: string;
}

export interface CatalogMaterialItem {
  id: string;
  nombre: string;
  categoria: 'Canalizaciones y Conducción' | 'Insumos y Materiales de Montaje' | 'Accesorios, Aparatos y Protecciones';
  subcategoria: string;
  material: string;
  especificaciones?: CatalogMaterialSpecifications;
  unidadMedida: string;
  precioEstimado: number;
  skuCode: string;
  badge?: string;
  isPopular?: boolean;
}

export interface CatalogCategory {
  categoryName: string;
  items: BudgetItem[];
}

export interface CustomerDetails {
  id?: string;
  name: string;
  rut?: string;
  address: string;
  city?: string;
  phone: string;
  email: string;
  emergencyPhone: string;
  propertyType?: 'Residencial' | 'Comercial' | 'Industrial' | 'Comunidad';
  notes?: string;
}

export interface BankAccountDetails {
  bankName: string;
  accountType: string;
  accountNumber: string;
  holderName: string;
  holderRut: string;
  emailForNotify: string;
}

export interface ContractorConfig {
  senderEmail: string;
  companyName: string;
  installerName: string;
  secLicense: string;
  secClass: string;
  isSecCertified?: boolean; // Toggle SEC display on/off
  customProfessionalTitle?: string; // Custom title if not yet SEC certified or student
  rut: string;
  phone: string;
  address: string;
  customLogoUrl?: string;
  installerSignatureUrl?: string;
  bankDetails: BankAccountDetails;
}

export interface AiDiagnosticMessage {
  id: string;
  sender: 'user' | 'ai';
  text: string;
  timestamp: string;
  faultCategory?: string;
  toolsNeeded?: string[];
  alternativeWithoutTools?: string;
  safetyWarning?: string;
}

export interface DiagnosticQueryRequest {
  faultDescription: string;
  installationType?: string; // e.g. Monofásica, Trifásica, Residencial
  missingTools?: string[];
  contextNotes?: string;
}

export interface BoardWire {
  id: string;
  fromId: string;
  fromName: string;
  toId: string;
  toName: string;
  color: 'phase' | 'neutral' | 'earth' | 'busbar';
}

export interface PlacedBoardAccessory {
  instanceId: string;
  itemId: string;
  name: string;
  category: 'barras' | 'peines' | 'canalizacion' | 'senializacion' | 'protecciones' | 'medicion';
  type: string;
  dinModules: number;
  dropZone: string;
  colorClass: string;
}

export interface ProjectBoardConfig {
  boardCapacity?: 12 | 18 | 24 | 36 | 48 | 54 | 72;
  placedAccessories?: PlacedBoardAccessory[];
  customWires?: BoardWire[];
  customProtectionSpecs?: CustomProtectionSpecs;
  feederLength?: number;
  isThreePhase?: boolean;
  feederWireSection?: number;
  rooms?: RoomData[];
  highAppliances?: HighAppliance[];
}

export type ServiceTypeMode = 'census' | 'replacement' | 'maintenance' | 'diagnostic';

export interface ReplacementItem {
  id: string;
  name: string;
  category: 'Accesorios / Interruptores' | 'Iluminación' | 'Protecciones / Tableros' | 'Conductores / Canalizaciones' | 'Artefactos';
  location: string;
  quantity: number;
  reason: 'Quemado / Averiado' | 'Sin Tierra / Obsoleto' | 'Renovación Estética' | 'Aumento Capacidad' | 'Falta de Voltaje';
  unitMaterialPrice: number;
  unitLaborPrice: number;
}

export interface MaintenanceCheckItem {
  id: string;
  category: string;
  checkPoint: string;
  status: 'conforme' | 'observado' | 'critico' | 'na';
  observation: string;
  estimatedFixCost?: number;
}

export interface FaultDiagnosticData {
  id: string;
  faultType: string;
  location: string;
  circuitName: string;
  measuredVoltage?: number;
  measuredIsolation?: number;
  measuredLeakageCurrent?: number;
  rootCause: string;
  solutionApplied: string;
  requiredParts: { name: string; quantity: number; unitPrice: number }[];
  laborCost: number;
  status: 'En Diagnóstico' | 'Reparado & Probado' | 'Pendiente de Repuesto';
}

export interface ClientRecord {
  id: string;
  name: string;
  rut: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  propertyType: 'Residencial' | 'Comercial' | 'Industrial' | 'Comunidad';
  notes: string;
  createdAt: string;
  boardConfig?: ProjectBoardConfig;
  versionHistory?: ProjectVersion[];
}

export interface ClientSignature {
  signedBy: string;
  signedRut?: string;
  signedAt: string;
  signatureDataUrl: string;
  termsAccepted: boolean;
}

export interface WorkReportData {
  clientName: string;
  address: string;
  briefNotes: string;
  generatedAiReport: string;
  photoPaths: string[]; // Base64 or object URLs
  testResults: {
    isolationMOhms: number;
    earthResistanceOhms: number;
    rcdTripTimeMs: number;
  };
}

export interface RicNormRule {
  num: string;
  title: string;
  summary: string;
  detailText: string;
  keyPoints: string[];
}

export interface CustomProtectionSpecs {
  iga: {
    amps: number;
    curve: string; // 'Curva B' | 'Curva C' | 'Curva D'
    breakingCapacity: string; // '4.5kA' | '6kA' | '10kA'
    poles: string; // '1x' | '2x' | '3x'
  };
  dps: {
    voltage: string; // '275V' | '400V'
    dischargeCurrent: string; // '20kA' | '40kA'
  };
  rcds: Record<number, {
    amps: number;
    sensitivity: string; // '30mA' | '300mA'
    classType: string; // 'Clase AC' | 'Clase A' | 'Superinmunizado'
  }>;
  circuitBreakers: Record<string, {
    amps: number;
    curve: string;
    breakingCapacity: string;
    wireSection: string;
    pipeType: string;
    customName?: string;
  }>;
}

export interface ProjectAttachment {
  id: string;
  name: string;
  sizeBytes: number;
  type: string; // e.g. 'image/png' | 'application/pdf' | 'text/plain'
  dataUrl: string; // base64 / blob preview
  uploadedAt: string;
  notes?: string;
}

export interface ProjectScopeItem {
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
  unit: string; // 'unid', 'global', 'hora', 'punto', 'm'
  category: 'ARTEFACTOS' | 'REVISION_TECNICA' | 'MANO_DE_OBRA' | 'PROTECCIONES' | 'MATERIALES' | 'TRAMITES_SEC';
}

export interface CustomServiceType {
  id: string;
  name: string;
  description?: string;
  isDefault?: boolean;
}

export type ProjectType =
  | 'Mantención preventiva'
  | 'Instalación nueva'
  | 'Detección de falla'
  | 'Cambio de accesorios'
  | 'REEMPLAZO_ARTEFACTOS'
  | 'REVISION_INSPECCION'
  | 'AUMENTO_CAPACIDAD'
  | 'INSTALACION_NUEVA'
  | 'REPARACION_EMERGENCIA'
  | 'OTRO_SERVICIO'
  | string;


export interface ProjectVersion {
  id: string;
  timestamp: string;
  modifiedBy: string;
  changesSummary: string;
  materialsPriceOld: number;
  materialsPriceNew: number;
  laborPriceOld: number;
  laborPriceNew: number;
  scopeItemsOld?: ProjectScopeItem[];
}

export interface ElectricalProject {
  id: string;
  code: string; // e.g. "PRJ-2026-001"
  title: string;
  projectType: ProjectType;
  status: 'COTIZACION' | 'APROBADO' | 'EN_EJECUCION' | 'COMPLETADO' | 'CANCELADO';
  client: CustomerDetails;
  description: string;
  isFaultDiagnosis?: boolean;
  faultDiagnosisDetails?: string;
  isModification?: boolean;
  modificationDetails?: string;
  attachments: ProjectAttachment[];
  scopeItems: ProjectScopeItem[];
  laborPrice: number;
  materialsPrice: number;
  totalPrice: number;
  includeTaxIVA: boolean;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  targetDeadline?: string;
  boardConfig?: ProjectBoardConfig;
  versionHistory?: ProjectVersion[];
}

